# BhumiGuard BD — STEP 4: Synthetic People and Parcel Registry

This notebook creates a small privacy-safe synthetic registry for testing
P3: Fraud & Double-Selling detection.

No real citizen or real land record is used.

Initial scope:
- 5 synthetic persons
- 5 synthetic parcels

In [890]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\shuvo\appdata\local\programs\python\python313\lib\site-packages (3.0.6)
Requirement already satisfied: numpy>=1.26.0 in c:\users\shuvo\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.5.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\shuvo\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\shuvo\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.5 in c:\users\shuvo\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [891]:
import pandas as pd

print("Pandas import: OK")

Pandas import: OK

## Synthetic People

Create fictional internal person records.

Only an internal ID and display name are required at this stage.

In [892]:
people_data = [
    {
        "person_id": "P001",
        "name_bn": "ব্যক্তি-০০১"
    },
    {
        "person_id": "P002",
        "name_bn": "ব্যক্তি-০০২"
    },
    {
        "person_id": "P003",
        "name_bn": "ব্যক্তি-০০৩"
    },
    {
        "person_id": "P004",
        "name_bn": "ব্যক্তি-০০৪"
    },
    {
        "person_id": "P005",
        "name_bn": "ব্যক্তি-০০৫"
    }
]

people_df = pd.DataFrame(people_data)

people_df

  person_id      name_bn
0      P001  ব্যক্তি-০০১
1      P002  ব্যক্তি-০০২
2      P003  ব্যক্তি-০০৩
3      P004  ব্যক্তি-০০৪
4      P005  ব্যক্তি-০০৫

In [893]:
print("People records:", len(people_df))
print("Unique person IDs:", people_df["person_id"].nunique())
print("Missing person IDs:", people_df["person_id"].isna().sum())
print("Duplicate person IDs:", people_df["person_id"].duplicated().sum())

People records: 5
Unique person IDs: 5
Missing person IDs: 0
Duplicate person IDs: 0

## Synthetic Parcel Registry

Create five fictional land parcels using the field structure derived
from the Saf Kabala sample.

These are demonstration records only.

In [894]:
parcel_data = [
    {
        "parcel_id": "PAR001",
        "district": "Demo-District-A",
        "upazila": "Demo-Upazila-A",
        "mouza": "Demo-Mouza-01",
        "survey_type": "RS",
        "khatian_no": "205",
        "dag_no": "731",
        "total_area_decimal": 20.0
    },
    {
        "parcel_id": "PAR002",
        "district": "Demo-District-A",
        "upazila": "Demo-Upazila-A",
        "mouza": "Demo-Mouza-01",
        "survey_type": "RS",
        "khatian_no": "206",
        "dag_no": "732",
        "total_area_decimal": 15.0
    },
    {
        "parcel_id": "PAR003",
        "district": "Demo-District-A",
        "upazila": "Demo-Upazila-B",
        "mouza": "Demo-Mouza-02",
        "survey_type": "BS",
        "khatian_no": "301",
        "dag_no": "810",
        "total_area_decimal": 30.0
    },
    {
        "parcel_id": "PAR004",
        "district": "Demo-District-B",
        "upazila": "Demo-Upazila-C",
        "mouza": "Demo-Mouza-03",
        "survey_type": "SA",
        "khatian_no": "115",
        "dag_no": "425",
        "total_area_decimal": 12.0
    },
    {
        "parcel_id": "PAR005",
        "district": "Demo-District-B",
        "upazila": "Demo-Upazila-C",
        "mouza": "Demo-Mouza-04",
        "survey_type": "CS",
        "khatian_no": "090",
        "dag_no": "512",
        "total_area_decimal": 25.0
    }
]

parcels_df = pd.DataFrame(parcel_data)

parcels_df

,parcel_id,district,upazila,mouza,survey_type,khatian_no,dag_no,total_area_decimal
0,PAR001,Demo-District-A,Demo-Upazila-A,Demo-Mouza-01,RS,205,731,20.0
1,PAR002,Demo-District-A,Demo-Upazila-A,Demo-Mouza-01,RS,206,732,15.0
2,PAR003,Demo-District-A,Demo-Upazila-B,Demo-Mouza-02,BS,301,810,30.0
3,PAR004,Demo-District-B,Demo-Upazila-C,Demo-Mouza-03,SA,115,425,12.0
4,PAR005,Demo-District-B,Demo-Upazila-C,Demo-Mouza-04,CS,090,512,25.0

In [895]:
print("Parcel records:", len(parcels_df))
print("Unique parcel IDs:", parcels_df["parcel_id"].nunique())
print("Duplicate parcel IDs:", parcels_df["parcel_id"].duplicated().sum())
print("Missing parcel IDs:", parcels_df["parcel_id"].isna().sum())

print("\nTotal synthetic land area:",
      parcels_df["total_area_decimal"].sum(),
      "decimal")

Parcel records: 5
Unique parcel IDs: 5
Duplicate parcel IDs: 0
Missing parcel IDs: 0

Total synthetic land area: 102.0 decimal

In [896]:
required_parcel_fields = [
    "parcel_id",
    "district",
    "upazila",
    "mouza",
    "survey_type",
    "khatian_no",
    "dag_no",
    "total_area_decimal"
]

missing_counts = parcels_df[required_parcel_fields].isna().sum()

print("Missing values by field:")
print(missing_counts)

Missing values by field:
parcel_id             0
district              0
upazila               0
mouza                 0
survey_type           0
khatian_no            0
dag_no                0
total_area_decimal    0
dtype: int64

In [897]:
identity_fields = [
    "district",
    "upazila",
    "mouza",
    "survey_type",
    "khatian_no",
    "dag_no"
]

duplicate_identity = parcels_df.duplicated(
    subset=identity_fields
).sum()

print("Duplicate parcel identities:", duplicate_identity)

Duplicate parcel identities: 0

In [898]:
print("STEP 4 SUMMARY")
print("--------------")

print("Synthetic people:", len(people_df))
print("Unique people:", people_df["person_id"].nunique())

print("\nSynthetic parcels:", len(parcels_df))
print("Unique parcels:", parcels_df["parcel_id"].nunique())

print(
    "Total land area:",
    parcels_df["total_area_decimal"].sum(),
    "decimal"
)

print("Duplicate parcel identities:", duplicate_identity)

print("\nSynthetic Registry Status: READY")

STEP 4 SUMMARY
--------------
Synthetic people: 5
Unique people: 5

Synthetic parcels: 5
Unique parcels: 5
Total land area: 102.0 decimal
Duplicate parcel identities: 0

Synthetic Registry Status: READY

# STEP 5 — Initial Ownership Registry

Create the initial valid ownership state for the five synthetic parcels.

This represents the ownership state before any new transaction is processed.

In [899]:
ownership_data = [
    {
        "ownership_id": "OWN001",
        "parcel_id": "PAR001",
        "owner_id": "P001",
        "owned_area_decimal": 20.0,
        "valid_from": "2025-01-01",
        "status": "ACTIVE"
    },
    {
        "ownership_id": "OWN002",
        "parcel_id": "PAR002",
        "owner_id": "P002",
        "owned_area_decimal": 15.0,
        "valid_from": "2025-01-01",
        "status": "ACTIVE"
    },
    {
        "ownership_id": "OWN003",
        "parcel_id": "PAR003",
        "owner_id": "P003",
        "owned_area_decimal": 30.0,
        "valid_from": "2025-01-01",
        "status": "ACTIVE"
    },
    {
        "ownership_id": "OWN004",
        "parcel_id": "PAR004",
        "owner_id": "P004",
        "owned_area_decimal": 12.0,
        "valid_from": "2025-01-01",
        "status": "ACTIVE"
    },
    {
        "ownership_id": "OWN005",
        "parcel_id": "PAR005",
        "owner_id": "P005",
        "owned_area_decimal": 25.0,
        "valid_from": "2025-01-01",
        "status": "ACTIVE"
    }
]

ownership_df = pd.DataFrame(ownership_data)

ownership_df

  ownership_id parcel_id owner_id  owned_area_decimal  valid_from  status
0       OWN001    PAR001     P001                20.0  2025-01-01  ACTIVE
1       OWN002    PAR002     P002                15.0  2025-01-01  ACTIVE
2       OWN003    PAR003     P003                30.0  2025-01-01  ACTIVE
3       OWN004    PAR004     P004                12.0  2025-01-01  ACTIVE
4       OWN005    PAR005     P005                25.0  2025-01-01  ACTIVE

In [900]:
print("Ownership records:", len(ownership_df))
print("Unique ownership IDs:", ownership_df["ownership_id"].nunique())
print("Duplicate ownership IDs:", ownership_df["ownership_id"].duplicated().sum())

Ownership records: 5
Unique ownership IDs: 5
Duplicate ownership IDs: 0

In [901]:
valid_person_ids = set(people_df["person_id"])

invalid_owners = ownership_df[
    ~ownership_df["owner_id"].isin(valid_person_ids)
]

print("Invalid owner references:", len(invalid_owners))

Invalid owner references: 0

In [902]:
valid_parcel_ids = set(parcels_df["parcel_id"])

invalid_parcels = ownership_df[
    ~ownership_df["parcel_id"].isin(valid_parcel_ids)
]

print("Invalid parcel references:", len(invalid_parcels))

Invalid parcel references: 0

In [903]:
ownership_check = ownership_df.merge(
    parcels_df[
        ["parcel_id", "total_area_decimal"]
    ],
    on="parcel_id",
    how="left"
)

ownership_check["area_match"] = (
    ownership_check["owned_area_decimal"]
    == ownership_check["total_area_decimal"]
)

ownership_check[
    [
        "parcel_id",
        "owner_id",
        "owned_area_decimal",
        "total_area_decimal",
        "area_match"
    ]
]

  parcel_id owner_id  owned_area_decimal  total_area_decimal  area_match
0    PAR001     P001                20.0                20.0        True
1    PAR002     P002                15.0                15.0        True
2    PAR003     P003                30.0                30.0        True
3    PAR004     P004                12.0                12.0        True
4    PAR005     P005                25.0                25.0        True

In [904]:
active_ownership = ownership_df[
    ownership_df["status"] == "ACTIVE"
]

parcel_owned_totals = (
    active_ownership
    .groupby("parcel_id")["owned_area_decimal"]
    .sum()
    .reset_index()
)

parcel_owned_totals = parcel_owned_totals.merge(
    parcels_df[
        ["parcel_id", "total_area_decimal"]
    ],
    on="parcel_id",
    how="left"
)

parcel_owned_totals["ownership_valid"] = (
    parcel_owned_totals["owned_area_decimal"]
    <= parcel_owned_totals["total_area_decimal"]
)

parcel_owned_totals

  parcel_id  owned_area_decimal  total_area_decimal  ownership_valid
0    PAR001                20.0                20.0             True
1    PAR002                15.0                15.0             True
2    PAR003                30.0                30.0             True
3    PAR004                12.0                12.0             True
4    PAR005                25.0                25.0             True

In [905]:
current_owner_view = ownership_df.merge(
    people_df,
    left_on="owner_id",
    right_on="person_id",
    how="left"
)

current_owner_view = current_owner_view[
    [
        "parcel_id",
        "owner_id",
        "name_bn",
        "owned_area_decimal",
        "status"
    ]
]

current_owner_view

  parcel_id owner_id      name_bn  owned_area_decimal  status
0    PAR001     P001  ব্যক্তি-০০১                20.0  ACTIVE
1    PAR002     P002  ব্যক্তি-০০২                15.0  ACTIVE
2    PAR003     P003  ব্যক্তি-০০৩                30.0  ACTIVE
3    PAR004     P004  ব্যক্তি-০০৪                12.0  ACTIVE
4    PAR005     P005  ব্যক্তি-০০৫                25.0  ACTIVE

In [906]:
print("STEP 5 SUMMARY")
print("--------------")

print("Ownership records:", len(ownership_df))
print("Active ownership records:", len(active_ownership))

print(
    "Invalid owner references:",
    len(invalid_owners)
)

print(
    "Invalid parcel references:",
    len(invalid_parcels)
)

invalid_area_records = parcel_owned_totals[
    ~parcel_owned_totals["ownership_valid"]
]

print(
    "Invalid ownership-area records:",
    len(invalid_area_records)
)

print("\nInitial Ownership Registry Status: READY")

STEP 5 SUMMARY
--------------
Ownership records: 5
Active ownership records: 5
Invalid owner references: 0
Invalid parcel references: 0
Invalid ownership-area records: 0

Initial Ownership Registry Status: READY

# STEP 6 — First Valid Land Transaction

Create and process the first legitimate land transfer.

Scenario:

- Seller: P001
- Buyer: P002
- Parcel: PAR001
- Seller currently owns: 20 decimal
- Transfer amount: 5 decimal

Expected result:

- P001 remaining ownership: 15 decimal
- P002 new ownership: 5 decimal

In [907]:
first_transaction = {
    "deed_id": "DEED001",
    "deed_type": "SAF_KABALA",
    "execution_date": "2026-01-10",

    "seller_id": "P001",
    "buyer_id": "P002",

    "parcel_id": "PAR001",
    "transferred_area_decimal": 5.0,

    "previous_deed_reference": None,
    "transaction_status": "PENDING"
}

first_transaction

{'deed_id': 'DEED001',
 'deed_type': 'SAF_KABALA',
 'execution_date': '2026-01-10',
 'seller_id': 'P001',
 'buyer_id': 'P002',
 'parcel_id': 'PAR001',
 'transferred_area_decimal': 5.0,
 'previous_deed_reference': None,
 'transaction_status': 'PENDING'}

In [908]:
seller_exists = (
    first_transaction["seller_id"]
    in set(people_df["person_id"])
)

buyer_exists = (
    first_transaction["buyer_id"]
    in set(people_df["person_id"])
)

print("Seller exists:", seller_exists)
print("Buyer exists:", buyer_exists)

Seller exists: True
Buyer exists: True

In [909]:
parcel_exists = (
    first_transaction["parcel_id"]
    in set(parcels_df["parcel_id"])
)

print("Parcel exists:", parcel_exists)

Parcel exists: True

In [910]:
seller_record = ownership_df[
    (ownership_df["parcel_id"] == first_transaction["parcel_id"]) &
    (ownership_df["owner_id"] == first_transaction["seller_id"]) &
    (ownership_df["status"] == "ACTIVE")
]

seller_record

  ownership_id parcel_id owner_id  owned_area_decimal  valid_from  status
0       OWN001    PAR001     P001                20.0  2025-01-01  ACTIVE

In [911]:
if len(seller_record) == 1:
    seller_available_area = seller_record.iloc[0]["owned_area_decimal"]
else:
    seller_available_area = 0.0

print("Seller available area:", seller_available_area)
print(
    "Requested transfer:",
    first_transaction["transferred_area_decimal"]
)

Seller available area: 20.0
Requested transfer: 5.0

In [912]:
transfer_amount = first_transaction["transferred_area_decimal"]

valid_transfer = (
    seller_exists
    and buyer_exists
    and parcel_exists
    and seller_available_area >= transfer_amount
    and transfer_amount > 0
)

print("Valid transfer:", valid_transfer)

Valid transfer: True

In [913]:
ownership_before_transaction = ownership_df.copy()

print("Ownership snapshot saved.")

Ownership snapshot saved.

In [914]:
current_ownership_df = ownership_df.copy()

seller_mask = (
    (current_ownership_df["parcel_id"] == first_transaction["parcel_id"]) &
    (current_ownership_df["owner_id"] == first_transaction["seller_id"]) &
    (current_ownership_df["status"] == "ACTIVE")
)

current_ownership_df.loc[
    seller_mask,
    "owned_area_decimal"
] -= transfer_amount

In [915]:
new_buyer_ownership = {
    "ownership_id": "OWN006",
    "parcel_id": first_transaction["parcel_id"],
    "owner_id": first_transaction["buyer_id"],
    "owned_area_decimal": transfer_amount,
    "valid_from": first_transaction["execution_date"],
    "status": "ACTIVE"
}

current_ownership_df = pd.concat(
    [
        current_ownership_df,
        pd.DataFrame([new_buyer_ownership])
    ],
    ignore_index=True
)

current_ownership_df

  ownership_id parcel_id owner_id  owned_area_decimal  valid_from  status
0       OWN001    PAR001     P001                15.0  2025-01-01  ACTIVE
1       OWN002    PAR002     P002                15.0  2025-01-01  ACTIVE
2       OWN003    PAR003     P003                30.0  2025-01-01  ACTIVE
3       OWN004    PAR004     P004                12.0  2025-01-01  ACTIVE
4       OWN005    PAR005     P005                25.0  2025-01-01  ACTIVE
5       OWN006    PAR001     P002                 5.0  2026-01-10  ACTIVE

In [916]:
par001_ownership = current_ownership_df[
    (current_ownership_df["parcel_id"] == "PAR001") &
    (current_ownership_df["status"] == "ACTIVE")
][
    [
        "owner_id",
        "owned_area_decimal"
    ]
]

par001_ownership

  owner_id  owned_area_decimal
0     P001                15.0
5     P002                 5.0

In [917]:
par001_total_owned = par001_ownership[
    "owned_area_decimal"
].sum()

par001_total_area = parcels_df.loc[
    parcels_df["parcel_id"] == "PAR001",
    "total_area_decimal"
].iloc[0]

print("Parcel total area:", par001_total_area)
print("Current total ownership:", par001_total_owned)

print(
    "Ownership conserved:",
    par001_total_owned == par001_total_area
)

Parcel total area: 20.0
Current total ownership: 20.0
Ownership conserved: True

In [918]:
first_transaction["transaction_status"] = "VALID"

transactions_df = pd.DataFrame(
    [first_transaction]
)

transactions_df

,deed_id,deed_type,execution_date,seller_id,buyer_id,parcel_id,transferred_area_decimal,previous_deed_reference,transaction_status
0,DEED001,SAF_KABALA,2026-01-10,P001,P002,PAR001,5.0,None,VALID

In [919]:
print("BEFORE TRANSACTION")
print("------------------")

print(
    ownership_before_transaction[
        ownership_before_transaction["parcel_id"] == "PAR001"
    ][
        ["owner_id", "owned_area_decimal"]
    ]
)

print("\nAFTER TRANSACTION")
print("-----------------")

print(
    current_ownership_df[
        current_ownership_df["parcel_id"] == "PAR001"
    ][
        ["owner_id", "owned_area_decimal"]
    ]
)

BEFORE TRANSACTION
------------------
  owner_id  owned_area_decimal
0     P001                20.0

AFTER TRANSACTION
-----------------
  owner_id  owned_area_decimal
0     P001                15.0
5     P002                 5.0

In [920]:
seller_remaining = current_ownership_df.loc[
    (current_ownership_df["parcel_id"] == "PAR001") &
    (current_ownership_df["owner_id"] == "P001"),
    "owned_area_decimal"
].iloc[0]

buyer_owned = current_ownership_df.loc[
    (current_ownership_df["parcel_id"] == "PAR001") &
    (current_ownership_df["owner_id"] == "P002"),
    "owned_area_decimal"
].iloc[0]

print("STEP 6 SUMMARY")
print("--------------")

print("Deed ID:", first_transaction["deed_id"])
print("Transaction valid:", valid_transfer)

print("\nParcel:", first_transaction["parcel_id"])
print("Transferred area:", transfer_amount)

print("\nSeller remaining:", seller_remaining)
print("Buyer ownership:", buyer_owned)

print(
    "Total ownership:",
    seller_remaining + buyer_owned
)

print(
    "Ownership conserved:",
    seller_remaining + buyer_owned == par001_total_area
)

print("\nValid Transaction Processing: PASS")

STEP 6 SUMMARY
--------------
Deed ID: DEED001
Transaction valid: True

Parcel: PAR001
Transferred area: 5.0

Seller remaining: 15.0
Buyer ownership: 5.0
Total ownership: 20.0
Ownership conserved: True

Valid Transaction Processing: PASS

# STEP 7 — ParcelKey and Land Field Normalization

Normalize parcel-identifying fields so that formatting differences do not
create false mismatches.

Examples:

- ৭৩১ → 731
- ০০৭৩১ → 731
- দাগ নং ৭৩১ → 731
- C.S. → CS
- আর এস → RS

The normalized fields will be used to create a stable ParcelKey.

In [921]:
import re
import unicodedata

print("Normalization libraries: READY")

Normalization libraries: READY

## Bangla Digit Normalization

Convert Bengali digits to ASCII digits before matching land identifiers.

In [922]:
BANGLA_DIGITS = str.maketrans(
    "০১২৩৪৫৬৭৮৯",
    "0123456789"
)

def bangla_to_english_digits(value):
    if value is None:
        return None

    value = str(value)
    return value.translate(BANGLA_DIGITS)

In [923]:
print(bangla_to_english_digits("৭৩১"))
print(bangla_to_english_digits("২০৫"))
print(bangla_to_english_digits("০০৭৩১"))

731
205
00731

In [924]:
def normalize_land_number(value):
    if value is None:
        return None

    value = bangla_to_english_digits(value)

    value = unicodedata.normalize("NFKC", value)

    value = value.strip()

    labels = [
        "দাগ নং",
        "দাগ নম্বর",
        "দাগ",
        "খতিয়ান নং",
        "খতিয়ান নং",
        "খতিয়ান নম্বর",
        "খতিয়ান নম্বর",
        "খতিয়ান",
        "খতিয়ান",
        "নং",
        "নম্বর",
        "NO.",
        "NO"
    ]

    for label in labels:
        value = value.replace(label, "")

    value = value.strip()

    # Current MVP: retain numeric characters only
    digits = re.sub(r"[^0-9]", "", value)

    if digits == "":
        return None

    # Remove unnecessary leading zeros
    return str(int(digits))

In [925]:
test_values = [
    "731",
    "৭৩১",
    "০০৭৩১",
    "দাগ নং ৭৩১",
    "দাগ নম্বর: 731",
]

for value in test_values:
    print(
        repr(value),
        "->",
        normalize_land_number(value)
    )

'731' -> 731
'৭৩১' -> 731
'০০৭৩১' -> 731
'দাগ নং ৭৩১' -> 731
'দাগ নম্বর: 731' -> 731

In [926]:
SURVEY_ALIASES = {
    "CS": "CS",
    "C S": "CS",
    "C.S": "CS",
    "C.S.": "CS",
    "সি এস": "CS",

    "SA": "SA",
    "S A": "SA",
    "S.A": "SA",
    "S.A.": "SA",
    "এস এ": "SA",

    "RS": "RS",
    "R S": "RS",
    "R.S": "RS",
    "R.S.": "RS",
    "আর এস": "RS",

    "BS": "BS",
    "B S": "BS",
    "B.S": "BS",
    "B.S.": "BS",
    "বি এস": "BS",
}

def normalize_survey_type(value):
    if value is None:
        return None

    value = unicodedata.normalize(
        "NFKC",
        str(value)
    )

    value = " ".join(value.strip().upper().split())

    return SURVEY_ALIASES.get(value, value)

In [927]:
survey_tests = [
    "RS",
    "R.S.",
    "r s",
    "আর এস",
    "C.S.",
    "সি এস",
    "বি এস"
]

for value in survey_tests:
    print(
        repr(value),
        "->",
        normalize_survey_type(value)
    )

'RS' -> RS
'R.S.' -> RS
'r s' -> RS
'আর এস' -> RS
'C.S.' -> CS
'সি এস' -> CS
'বি এস' -> BS

In [928]:
def normalize_location(value):
    if value is None:
        return None

    value = unicodedata.normalize(
        "NFKC",
        str(value)
    )

    value = " ".join(value.strip().split())

    return value.upper()

In [929]:
location_tests = [
    "Demo-District-A",
    " demo-district-a ",
    "Demo-District-A   "
]

for value in location_tests:
    print(
        repr(value),
        "->",
        normalize_location(value)
    )

'Demo-District-A' -> DEMO-DISTRICT-A
' demo-district-a ' -> DEMO-DISTRICT-A
'Demo-District-A   ' -> DEMO-DISTRICT-A

In [930]:
def create_parcel_key(
    district,
    upazila,
    mouza,
    survey_type,
    khatian_no,
    dag_no
):
    district_n = normalize_location(district)
    upazila_n = normalize_location(upazila)
    mouza_n = normalize_location(mouza)

    survey_n = normalize_survey_type(survey_type)

    khatian_n = normalize_land_number(khatian_no)
    dag_n = normalize_land_number(dag_no)

    components = [
        district_n,
        upazila_n,
        mouza_n,
        survey_n,
        khatian_n,
        dag_n
    ]

    if any(value is None for value in components):
        return None

    return "|".join(components)

In [931]:
normalized_parcels_df = parcels_df.copy()

normalized_parcels_df["parcel_key"] = normalized_parcels_df.apply(
    lambda row: create_parcel_key(
        row["district"],
        row["upazila"],
        row["mouza"],
        row["survey_type"],
        row["khatian_no"],
        row["dag_no"]
    ),
    axis=1
)

normalized_parcels_df[
    [
        "parcel_id",
        "parcel_key"
    ]
]

  parcel_id                                         parcel_key
0    PAR001  DEMO-DISTRICT-A|DEMO-UPAZILA-A|DEMO-MOUZA-01|R...
1    PAR002  DEMO-DISTRICT-A|DEMO-UPAZILA-A|DEMO-MOUZA-01|R...
2    PAR003  DEMO-DISTRICT-A|DEMO-UPAZILA-B|DEMO-MOUZA-02|B...
3    PAR004  DEMO-DISTRICT-B|DEMO-UPAZILA-C|DEMO-MOUZA-03|S...
4    PAR005  DEMO-DISTRICT-B|DEMO-UPAZILA-C|DEMO-MOUZA-04|C...

In [932]:
print(
    "Parcel records:",
    len(normalized_parcels_df)
)

print(
    "Unique ParcelKeys:",
    normalized_parcels_df["parcel_key"].nunique()
)

print(
    "Duplicate ParcelKeys:",
    normalized_parcels_df["parcel_key"].duplicated().sum()
)

print(
    "Missing ParcelKeys:",
    normalized_parcels_df["parcel_key"].isna().sum()
)

Parcel records: 5
Unique ParcelKeys: 5
Duplicate ParcelKeys: 0
Missing ParcelKeys: 0

In [933]:
key_a = create_parcel_key(
    district="Demo-District-A",
    upazila="Demo-Upazila-A",
    mouza="Demo-Mouza-01",
    survey_type="RS",
    khatian_no="205",
    dag_no="731"
)

print(key_a)

DEMO-DISTRICT-A|DEMO-UPAZILA-A|DEMO-MOUZA-01|RS|205|731

In [934]:
key_b = create_parcel_key(
    district=" demo-district-a ",
    upazila="Demo-Upazila-A",
    mouza="Demo-Mouza-01",
    survey_type="আর এস",
    khatian_no="খতিয়ান নং ২০৫",
    dag_no="দাগ নং ০০৭৩১"
)

print(key_b)

DEMO-DISTRICT-A|DEMO-UPAZILA-A|DEMO-MOUZA-01|RS|205|731

In [935]:
print("Key A:", key_a)
print("Key B:", key_b)

print(
    "Same parcel:",
    key_a == key_b
)

Key A: DEMO-DISTRICT-A|DEMO-UPAZILA-A|DEMO-MOUZA-01|RS|205|731
Key B: DEMO-DISTRICT-A|DEMO-UPAZILA-A|DEMO-MOUZA-01|RS|205|731
Same parcel: True

In [936]:
print("STEP 7 SUMMARY")
print("--------------")

print(
    "Parcel records:",
    len(normalized_parcels_df)
)

print(
    "Unique ParcelKeys:",
    normalized_parcels_df["parcel_key"].nunique()
)

print(
    "Duplicate ParcelKeys:",
    normalized_parcels_df["parcel_key"].duplicated().sum()
)

print(
    "Missing ParcelKeys:",
    normalized_parcels_df["parcel_key"].isna().sum()
)

print(
    "Bangla digit normalization:",
    normalize_land_number("দাগ নং ০০৭৩১")
)

print(
    "Survey normalization:",
    normalize_survey_type("আর এস")
)

print(
    "Variant parcel matching:",
    key_a == key_b
)

print("\nParcel Normalization Status: READY")

STEP 7 SUMMARY
--------------
Parcel records: 5
Unique ParcelKeys: 5
Duplicate ParcelKeys: 0
Missing ParcelKeys: 0
Bangla digit normalization: 731
Survey normalization: RS
Variant parcel matching: True

Parcel Normalization Status: READY

In [937]:
def get_owner_area(ledger_df, parcel_id, owner_id):
    rows = ledger_df[
        (ledger_df["parcel_id"] == parcel_id) &
        (ledger_df["owner_id"] == owner_id) &
        (ledger_df["status"] == "ACTIVE")
    ]

    if rows.empty:
        return 0.0

    return float(rows["owned_area_decimal"].sum())

In [938]:
print(
    "P001 owns PAR001:",
    get_owner_area(
        ownership_df,
        "PAR001",
        "P001"
    )
)

print(
    "P002 owns PAR001:",
    get_owner_area(
        ownership_df,
        "PAR001",
        "P002"
    )
)

P001 owns PAR001: 20.0
P002 owns PAR001: 0.0

In [939]:
def next_ownership_id(ledger_df):
    numbers = []

    for value in ledger_df["ownership_id"]:
        value = str(value)

        if value.startswith("OWN"):
            number = value.replace("OWN", "")

            if number.isdigit():
                numbers.append(int(number))

    next_number = max(numbers, default=0) + 1

    return f"OWN{next_number:03d}"

In [940]:
print(
    "Next ownership ID:",
    next_ownership_id(ownership_df)
)

Next ownership ID: OWN006

In [941]:
def check_ledger_integrity(ledger_df, parcels_df):

    active = ledger_df[
        ledger_df["status"] == "ACTIVE"
    ].copy()

    totals = (
        active
        .groupby("parcel_id")["owned_area_decimal"]
        .sum()
        .reset_index()
    )

    totals = totals.merge(
        parcels_df[
            ["parcel_id", "total_area_decimal"]
        ],
        on="parcel_id",
        how="left"
    )

    totals["valid"] = (
        (totals["owned_area_decimal"] >= 0) &
        (
            totals["owned_area_decimal"]
            <= totals["total_area_decimal"]
        )
    )

    negative_rows = ledger_df[
        ledger_df["owned_area_decimal"] < 0
    ]

    return (
        totals["valid"].all()
        and negative_rows.empty
    )

In [942]:
print(
    "Initial ledger integrity:",
    check_ledger_integrity(
        ownership_df,
        parcels_df
    )
)

Initial ledger integrity: True

In [943]:
def process_transfer(
    ledger_df,
    transaction,
    people_df,
    parcels_df
):
    # Work on a copy
    updated_ledger = ledger_df.copy()

    seller_id = transaction["seller_id"]
    buyer_id = transaction["buyer_id"]
    parcel_id = transaction["parcel_id"]

    transfer_area = float(
        transaction["transferred_area_decimal"]
    )

    # Basic reference checks
    person_ids = set(people_df["person_id"])
    parcel_ids = set(parcels_df["parcel_id"])

    if seller_id not in person_ids:
        return ledger_df.copy(), {
            "valid": False,
            "reason": "SELLER_NOT_FOUND"
        }

    if buyer_id not in person_ids:
        return ledger_df.copy(), {
            "valid": False,
            "reason": "BUYER_NOT_FOUND"
        }

    if parcel_id not in parcel_ids:
        return ledger_df.copy(), {
            "valid": False,
            "reason": "PARCEL_NOT_FOUND"
        }

    if seller_id == buyer_id:
        return ledger_df.copy(), {
            "valid": False,
            "reason": "SELLER_BUYER_SAME"
        }

    if transfer_area <= 0:
        return ledger_df.copy(), {
            "valid": False,
            "reason": "INVALID_TRANSFER_AREA"
        }

    # Seller ownership check
    seller_available = get_owner_area(
        updated_ledger,
        parcel_id,
        seller_id
    )

    if seller_available == 0:
        return ledger_df.copy(), {
            "valid": False,
            "reason": "SELLER_NOT_OWNER",
            "seller_available": seller_available
        }

    if transfer_area > seller_available:
        return ledger_df.copy(), {
            "valid": False,
            "reason": "INSUFFICIENT_OWNERSHIP",
            "seller_available": seller_available,
            "requested_area": transfer_area
        }

    # Update seller
    seller_mask = (
        (updated_ledger["parcel_id"] == parcel_id) &
        (updated_ledger["owner_id"] == seller_id) &
        (updated_ledger["status"] == "ACTIVE")
    )

    seller_index = updated_ledger[
        seller_mask
    ].index[0]

    updated_ledger.loc[
        seller_index,
        "owned_area_decimal"
    ] -= transfer_area

    # Seller owns nothing after full transfer
    if (
        updated_ledger.loc[
            seller_index,
            "owned_area_decimal"
        ] == 0
    ):
        updated_ledger.loc[
            seller_index,
            "status"
        ] = "INACTIVE"

    # Check whether buyer already owns part of parcel
    buyer_mask = (
        (updated_ledger["parcel_id"] == parcel_id) &
        (updated_ledger["owner_id"] == buyer_id) &
        (updated_ledger["status"] == "ACTIVE")
    )

    if buyer_mask.any():

        buyer_index = updated_ledger[
            buyer_mask
        ].index[0]

        updated_ledger.loc[
            buyer_index,
            "owned_area_decimal"
        ] += transfer_area

    else:

        new_row = {
            "ownership_id":
                next_ownership_id(updated_ledger),

            "parcel_id":
                parcel_id,

            "owner_id":
                buyer_id,

            "owned_area_decimal":
                transfer_area,

            "valid_from":
                transaction["execution_date"],

            "status":
                "ACTIVE"
        }

        updated_ledger = pd.concat(
            [
                updated_ledger,
                pd.DataFrame([new_row])
            ],
            ignore_index=True
        )

    # Final safety check
    if not check_ledger_integrity(
        updated_ledger,
        parcels_df
    ):
        return ledger_df.copy(), {
            "valid": False,
            "reason": "LEDGER_INTEGRITY_FAILURE"
        }

    return updated_ledger, {
        "valid": True,
        "reason": "VALID_TRANSFER",
        "seller_available_before":
            seller_available,
        "transferred_area":
            transfer_area
    }

In [944]:
ledger_test_df = ownership_df.copy()

test_transaction = {
    "deed_id": "DEED001",
    "deed_type": "SAF_KABALA",
    "execution_date": "2026-01-10",

    "seller_id": "P001",
    "buyer_id": "P002",

    "parcel_id": "PAR001",
    "transferred_area_decimal": 5.0
}

In [945]:
ledger_after_test, transfer_result = process_transfer(
    ledger_test_df,
    test_transaction,
    people_df,
    parcels_df
)

print(transfer_result)

{'valid': True, 'reason': 'VALID_TRANSFER', 'seller_available_before': 20.0, 'transferred_area': 5.0}

In [946]:
result_view = ledger_after_test[
    (ledger_after_test["parcel_id"] == "PAR001") &
    (ledger_after_test["status"] == "ACTIVE")
][
    [
        "owner_id",
        "owned_area_decimal"
    ]
]

result_view

  owner_id  owned_area_decimal
0     P001                15.0
5     P002                 5.0

In [947]:
print(
    "Original P001 ownership:",
    get_owner_area(
        ownership_df,
        "PAR001",
        "P001"
    )
)

print(
    "Updated P001 ownership:",
    get_owner_area(
        ledger_after_test,
        "PAR001",
        "P001"
    )
)

Original P001 ownership: 20.0
Updated P001 ownership: 15.0

In [948]:
print(
    "P002 ownership after transfer:",
    get_owner_area(
        ledger_after_test,
        "PAR001",
        "P002"
    )
)

P002 ownership after transfer: 5.0

In [949]:
active_par001 = ledger_after_test[
    (ledger_after_test["parcel_id"] == "PAR001") &
    (ledger_after_test["status"] == "ACTIVE")
]

total_owned = active_par001[
    "owned_area_decimal"
].sum()

print("PAR001 total ownership:", total_owned)

print(
    "Ledger integrity:",
    check_ledger_integrity(
        ledger_after_test,
        parcels_df
    )
)

PAR001 total ownership: 20.0
Ledger integrity: True

In [950]:
seller_after = get_owner_area(
    ledger_after_test,
    "PAR001",
    "P001"
)

buyer_after = get_owner_area(
    ledger_after_test,
    "PAR001",
    "P002"
)

print("STEP 8 SUMMARY")
print("--------------")

print(
    "Transfer accepted:",
    transfer_result["valid"]
)

print(
    "Decision:",
    transfer_result["reason"]
)

print(
    "Seller before:",
    transfer_result["seller_available_before"]
)

print(
    "Transferred:",
    transfer_result["transferred_area"]
)

print(
    "Seller after:",
    seller_after
)

print(
    "Buyer after:",
    buyer_after
)

print(
    "Total parcel ownership:",
    seller_after + buyer_after
)

print(
    "Ledger integrity:",
    check_ledger_integrity(
        ledger_after_test,
        parcels_df
    )
)

print("\nOwnership Ledger Engine: READY")

STEP 8 SUMMARY
--------------
Transfer accepted: True
Decision: VALID_TRANSFER
Seller before: 20.0
Transferred: 5.0
Seller after: 15.0
Buyer after: 5.0
Total parcel ownership: 20.0
Ledger integrity: True

Ownership Ledger Engine: READY

# STEP 9 — Seller Not Owner Detection

Test whether BhumiGuard rejects a transaction when the seller
has no active ownership in the specified parcel.

Expected result:

- Transaction rejected
- Reason: SELLER_NOT_OWNER
- Ownership ledger remains unchanged

In [951]:
seller_not_owner_transaction = {
    "deed_id": "DEED002",
    "deed_type": "SAF_KABALA",
    "execution_date": "2026-01-15",

    "seller_id": "P003",
    "buyer_id": "P004",

    "parcel_id": "PAR001",
    "transferred_area_decimal": 5.0
}

seller_not_owner_transaction

{'deed_id': 'DEED002',
 'deed_type': 'SAF_KABALA',
 'execution_date': '2026-01-15',
 'seller_id': 'P003',
 'buyer_id': 'P004',
 'parcel_id': 'PAR001',
 'transferred_area_decimal': 5.0}

In [952]:
p003_area_before = get_owner_area(
    ownership_df,
    "PAR001",
    "P003"
)

print(
    "P003 current ownership in PAR001:",
    p003_area_before
)

P003 current ownership in PAR001: 0.0

In [953]:
ledger_before_invalid_test = ownership_df.copy()

print("Original ledger snapshot saved.")

Original ledger snapshot saved.

In [954]:
ledger_after_invalid_test, invalid_result = process_transfer(
    ledger_before_invalid_test,
    seller_not_owner_transaction,
    people_df,
    parcels_df
)

print(invalid_result)

{'valid': False, 'reason': 'SELLER_NOT_OWNER', 'seller_available': 0.0}

In [955]:
print(
    "Transaction accepted:",
    invalid_result["valid"]
)

print(
    "Decision:",
    invalid_result["reason"]
)

Transaction accepted: False
Decision: SELLER_NOT_OWNER

In [956]:
ledger_unchanged = ledger_before_invalid_test.equals(
    ledger_after_invalid_test
)

print(
    "Ledger unchanged:",
    ledger_unchanged
)

Ledger unchanged: True

In [957]:
p001_area_after = get_owner_area(
    ledger_after_invalid_test,
    "PAR001",
    "P001"
)

p003_area_after = get_owner_area(
    ledger_after_invalid_test,
    "PAR001",
    "P003"
)

print(
    "P001 ownership after rejected transaction:",
    p001_area_after
)

print(
    "P003 ownership after rejected transaction:",
    p003_area_after
)

P001 ownership after rejected transaction: 20.0
P003 ownership after rejected transaction: 0.0

In [958]:
print(
    "Ledger integrity:",
    check_ledger_integrity(
        ledger_after_invalid_test,
        parcels_df
    )
)

Ledger integrity: True

In [959]:
if invalid_result["reason"] == "SELLER_NOT_OWNER":

    explanation = (
        f"Seller {seller_not_owner_transaction['seller_id']} "
        f"has no active ownership in parcel "
        f"{seller_not_owner_transaction['parcel_id']}. "
        "The transaction requires manual review and was not applied."
    )

else:
    explanation = "No seller-ownership conflict detected."

print(explanation)

Seller P003 has no active ownership in parcel PAR001. The transaction requires manual review and was not applied.

In [960]:
print("STEP 9 SUMMARY")
print("--------------")

print(
    "Deed ID:",
    seller_not_owner_transaction["deed_id"]
)

print(
    "Seller:",
    seller_not_owner_transaction["seller_id"]
)

print(
    "Parcel:",
    seller_not_owner_transaction["parcel_id"]
)

print(
    "Seller available area:",
    p003_area_before
)

print(
    "Transaction accepted:",
    invalid_result["valid"]
)

print(
    "Decision:",
    invalid_result["reason"]
)

print(
    "Ledger unchanged:",
    ledger_unchanged
)

print(
    "Ledger integrity:",
    check_ledger_integrity(
        ledger_after_invalid_test,
        parcels_df
    )
)

print("\nSeller Ownership Rule: PASS")

STEP 9 SUMMARY
--------------
Deed ID: DEED002
Seller: P003
Parcel: PAR001
Seller available area: 0.0
Transaction accepted: False
Decision: SELLER_NOT_OWNER
Ledger unchanged: True
Ledger integrity: True

Seller Ownership Rule: PASS

# STEP 10 — Over-Transfer Detection

Test whether BhumiGuard rejects a transaction when the seller
tries to transfer more land than currently owned.

Current state after the valid transaction:

- P001 owns 15 decimal of PAR001
- P002 owns 5 decimal of PAR001

Test:

- Seller: P001
- Buyer: P003
- Requested transfer: 18 decimal

Expected result:

- Transaction rejected
- Reason: INSUFFICIENT_OWNERSHIP
- Ledger unchanged

In [961]:
print(
    "P001 current ownership:",
    get_owner_area(
        ledger_after_test,
        "PAR001",
        "P001"
    )
)

print(
    "P002 current ownership:",
    get_owner_area(
        ledger_after_test,
        "PAR001",
        "P002"
    )
)

P001 current ownership: 15.0
P002 current ownership: 5.0

In [962]:
over_transfer_transaction = {
    "deed_id": "DEED003",
    "deed_type": "SAF_KABALA",
    "execution_date": "2026-01-20",

    "seller_id": "P001",
    "buyer_id": "P003",

    "parcel_id": "PAR001",
    "transferred_area_decimal": 18.0
}

over_transfer_transaction

{'deed_id': 'DEED003',
 'deed_type': 'SAF_KABALA',
 'execution_date': '2026-01-20',
 'seller_id': 'P001',
 'buyer_id': 'P003',
 'parcel_id': 'PAR001',
 'transferred_area_decimal': 18.0}

In [963]:
seller_available_before_over_transfer = get_owner_area(
    ledger_after_test,
    "PAR001",
    "P001"
)

requested_area = over_transfer_transaction[
    "transferred_area_decimal"
]

print(
    "Seller available area:",
    seller_available_before_over_transfer
)

print(
    "Requested transfer:",
    requested_area
)

Seller available area: 15.0
Requested transfer: 18.0

In [964]:
ledger_before_over_transfer = ledger_after_test.copy()

print("Ledger snapshot saved.")

Ledger snapshot saved.

In [965]:
ledger_after_over_transfer, over_transfer_result = process_transfer(
    ledger_before_over_transfer,
    over_transfer_transaction,
    people_df,
    parcels_df
)

print(over_transfer_result)

{'valid': False, 'reason': 'INSUFFICIENT_OWNERSHIP', 'seller_available': 15.0, 'requested_area': 18.0}

In [966]:
print(
    "Transaction accepted:",
    over_transfer_result["valid"]
)

print(
    "Decision:",
    over_transfer_result["reason"]
)

print(
    "Seller available:",
    over_transfer_result["seller_available"]
)

print(
    "Requested area:",
    over_transfer_result["requested_area"]
)

Transaction accepted: False
Decision: INSUFFICIENT_OWNERSHIP
Seller available: 15.0
Requested area: 18.0

In [967]:
over_transfer_ledger_unchanged = (
    ledger_before_over_transfer.equals(
        ledger_after_over_transfer
    )
)

print(
    "Ledger unchanged:",
    over_transfer_ledger_unchanged
)

Ledger unchanged: True

In [968]:
p001_after_rejection = get_owner_area(
    ledger_after_over_transfer,
    "PAR001",
    "P001"
)

p002_after_rejection = get_owner_area(
    ledger_after_over_transfer,
    "PAR001",
    "P002"
)

p003_after_rejection = get_owner_area(
    ledger_after_over_transfer,
    "PAR001",
    "P003"
)

print("P001:", p001_after_rejection)
print("P002:", p002_after_rejection)
print("P003:", p003_after_rejection)

P001: 15.0
P002: 5.0
P003: 0.0

In [969]:
if over_transfer_result["reason"] == "INSUFFICIENT_OWNERSHIP":

    explanation = (
        f"Seller {over_transfer_transaction['seller_id']} "
        f"currently owns {over_transfer_result['seller_available']} decimal "
        f"of parcel {over_transfer_transaction['parcel_id']}, "
        f"but the requested transfer is "
        f"{over_transfer_result['requested_area']} decimal. "
        "The transaction was rejected for manual review."
    )

else:
    explanation = "No over-transfer conflict detected."

print(explanation)

Seller P001 currently owns 15.0 decimal of parcel PAR001, but the requested transfer is 18.0 decimal. The transaction was rejected for manual review.

In [970]:
print("STEP 10 SUMMARY")
print("----------------")

print(
    "Deed ID:",
    over_transfer_transaction["deed_id"]
)

print(
    "Seller:",
    over_transfer_transaction["seller_id"]
)

print(
    "Parcel:",
    over_transfer_transaction["parcel_id"]
)

print(
    "Available area:",
    seller_available_before_over_transfer
)

print(
    "Requested area:",
    requested_area
)

print(
    "Transaction accepted:",
    over_transfer_result["valid"]
)

print(
    "Decision:",
    over_transfer_result["reason"]
)

print(
    "Ledger unchanged:",
    over_transfer_ledger_unchanged
)

print(
    "Ledger integrity:",
    check_ledger_integrity(
        ledger_after_over_transfer,
        parcels_df
    )
)

print("\nOver-Transfer Rule: PASS")

STEP 10 SUMMARY
----------------
Deed ID: DEED003
Seller: P001
Parcel: PAR001
Available area: 15.0
Requested area: 18.0
Transaction accepted: False
Decision: INSUFFICIENT_OWNERSHIP
Ledger unchanged: True
Ledger integrity: True

Over-Transfer Rule: PASS


# STEP 11 — Double-Selling Detection

Detect whether the same identifiable land portion has already been
transferred in an earlier valid transaction.

For the synthetic MVP, each transferable portion may have an internal
`portion_id`.

Scenario:

- PAR001 total area = 20 decimal
- DEED001 already sold portion PAR001-PART-A (5 decimal) to P002
- P001 still owns another 15 decimal
- P001 attempts to sell PAR001-PART-A again to P003

The area check alone would not catch this because P001 still owns 15 decimal.

Expected result:

- DOUBLE_SALE detected
- transaction rejected
- ownership ledger unchanged
- transaction history unchanged

In [971]:
accepted_transactions_df = transactions_df.copy()

accepted_transactions_df["portion_id"] = [
    "PAR001-PART-A"
]

accepted_transactions_df[
    [
        "deed_id",
        "seller_id",
        "buyer_id",
        "parcel_id",
        "transferred_area_decimal",
        "portion_id",
        "transaction_status"
    ]
]

,deed_id,seller_id,buyer_id,parcel_id,transferred_area_decimal,portion_id,transaction_status
0,DEED001,P001,P002,PAR001,5.0,PAR001-PART-A,VALID

In [972]:
def check_double_sale(history_df, transaction):

    portion_id = transaction.get("portion_id")

    if portion_id is None:
        return {
            "double_sale": False,
            "reason": "NO_PORTION_ID"
        }

    previous_sales = history_df[
        (history_df["parcel_id"] == transaction["parcel_id"]) &
        (history_df["portion_id"] == portion_id) &
        (history_df["transaction_status"] == "VALID")
    ]

    if previous_sales.empty:
        return {
            "double_sale": False,
            "reason": "NO_PREVIOUS_SALE"
        }

    previous_deeds = previous_sales[
        "deed_id"
    ].tolist()

    previous_buyers = previous_sales[
        "buyer_id"
    ].tolist()

    return {
        "double_sale": True,
        "reason": "DOUBLE_SALE",
        "previous_deeds": previous_deeds,
        "previous_buyers": previous_buyers
    }

In [973]:
test_double_sale_check = {
    "deed_id": "DEED004",
    "seller_id": "P001",
    "buyer_id": "P003",
    "parcel_id": "PAR001",
    "portion_id": "PAR001-PART-A",
    "transferred_area_decimal": 5.0
}

double_sale_check = check_double_sale(
    accepted_transactions_df,
    test_double_sale_check
)

print(double_sale_check)

{'double_sale': True, 'reason': 'DOUBLE_SALE', 'previous_deeds': ['DEED001'], 'previous_buyers': ['P002']}

In [974]:
double_sale_transaction = {
    "deed_id": "DEED004",
    "deed_type": "SAF_KABALA",
    "execution_date": "2026-01-25",

    "seller_id": "P001",
    "buyer_id": "P003",

    "parcel_id": "PAR001",
    "portion_id": "PAR001-PART-A",

    "transferred_area_decimal": 5.0,

    "transaction_status": "PENDING"
}

double_sale_transaction

{'deed_id': 'DEED004',
 'deed_type': 'SAF_KABALA',
 'execution_date': '2026-01-25',
 'seller_id': 'P001',
 'buyer_id': 'P003',
 'parcel_id': 'PAR001',
 'portion_id': 'PAR001-PART-A',
 'transferred_area_decimal': 5.0,
 'transaction_status': 'PENDING'}

In [975]:
seller_available_double_sale = get_owner_area(
    ledger_after_test,
    "PAR001",
    "P001"
)

requested_double_sale_area = (
    double_sale_transaction[
        "transferred_area_decimal"
    ]
)

print(
    "Seller available:",
    seller_available_double_sale
)

print(
    "Requested:",
    requested_double_sale_area
)

print(
    "Area check alone passes:",
    requested_double_sale_area
    <= seller_available_double_sale
)

Seller available: 15.0
Requested: 5.0
Area check alone passes: True

In [976]:
def process_transfer_with_history(
    ledger_df,
    history_df,
    transaction,
    people_df,
    parcels_df
):

    # 1. Check historical portion conflict first
    double_sale_result = check_double_sale(
        history_df,
        transaction
    )

    if double_sale_result["double_sale"]:

        return (
            ledger_df.copy(),
            history_df.copy(),
            {
                "valid": False,
                "reason": "DOUBLE_SALE",
                "previous_deeds":
                    double_sale_result["previous_deeds"],
                "previous_buyers":
                    double_sale_result["previous_buyers"]
            }
        )

    # 2. Run normal ownership validation
    updated_ledger, transfer_result = process_transfer(
        ledger_df,
        transaction,
        people_df,
        parcels_df
    )

    if not transfer_result["valid"]:

        return (
            ledger_df.copy(),
            history_df.copy(),
            transfer_result
        )

    # 3. Add accepted transaction to history
    accepted_transaction = transaction.copy()

    accepted_transaction[
        "transaction_status"
    ] = "VALID"

    updated_history = pd.concat(
        [
            history_df,
            pd.DataFrame(
                [accepted_transaction]
            )
        ],
        ignore_index=True
    )

    return (
        updated_ledger,
        updated_history,
        {
            "valid": True,
            "reason": "VALID_TRANSFER"
        }
    )

In [977]:
ledger_before_double_sale = (
    ledger_after_test.copy()
)

history_before_double_sale = (
    accepted_transactions_df.copy()
)

In [978]:
(
    ledger_after_double_sale,
    history_after_double_sale,
    double_sale_result
) = process_transfer_with_history(
    ledger_before_double_sale,
    history_before_double_sale,
    double_sale_transaction,
    people_df,
    parcels_df
)

print(double_sale_result)

{'valid': False, 'reason': 'DOUBLE_SALE', 'previous_deeds': ['DEED001'], 'previous_buyers': ['P002']}

In [979]:
double_sale_ledger_unchanged = (
    ledger_before_double_sale.equals(
        ledger_after_double_sale
    )
)

print(
    "Ledger unchanged:",
    double_sale_ledger_unchanged
)

Ledger unchanged: True

In [980]:
double_sale_history_unchanged = (
    history_before_double_sale.equals(
        history_after_double_sale
    )
)

print(
    "History unchanged:",
    double_sale_history_unchanged
)

print(
    "History records:",
    len(history_after_double_sale)
)

History unchanged: True
History records: 1

In [981]:
conflicting_sale = accepted_transactions_df[
    accepted_transactions_df["portion_id"]
    == double_sale_transaction["portion_id"]
][
    [
        "deed_id",
        "buyer_id",
        "parcel_id",
        "portion_id",
        "transferred_area_decimal"
    ]
]

conflicting_sale

   deed_id buyer_id parcel_id     portion_id  transferred_area_decimal
0  DEED001     P002    PAR001  PAR001-PART-A                       5.0

In [982]:
if double_sale_result["reason"] == "DOUBLE_SALE":

    previous_deed = (
        double_sale_result[
            "previous_deeds"
        ][0]
    )

    previous_buyer = (
        double_sale_result[
            "previous_buyers"
        ][0]
    )

    explanation = (
        f"Portion "
        f"{double_sale_transaction['portion_id']} "
        f"of parcel "
        f"{double_sale_transaction['parcel_id']} "
        f"was already transferred under "
        f"{previous_deed} to {previous_buyer}. "
        "The new transaction was rejected "
        "as a potential double sale."
    )

else:
    explanation = (
        "No prior sale conflict detected."
    )

print(explanation)

Portion PAR001-PART-A of parcel PAR001 was already transferred under DEED001 to P002. The new transaction was rejected as a potential double sale.

In [983]:
print("STEP 11 SUMMARY")
print("----------------")

print(
    "Deed ID:",
    double_sale_transaction["deed_id"]
)

print(
    "Parcel:",
    double_sale_transaction["parcel_id"]
)

print(
    "Portion:",
    double_sale_transaction["portion_id"]
)

print(
    "Seller available area:",
    seller_available_double_sale
)

print(
    "Requested area:",
    requested_double_sale_area
)

print(
    "Area check alone passes:",
    requested_double_sale_area
    <= seller_available_double_sale
)

print(
    "Transaction accepted:",
    double_sale_result["valid"]
)

print(
    "Decision:",
    double_sale_result["reason"]
)

print(
    "Previous deed:",
    double_sale_result["previous_deeds"][0]
)

print(
    "Previous buyer:",
    double_sale_result["previous_buyers"][0]
)

print(
    "Ledger unchanged:",
    double_sale_ledger_unchanged
)

print(
    "History unchanged:",
    double_sale_history_unchanged
)

print("\nDouble-Sale Rule: PASS")

STEP 11 SUMMARY
----------------
Deed ID: DEED004
Parcel: PAR001
Portion: PAR001-PART-A
Seller available area: 15.0
Requested area: 5.0
Area check alone passes: True
Transaction accepted: False
Decision: DOUBLE_SALE
Previous deed: DEED001
Previous buyer: P002
Ledger unchanged: True
History unchanged: True

Double-Sale Rule: PASS

# STEP 12 — Duplicate Deed Number Detection

Detect whether a deed identifier has already been used in the accepted
transaction history.

Expected behavior:

- Duplicate deed ID is rejected before ownership is modified
- Ledger remains unchanged
- Transaction history remains unchanged

In [984]:
def check_duplicate_deed(history_df, deed_id):

    matches = history_df[
        history_df["deed_id"] == deed_id
    ]

    if matches.empty:
        return {
            "duplicate": False,
            "reason": "DEED_ID_AVAILABLE"
        }

    return {
        "duplicate": True,
        "reason": "DUPLICATE_DEED",
        "existing_records": len(matches)
    }

In [985]:
duplicate_test = check_duplicate_deed(
    accepted_transactions_df,
    "DEED001"
)

print(duplicate_test)

{'duplicate': True, 'reason': 'DUPLICATE_DEED', 'existing_records': 1}

In [986]:
new_deed_test = check_duplicate_deed(
    accepted_transactions_df,
    "DEED005"
)

print(new_deed_test)

{'duplicate': False, 'reason': 'DEED_ID_AVAILABLE'}

In [987]:
duplicate_deed_transaction = {
    "deed_id": "DEED001",
    "deed_type": "SAF_KABALA",
    "execution_date": "2026-01-30",

    "seller_id": "P001",
    "buyer_id": "P003",

    "parcel_id": "PAR001",
    "portion_id": "PAR001-PART-B",

    "transferred_area_decimal": 2.0,

    "transaction_status": "PENDING"
}

duplicate_deed_transaction

{'deed_id': 'DEED001',
 'deed_type': 'SAF_KABALA',
 'execution_date': '2026-01-30',
 'seller_id': 'P001',
 'buyer_id': 'P003',
 'parcel_id': 'PAR001',
 'portion_id': 'PAR001-PART-B',
 'transferred_area_decimal': 2.0,
 'transaction_status': 'PENDING'}

In [988]:
duplicate_seller_available = get_owner_area(
    ledger_after_test,
    "PAR001",
    "P001"
)

duplicate_requested_area = (
    duplicate_deed_transaction[
        "transferred_area_decimal"
    ]
)

print(
    "Seller available:",
    duplicate_seller_available
)

print(
    "Requested:",
    duplicate_requested_area
)

print(
    "Ownership check alone passes:",
    duplicate_requested_area
    <= duplicate_seller_available
)

Seller available: 15.0
Requested: 2.0
Ownership check alone passes: True

In [989]:
def process_transfer_with_checks(
    ledger_df,
    history_df,
    transaction,
    people_df,
    parcels_df
):

    # 1. Duplicate deed check
    duplicate_result = check_duplicate_deed(
        history_df,
        transaction["deed_id"]
    )

    if duplicate_result["duplicate"]:

        return (
            ledger_df.copy(),
            history_df.copy(),
            {
                "valid": False,
                "reason": "DUPLICATE_DEED",
                "existing_records":
                    duplicate_result[
                        "existing_records"
                    ]
            }
        )

    # 2. Double-sale check
    double_sale_result = check_double_sale(
        history_df,
        transaction
    )

    if double_sale_result["double_sale"]:

        return (
            ledger_df.copy(),
            history_df.copy(),
            {
                "valid": False,
                "reason": "DOUBLE_SALE",
                "previous_deeds":
                    double_sale_result[
                        "previous_deeds"
                    ],
                "previous_buyers":
                    double_sale_result[
                        "previous_buyers"
                    ]
            }
        )

    # 3. Normal ownership validation
    updated_ledger, transfer_result = process_transfer(
        ledger_df,
        transaction,
        people_df,
        parcels_df
    )

    if not transfer_result["valid"]:

        return (
            ledger_df.copy(),
            history_df.copy(),
            transfer_result
        )

    # 4. Save valid transaction
    accepted_transaction = transaction.copy()

    accepted_transaction[
        "transaction_status"
    ] = "VALID"

    updated_history = pd.concat(
        [
            history_df,
            pd.DataFrame(
                [accepted_transaction]
            )
        ],
        ignore_index=True
    )

    return (
        updated_ledger,
        updated_history,
        {
            "valid": True,
            "reason": "VALID_TRANSFER"
        }
    )

In [990]:
ledger_before_duplicate = (
    ledger_after_test.copy()
)

history_before_duplicate = (
    accepted_transactions_df.copy()
)

In [991]:
(
    ledger_after_duplicate,
    history_after_duplicate,
    duplicate_result
) = process_transfer_with_checks(
    ledger_before_duplicate,
    history_before_duplicate,
    duplicate_deed_transaction,
    people_df,
    parcels_df
)

print(duplicate_result)

{'valid': False, 'reason': 'DUPLICATE_DEED', 'existing_records': 1}

In [992]:
duplicate_ledger_unchanged = (
    ledger_before_duplicate.equals(
        ledger_after_duplicate
    )
)

print(
    "Ledger unchanged:",
    duplicate_ledger_unchanged
)

Ledger unchanged: True

In [993]:
duplicate_history_unchanged = (
    history_before_duplicate.equals(
        history_after_duplicate
    )
)

print(
    "History unchanged:",
    duplicate_history_unchanged
)

print(
    "History records:",
    len(history_after_duplicate)
)

History unchanged: True
History records: 1

In [994]:
existing_deed = accepted_transactions_df[
    accepted_transactions_df["deed_id"]
    == duplicate_deed_transaction["deed_id"]
][
    [
        "deed_id",
        "seller_id",
        "buyer_id",
        "parcel_id",
        "transferred_area_decimal"
    ]
]

existing_deed

   deed_id seller_id buyer_id parcel_id  transferred_area_decimal
0  DEED001      P001     P002    PAR001                       5.0

In [995]:
if duplicate_result["reason"] == "DUPLICATE_DEED":

    explanation = (
        f"Deed ID "
        f"{duplicate_deed_transaction['deed_id']} "
        "already exists in the accepted transaction history. "
        "The new transaction was rejected before any ownership "
        "change was applied."
    )

else:
    explanation = "No duplicate deed conflict detected."

print(explanation)

Deed ID DEED001 already exists in the accepted transaction history. The new transaction was rejected before any ownership change was applied.

In [996]:
print("STEP 12 SUMMARY")
print("----------------")

print(
    "Submitted deed ID:",
    duplicate_deed_transaction["deed_id"]
)

print(
    "Seller:",
    duplicate_deed_transaction["seller_id"]
)

print(
    "Parcel:",
    duplicate_deed_transaction["parcel_id"]
)

print(
    "Requested area:",
    duplicate_requested_area
)

print(
    "Ownership check alone passes:",
    duplicate_requested_area
    <= duplicate_seller_available
)

print(
    "Transaction accepted:",
    duplicate_result["valid"]
)

print(
    "Decision:",
    duplicate_result["reason"]
)

print(
    "Existing records:",
    duplicate_result["existing_records"]
)

print(
    "Ledger unchanged:",
    duplicate_ledger_unchanged
)

print(
    "History unchanged:",
    duplicate_history_unchanged
)

print("\nDuplicate Deed Rule: PASS")

STEP 12 SUMMARY
----------------
Submitted deed ID: DEED001
Seller: P001
Parcel: PAR001
Requested area: 2.0
Ownership check alone passes: True
Transaction accepted: False
Decision: DUPLICATE_DEED
Existing records: 1
Ledger unchanged: True
History unchanged: True

Duplicate Deed Rule: PASS

# STEP 13 — Deed vs Mutation Record Mismatch

Create a separate synthetic mutation registry and compare a proposed
deed transaction against the mutation-side ownership record.

Important:
A mismatch is treated as a verification alert, not as proof of fraud
or final legal ownership.

In [997]:
mutation_data = [
    {
        "mutation_id": "MUT001",
        "parcel_id": "PAR001",
        "portion_id": "PAR001-PART-B",
        "mutation_owner_id": "P004",
        "mutation_area_decimal": 5.0,
        "effective_date": "2026-01-12",
        "status": "ACTIVE"
    },
    {
        "mutation_id": "MUT002",
        "parcel_id": "PAR001",
        "portion_id": "PAR001-PART-C",
        "mutation_owner_id": "P001",
        "mutation_area_decimal": 5.0,
        "effective_date": "2026-01-12",
        "status": "ACTIVE"
    }
]

mutation_df = pd.DataFrame(mutation_data)

mutation_df

,mutation_id,parcel_id,portion_id,mutation_owner_id,mutation_area_decimal,effective_date,status
0,MUT001,PAR001,PAR001-PART-B,P004,5.0,2026-01-12,ACTIVE
1,MUT002,PAR001,PAR001-PART-C,P001,5.0,2026-01-12,ACTIVE

In [998]:
print("Mutation records:", len(mutation_df))
print(
    "Unique mutation IDs:",
    mutation_df["mutation_id"].nunique()
)

print(
    "Duplicate mutation IDs:",
    mutation_df["mutation_id"].duplicated().sum()
)

print(
    "Invalid owner references:",
    (~mutation_df["mutation_owner_id"].isin(
        people_df["person_id"]
    )).sum()
)

print(
    "Invalid parcel references:",
    (~mutation_df["parcel_id"].isin(
        parcels_df["parcel_id"]
    )).sum()
)

Mutation records: 2
Unique mutation IDs: 2
Duplicate mutation IDs: 0
Invalid owner references: 0
Invalid parcel references: 0

In [999]:
def check_deed_mutation_match(
    mutation_df,
    transaction
):

    records = mutation_df[
        (mutation_df["parcel_id"] ==
         transaction["parcel_id"]) &
        (mutation_df["portion_id"] ==
         transaction["portion_id"]) &
        (mutation_df["status"] == "ACTIVE")
    ]

    if records.empty:
        return {
            "match": None,
            "reason": "NO_MUTATION_RECORD"
        }

    mutation_owners = set(
        records["mutation_owner_id"]
    )

    deed_seller = transaction["seller_id"]

    if deed_seller in mutation_owners:
        return {
            "match": True,
            "reason": "MUTATION_MATCH",
            "mutation_owners":
                sorted(mutation_owners)
        }

    return {
        "match": False,
        "reason": "DEED_MUTATION_MISMATCH",
        "deed_seller": deed_seller,
        "mutation_owners":
            sorted(mutation_owners)
    }

In [1000]:
matching_transaction = {
    "deed_id": "TEST-MATCH",
    "seller_id": "P001",
    "buyer_id": "P003",
    "parcel_id": "PAR001",
    "portion_id": "PAR001-PART-C",
    "transferred_area_decimal": 2.0
}

matching_result = check_deed_mutation_match(
    mutation_df,
    matching_transaction
)

print(matching_result)

{'match': True, 'reason': 'MUTATION_MATCH', 'mutation_owners': ['P001']}

In [1001]:
mutation_mismatch_transaction = {
    "deed_id": "DEED005",
    "deed_type": "SAF_KABALA",
    "execution_date": "2026-02-01",

    "seller_id": "P001",
    "buyer_id": "P003",

    "parcel_id": "PAR001",
    "portion_id": "PAR001-PART-B",

    "transferred_area_decimal": 2.0,

    "transaction_status": "PENDING"
}

mutation_mismatch_transaction

{'deed_id': 'DEED005',
 'deed_type': 'SAF_KABALA',
 'execution_date': '2026-02-01',
 'seller_id': 'P001',
 'buyer_id': 'P003',
 'parcel_id': 'PAR001',
 'portion_id': 'PAR001-PART-B',
 'transferred_area_decimal': 2.0,
 'transaction_status': 'PENDING'}

In [1002]:
mismatch_seller_available = get_owner_area(
    ledger_after_test,
    "PAR001",
    "P001"
)

duplicate_check = check_duplicate_deed(
    accepted_transactions_df,
    mutation_mismatch_transaction["deed_id"]
)

double_sale_check = check_double_sale(
    accepted_transactions_df,
    mutation_mismatch_transaction
)

print(
    "Seller available:",
    mismatch_seller_available
)

print(
    "Requested:",
    mutation_mismatch_transaction[
        "transferred_area_decimal"
    ]
)

print(
    "Ownership check passes:",
    mutation_mismatch_transaction[
        "transferred_area_decimal"
    ] <= mismatch_seller_available
)

print(
    "Duplicate deed:",
    duplicate_check["duplicate"]
)

print(
    "Double sale:",
    double_sale_check["double_sale"]
)

Seller available: 15.0
Requested: 2.0
Ownership check passes: True
Duplicate deed: False
Double sale: False

In [1003]:
mutation_check = check_deed_mutation_match(
    mutation_df,
    mutation_mismatch_transaction
)

print(mutation_check)

{'match': False, 'reason': 'DEED_MUTATION_MISMATCH', 'deed_seller': 'P001', 'mutation_owners': ['P004']}

In [1004]:
def process_transfer_full_checks(
    ledger_df,
    history_df,
    mutation_df,
    transaction,
    people_df,
    parcels_df
):

    # 1. Duplicate deed
    duplicate_result = check_duplicate_deed(
        history_df,
        transaction["deed_id"]
    )

    if duplicate_result["duplicate"]:
        return (
            ledger_df.copy(),
            history_df.copy(),
            {
                "valid": False,
                "reason": "DUPLICATE_DEED"
            }
        )

    # 2. Double-sale
    double_sale_result = check_double_sale(
        history_df,
        transaction
    )

    if double_sale_result["double_sale"]:
        return (
            ledger_df.copy(),
            history_df.copy(),
            {
                "valid": False,
                "reason": "DOUBLE_SALE",
                "previous_deeds":
                    double_sale_result[
                        "previous_deeds"
                    ]
            }
        )

    # 3. Mutation consistency
    mutation_result = check_deed_mutation_match(
        mutation_df,
        transaction
    )

    if mutation_result["match"] is False:
        return (
            ledger_df.copy(),
            history_df.copy(),
            {
                "valid": False,
                "reason":
                    "DEED_MUTATION_MISMATCH",

                "deed_seller":
                    mutation_result[
                        "deed_seller"
                    ],

                "mutation_owners":
                    mutation_result[
                        "mutation_owners"
                    ]
            }
        )

    # 4. Ownership validation
    updated_ledger, transfer_result = (
        process_transfer(
            ledger_df,
            transaction,
            people_df,
            parcels_df
        )
    )

    if not transfer_result["valid"]:
        return (
            ledger_df.copy(),
            history_df.copy(),
            transfer_result
        )

    # 5. Store valid transaction
    accepted_transaction = transaction.copy()

    accepted_transaction[
        "transaction_status"
    ] = "VALID"

    updated_history = pd.concat(
        [
            history_df,
            pd.DataFrame(
                [accepted_transaction]
            )
        ],
        ignore_index=True
    )

    return (
        updated_ledger,
        updated_history,
        {
            "valid": True,
            "reason": "VALID_TRANSFER"
        }
    )

In [1005]:
ledger_before_mutation_test = (
    ledger_after_test.copy()
)

history_before_mutation_test = (
    accepted_transactions_df.copy()
)

In [1006]:
(
    ledger_after_mutation_test,
    history_after_mutation_test,
    mutation_result
) = process_transfer_full_checks(
    ledger_before_mutation_test,
    history_before_mutation_test,
    mutation_df,
    mutation_mismatch_transaction,
    people_df,
    parcels_df
)

print(mutation_result)

{'valid': False, 'reason': 'DEED_MUTATION_MISMATCH', 'deed_seller': 'P001', 'mutation_owners': ['P004']}

In [1007]:
mutation_ledger_unchanged = (
    ledger_before_mutation_test.equals(
        ledger_after_mutation_test
    )
)

print(
    "Ledger unchanged:",
    mutation_ledger_unchanged
)

Ledger unchanged: True

In [1008]:
mutation_history_unchanged = (
    history_before_mutation_test.equals(
        history_after_mutation_test
    )
)

print(
    "History unchanged:",
    mutation_history_unchanged
)

History unchanged: True

In [1009]:
if mutation_result["reason"] == \
        "DEED_MUTATION_MISMATCH":

    explanation = (
        f"The proposed deed identifies "
        f"{mutation_result['deed_seller']} "
        f"as the seller of "
        f"{mutation_mismatch_transaction['portion_id']}, "
        f"while the synthetic mutation record lists "
        f"{', '.join(mutation_result['mutation_owners'])} "
        "for that portion. "
        "The records are inconsistent and require "
        "manual verification."
    )

else:
    explanation = (
        "No deed-mutation mismatch detected."
    )

print(explanation)

The proposed deed identifies P001 as the seller of PAR001-PART-B, while the synthetic mutation record lists P004 for that portion. The records are inconsistent and require manual verification.

In [1010]:
print("STEP 13 SUMMARY")
print("----------------")

print(
    "Deed ID:",
    mutation_mismatch_transaction[
        "deed_id"
    ]
)

print(
    "Seller:",
    mutation_mismatch_transaction[
        "seller_id"
    ]
)

print(
    "Parcel:",
    mutation_mismatch_transaction[
        "parcel_id"
    ]
)

print(
    "Portion:",
    mutation_mismatch_transaction[
        "portion_id"
    ]
)

print(
    "Ownership check passes:",
    mutation_mismatch_transaction[
        "transferred_area_decimal"
    ] <= mismatch_seller_available
)

print(
    "Mutation-side owner:",
    mutation_check[
        "mutation_owners"
    ][0]
)

print(
    "Transaction accepted:",
    mutation_result["valid"]
)

print(
    "Decision:",
    mutation_result["reason"]
)

print(
    "Ledger unchanged:",
    mutation_ledger_unchanged
)

print(
    "History unchanged:",
    mutation_history_unchanged
)

print(
    "Positive match test:",
    matching_result["reason"]
)

print("\nDeed-Mutation Rule: PASS")

STEP 13 SUMMARY
----------------
Deed ID: DEED005
Seller: P001
Parcel: PAR001
Portion: PAR001-PART-B
Ownership check passes: True
Mutation-side owner: P004
Transaction accepted: False
Decision: DEED_MUTATION_MISMATCH
Ledger unchanged: True
History unchanged: True
Positive match test: MUTATION_MATCH

Deed-Mutation Rule: PASS

# STEP 14 — Unified Explainable Risk Engine

Combine all fraud/conflict checks into one explainable verification report.

Risk policy for the MVP:

- LOW: all available checks pass
- MEDIUM: no critical conflict, but some information is unavailable
- HIGH: one or more critical conflicts are detected

Important:
Risk level is a screening result, not a legal declaration of fraud or ownership.

In [1011]:
def evaluate_transaction_rules(
    ledger_df,
    history_df,
    mutation_df,
    transaction,
    people_df,
    parcels_df
):
    rules = {}

    seller_id = transaction["seller_id"]
    buyer_id = transaction["buyer_id"]
    parcel_id = transaction["parcel_id"]
    deed_id = transaction["deed_id"]

    transfer_area = float(
        transaction["transferred_area_decimal"]
    )

    # ---------------------------------
    # Rule 1: Deed ID
    # ---------------------------------
    duplicate_result = check_duplicate_deed(
        history_df,
        deed_id
    )

    if duplicate_result["duplicate"]:
        rules["deed_id_check"] = {
            "status": "FAIL",
            "code": "DUPLICATE_DEED",
            "message": (
                f"Deed ID {deed_id} already exists."
            )
        }
    else:
        rules["deed_id_check"] = {
            "status": "PASS",
            "code": "DEED_ID_AVAILABLE",
            "message": "Deed ID is not duplicated."
        }

    # ---------------------------------
    # Rule 2: Parcel
    # ---------------------------------
    parcel_exists = (
        parcel_id in set(parcels_df["parcel_id"])
    )

    if parcel_exists:
        rules["parcel_check"] = {
            "status": "PASS",
            "code": "PARCEL_FOUND",
            "message": "Parcel exists in the registry."
        }
    else:
        rules["parcel_check"] = {
            "status": "FAIL",
            "code": "PARCEL_NOT_FOUND",
            "message": "Parcel was not found."
        }

    # ---------------------------------
    # Rule 3: Seller ownership
    # ---------------------------------
    seller_area = get_owner_area(
        ledger_df,
        parcel_id,
        seller_id
    )

    if seller_area > 0:
        rules["seller_ownership_check"] = {
            "status": "PASS",
            "code": "SELLER_IS_OWNER",
            "message": (
                f"Seller currently owns "
                f"{seller_area} decimal."
            )
        }
    else:
        rules["seller_ownership_check"] = {
            "status": "FAIL",
            "code": "SELLER_NOT_OWNER",
            "message": (
                "Seller has no active ownership "
                "in this parcel."
            )
        }

    # ---------------------------------
    # Rule 4: Transfer area
    # ---------------------------------
    if transfer_area <= 0:
        rules["area_check"] = {
            "status": "FAIL",
            "code": "INVALID_TRANSFER_AREA",
            "message": "Transfer area must be positive."
        }

    elif transfer_area > seller_area:
        rules["area_check"] = {
            "status": "FAIL",
            "code": "INSUFFICIENT_OWNERSHIP",
            "message": (
                f"Requested {transfer_area} decimal, "
                f"but seller has {seller_area} decimal."
            )
        }

    else:
        rules["area_check"] = {
            "status": "PASS",
            "code": "AREA_AVAILABLE",
            "message": (
                f"Requested {transfer_area} decimal "
                "is within seller ownership."
            )
        }

    # ---------------------------------
    # Rule 5: Double-sale
    # ---------------------------------
    double_sale_result = check_double_sale(
        history_df,
        transaction
    )

    if double_sale_result["double_sale"]:
        rules["double_sale_check"] = {
            "status": "FAIL",
            "code": "DOUBLE_SALE",
            "message": (
                "The same identified land portion "
                "appears in a previous valid sale."
            )
        }

    elif double_sale_result["reason"] == "NO_PORTION_ID":
        rules["double_sale_check"] = {
            "status": "WARNING",
            "code": "PORTION_ID_UNAVAILABLE",
            "message": (
                "Double-sale verification is incomplete "
                "because no portion ID is available."
            )
        }

    else:
        rules["double_sale_check"] = {
            "status": "PASS",
            "code": "NO_PREVIOUS_SALE",
            "message": (
                "No previous valid sale was found "
                "for this portion."
            )
        }

    # ---------------------------------
    # Rule 6: Mutation consistency
    # ---------------------------------
    mutation_result = check_deed_mutation_match(
        mutation_df,
        transaction
    )

    if mutation_result["match"] is True:
        rules["mutation_check"] = {
            "status": "PASS",
            "code": "MUTATION_MATCH",
            "message": (
                "Deed seller matches the active "
                "mutation-side owner."
            )
        }

    elif mutation_result["match"] is False:
        rules["mutation_check"] = {
            "status": "FAIL",
            "code": "DEED_MUTATION_MISMATCH",
            "message": (
                f"Deed seller is {seller_id}, "
                f"but mutation record lists "
                f"{', '.join(mutation_result['mutation_owners'])}."
            )
        }

    else:
        rules["mutation_check"] = {
            "status": "WARNING",
            "code": "NO_MUTATION_RECORD",
            "message": (
                "No matching mutation record is available "
                "for this parcel portion."
            )
        }

    return rules

In [1012]:
def calculate_risk_level(rules):

    fail_count = sum(
        rule["status"] == "FAIL"
        for rule in rules.values()
    )

    warning_count = sum(
        rule["status"] == "WARNING"
        for rule in rules.values()
    )

    pass_count = sum(
        rule["status"] == "PASS"
        for rule in rules.values()
    )

    if fail_count > 0:
        risk_level = "HIGH"

    elif warning_count > 0:
        risk_level = "MEDIUM"

    else:
        risk_level = "LOW"

    return {
        "risk_level": risk_level,
        "pass_count": pass_count,
        "warning_count": warning_count,
        "fail_count": fail_count
    }

In [1013]:
def verify_transaction(
    ledger_df,
    history_df,
    mutation_df,
    transaction,
    people_df,
    parcels_df
):

    rules = evaluate_transaction_rules(
        ledger_df,
        history_df,
        mutation_df,
        transaction,
        people_df,
        parcels_df
    )

    risk_summary = calculate_risk_level(
        rules
    )

    return {
        "deed_id": transaction["deed_id"],
        "parcel_id": transaction["parcel_id"],
        "seller_id": transaction["seller_id"],
        "buyer_id": transaction["buyer_id"],

        "risk_level":
            risk_summary["risk_level"],

        "pass_count":
            risk_summary["pass_count"],

        "warning_count":
            risk_summary["warning_count"],

        "fail_count":
            risk_summary["fail_count"],

        "rules": rules
    }

In [1014]:
low_risk_transaction = {
    "deed_id": "DEED006",
    "deed_type": "SAF_KABALA",
    "execution_date": "2026-02-05",

    "seller_id": "P001",
    "buyer_id": "P003",

    "parcel_id": "PAR001",
    "portion_id": "PAR001-PART-C",

    "transferred_area_decimal": 2.0,
    "transaction_status": "PENDING"
}

In [1015]:
low_report = verify_transaction(
    ledger_after_test,
    accepted_transactions_df,
    mutation_df,
    low_risk_transaction,
    people_df,
    parcels_df
)

print("Risk:", low_report["risk_level"])
print("Pass:", low_report["pass_count"])
print("Warning:", low_report["warning_count"])
print("Fail:", low_report["fail_count"])

Risk: LOW
Pass: 6
Warning: 0
Fail: 0

In [1016]:
for rule_name, result in low_report["rules"].items():

    print(
        rule_name,
        "->",
        result["status"],
        "|",
        result["code"]
    )

deed_id_check -> PASS | DEED_ID_AVAILABLE
parcel_check -> PASS | PARCEL_FOUND
seller_ownership_check -> PASS | SELLER_IS_OWNER
area_check -> PASS | AREA_AVAILABLE
double_sale_check -> PASS | NO_PREVIOUS_SALE
mutation_check -> PASS | MUTATION_MATCH

In [1017]:
medium_risk_transaction = {
    "deed_id": "DEED007",
    "deed_type": "SAF_KABALA",
    "execution_date": "2026-02-06",

    "seller_id": "P001",
    "buyer_id": "P004",

    "parcel_id": "PAR001",
    "portion_id": "PAR001-PART-Z",

    "transferred_area_decimal": 2.0,
    "transaction_status": "PENDING"
}

In [1018]:
medium_report = verify_transaction(
    ledger_after_test,
    accepted_transactions_df,
    mutation_df,
    medium_risk_transaction,
    people_df,
    parcels_df
)

print("Risk:", medium_report["risk_level"])
print("Pass:", medium_report["pass_count"])
print("Warning:", medium_report["warning_count"])
print("Fail:", medium_report["fail_count"])

Risk: MEDIUM
Pass: 5
Warning: 1
Fail: 0

In [1019]:
high_report = verify_transaction(
    ledger_after_test,
    accepted_transactions_df,
    mutation_df,
    mutation_mismatch_transaction,
    people_df,
    parcels_df
)

print("Risk:", high_report["risk_level"])
print("Pass:", high_report["pass_count"])
print("Warning:", high_report["warning_count"])
print("Fail:", high_report["fail_count"])

Risk: HIGH
Pass: 5
Warning: 0
Fail: 1

In [1020]:
def print_risk_report(report):

    print("=" * 55)
    print("BHUMIGUARD BD — PRE-REGISTRATION CHECK")
    print("=" * 55)

    print("Deed:", report["deed_id"])
    print("Parcel:", report["parcel_id"])
    print("Seller:", report["seller_id"])
    print("Buyer:", report["buyer_id"])

    print("\nRULE CHECKS")
    print("-" * 55)

    for rule_name, result in report["rules"].items():

        print(
            f"{result['status']:7} | "
            f"{result['code']}"
        )

        print(
            "          ",
            result["message"]
        )

    print("\nSUMMARY")
    print("-" * 55)

    print("PASS:", report["pass_count"])
    print("WARNING:", report["warning_count"])
    print("FAIL:", report["fail_count"])

    print(
        "\nOVERALL RISK:",
        report["risk_level"]
    )

    print("\nScreening result only — manual/legal")
    print("verification may still be required.")

In [1021]:
print_risk_report(high_report)

=======================================================
BHUMIGUARD BD — PRE-REGISTRATION CHECK
=======================================================
Deed: DEED005
Parcel: PAR001
Seller: P001
Buyer: P003

RULE CHECKS
-------------------------------------------------------
PASS    | DEED_ID_AVAILABLE
           Deed ID is not duplicated.
PASS    | PARCEL_FOUND
           Parcel exists in the registry.
PASS    | SELLER_IS_OWNER
           Seller currently owns 15.0 decimal.
PASS    | AREA_AVAILABLE
           Requested 2.0 decimal is within seller ownership.
PASS    | NO_PREVIOUS_SALE
           No previous valid sale was found for this portion.
FAIL    | DEED_MUTATION_MISMATCH
           Deed seller is P001, but mutation record lists P004.

SUMMARY
-------------------------------------------------------
PASS: 5
WARNING: 0
FAIL: 1

OVERALL RISK: HIGH

Screening result only — manual/legal
verification may still be required.

In [1022]:
print("LOW TEST:")
print(
    low_report["risk_level"],
    low_report["pass_count"],
    low_report["warning_count"],
    low_report["fail_count"]
)

print("\nMEDIUM TEST:")
print(
    medium_report["risk_level"],
    medium_report["pass_count"],
    medium_report["warning_count"],
    medium_report["fail_count"]
)

print("\nHIGH TEST:")
print(
    high_report["risk_level"],
    high_report["pass_count"],
    high_report["warning_count"],
    high_report["fail_count"]
)

LOW TEST:
LOW 6 0 0

MEDIUM TEST:
MEDIUM 5 1 0

HIGH TEST:
HIGH 5 0 1

In [1023]:
print("STEP 14 SUMMARY")
print("----------------")

print(
    "LOW test:",
    low_report["risk_level"]
)

print(
    "MEDIUM test:",
    medium_report["risk_level"]
)

print(
    "HIGH test:",
    high_report["risk_level"]
)

print(
    "Rules evaluated:",
    len(low_report["rules"])
)

print(
    "Explainable messages:",
    all(
        "message" in result
        for result
        in high_report["rules"].values()
    )
)

print("\nUnified Risk Engine: READY")

STEP 14 SUMMARY
----------------
LOW test: LOW
MEDIUM test: MEDIUM
HIGH test: HIGH
Rules evaluated: 6
Explainable messages: True

Unified Risk Engine: READY

# STEP 15 — Automated Test Suite

Run multiple known transaction scenarios automatically.

The test suite verifies:

1. Valid / low-risk transaction
2. Seller not owner
3. Over-transfer
4. Double-sale
5. Duplicate deed
6. Deed-mutation mismatch
7. Missing mutation record / medium risk

The tests also verify that risk evaluation does not modify
the ownership ledger or accepted transaction history.

In [1024]:
automated_test_cases = [
    {
        "name": "LOW_RISK_VALID",
        "transaction": {
            "deed_id": "DEED011",
            "deed_type": "SAF_KABALA",
            "execution_date": "2026-03-01",
            "seller_id": "P001",
            "buyer_id": "P003",
            "parcel_id": "PAR001",
            "portion_id": "PAR001-PART-C",
            "transferred_area_decimal": 1.0,
            "transaction_status": "PENDING"
        },
        "expected_risk": "LOW",
        "expected_code": "MUTATION_MATCH"
    },

    {
        "name": "SELLER_NOT_OWNER",
        "transaction": {
            "deed_id": "DEED012",
            "deed_type": "SAF_KABALA",
            "execution_date": "2026-03-02",
            "seller_id": "P003",
            "buyer_id": "P004",
            "parcel_id": "PAR001",
            "portion_id": "PAR001-PART-X",
            "transferred_area_decimal": 1.0,
            "transaction_status": "PENDING"
        },
        "expected_risk": "HIGH",
        "expected_code": "SELLER_NOT_OWNER"
    },

    {
        "name": "OVER_TRANSFER",
        "transaction": {
            "deed_id": "DEED013",
            "deed_type": "SAF_KABALA",
            "execution_date": "2026-03-03",
            "seller_id": "P001",
            "buyer_id": "P003",
            "parcel_id": "PAR001",
            "portion_id": "PAR001-PART-Y",
            "transferred_area_decimal": 18.0,
            "transaction_status": "PENDING"
        },
        "expected_risk": "HIGH",
        "expected_code": "INSUFFICIENT_OWNERSHIP"
    },

    {
        "name": "DOUBLE_SALE",
        "transaction": {
            "deed_id": "DEED014",
            "deed_type": "SAF_KABALA",
            "execution_date": "2026-03-04",
            "seller_id": "P001",
            "buyer_id": "P003",
            "parcel_id": "PAR001",
            "portion_id": "PAR001-PART-A",
            "transferred_area_decimal": 1.0,
            "transaction_status": "PENDING"
        },
        "expected_risk": "HIGH",
        "expected_code": "DOUBLE_SALE"
    },

    {
        "name": "DUPLICATE_DEED",
        "transaction": {
            "deed_id": "DEED001",
            "deed_type": "SAF_KABALA",
            "execution_date": "2026-03-05",
            "seller_id": "P001",
            "buyer_id": "P003",
            "parcel_id": "PAR001",
            "portion_id": "PAR001-PART-C",
            "transferred_area_decimal": 1.0,
            "transaction_status": "PENDING"
        },
        "expected_risk": "HIGH",
        "expected_code": "DUPLICATE_DEED"
    },

    {
        "name": "MUTATION_MISMATCH",
        "transaction": {
            "deed_id": "DEED015",
            "deed_type": "SAF_KABALA",
            "execution_date": "2026-03-06",
            "seller_id": "P001",
            "buyer_id": "P003",
            "parcel_id": "PAR001",
            "portion_id": "PAR001-PART-B",
            "transferred_area_decimal": 1.0,
            "transaction_status": "PENDING"
        },
        "expected_risk": "HIGH",
        "expected_code": "DEED_MUTATION_MISMATCH"
    },

    {
        "name": "MISSING_MUTATION",
        "transaction": {
            "deed_id": "DEED016",
            "deed_type": "SAF_KABALA",
            "execution_date": "2026-03-07",
            "seller_id": "P001",
            "buyer_id": "P004",
            "parcel_id": "PAR001",
            "portion_id": "PAR001-PART-Z",
            "transferred_area_decimal": 1.0,
            "transaction_status": "PENDING"
        },
        "expected_risk": "MEDIUM",
        "expected_code": "NO_MUTATION_RECORD"
    }
]

print("Automated test cases:", len(automated_test_cases))

Automated test cases: 7

In [1025]:
def run_automated_tests(
    test_cases,
    ledger_df,
    history_df,
    mutation_df,
    people_df,
    parcels_df
):

    results = []

    for test in test_cases:

        report = verify_transaction(
            ledger_df,
            history_df,
            mutation_df,
            test["transaction"],
            people_df,
            parcels_df
        )

        rule_codes = [
            result["code"]
            for result in report["rules"].values()
        ]

        risk_pass = (
            report["risk_level"]
            == test["expected_risk"]
        )

        code_pass = (
            test["expected_code"]
            in rule_codes
        )

        test_pass = risk_pass and code_pass

        results.append({
            "test_name": test["name"],
            "expected_risk": test["expected_risk"],
            "actual_risk": report["risk_level"],
            "expected_code": test["expected_code"],
            "code_found": code_pass,
            "passed": test_pass
        })

    return pd.DataFrame(results)

In [1026]:
automated_results_df = run_automated_tests(
    automated_test_cases,
    ledger_after_test,
    accepted_transactions_df,
    mutation_df,
    people_df,
    parcels_df
)

automated_results_df

,test_name,expected_risk,actual_risk,expected_code,code_found,passed
0,LOW_RISK_VALID,LOW,LOW,MUTATION_MATCH,True,True
1,SELLER_NOT_OWNER,HIGH,HIGH,SELLER_NOT_OWNER,True,True
2,OVER_TRANSFER,HIGH,HIGH,INSUFFICIENT_OWNERSHIP,True,True
3,DOUBLE_SALE,HIGH,HIGH,DOUBLE_SALE,True,True
4,DUPLICATE_DEED,HIGH,HIGH,DUPLICATE_DEED,True,True
5,MUTATION_MISMATCH,HIGH,HIGH,DEED_MUTATION_MISMATCH,True,True
6,MISSING_MUTATION,MEDIUM,MEDIUM,NO_MUTATION_RECORD,True,True

In [1027]:
print(
    "Tests passed:",
    automated_results_df["passed"].sum()
)

print(
    "Tests failed:",
    (~automated_results_df["passed"]).sum()
)

Tests passed: 7
Tests failed: 0

In [1028]:
for _, row in automated_results_df.iterrows():

    status = "PASS" if row["passed"] else "FAIL"

    print(
        f"{status:4} | "
        f"{row['test_name']:20} | "
        f"Expected: {row['expected_risk']:6} | "
        f"Actual: {row['actual_risk']:6} | "
        f"Code: {row['expected_code']}"
    )

PASS | LOW_RISK_VALID       | Expected: LOW    | Actual: LOW    | Code: MUTATION_MATCH
PASS | SELLER_NOT_OWNER     | Expected: HIGH   | Actual: HIGH   | Code: SELLER_NOT_OWNER
PASS | OVER_TRANSFER        | Expected: HIGH   | Actual: HIGH   | Code: INSUFFICIENT_OWNERSHIP
PASS | DOUBLE_SALE          | Expected: HIGH   | Actual: HIGH   | Code: DOUBLE_SALE
PASS | DUPLICATE_DEED       | Expected: HIGH   | Actual: HIGH   | Code: DUPLICATE_DEED
PASS | MUTATION_MISMATCH    | Expected: HIGH   | Actual: HIGH   | Code: DEED_MUTATION_MISMATCH
PASS | MISSING_MUTATION     | Expected: MEDIUM | Actual: MEDIUM | Code: NO_MUTATION_RECORD

In [1029]:
ledger_snapshot = ledger_after_test.copy()
history_snapshot = accepted_transactions_df.copy()

for test in automated_test_cases:

    _ = verify_transaction(
        ledger_after_test,
        accepted_transactions_df,
        mutation_df,
        test["transaction"],
        people_df,
        parcels_df
    )

ledger_unchanged_after_tests = (
    ledger_snapshot.equals(
        ledger_after_test
    )
)

history_unchanged_after_tests = (
    history_snapshot.equals(
        accepted_transactions_df
    )
)

print(
    "Ledger unchanged:",
    ledger_unchanged_after_tests
)

print(
    "History unchanged:",
    history_unchanged_after_tests
)

Ledger unchanged:

 True
History unchanged: True

In [1030]:
valid_processing_transaction = {
    "deed_id": "DEED020",
    "deed_type": "SAF_KABALA",
    "execution_date": "2026-03-10",

    "seller_id": "P001",
    "buyer_id": "P003",

    "parcel_id": "PAR001",
    "portion_id": "PAR001-PART-C",

    "transferred_area_decimal": 1.0,
    "transaction_status": "PENDING"
}

In [1031]:
(
    valid_test_ledger,
    valid_test_history,
    valid_processing_result
) = process_transfer_full_checks(
    ledger_after_test,
    accepted_transactions_df,
    mutation_df,
    valid_processing_transaction,
    people_df,
    parcels_df
)

print(valid_processing_result)

{'valid': True, 'reason': 'VALID_TRANSFER'}

In [1032]:
print(
    "P001 after:",
    get_owner_area(
        valid_test_ledger,
        "PAR001",
        "P001"
    )
)

print(
    "P003 after:",
    get_owner_area(
        valid_test_ledger,
        "PAR001",
        "P003"
    )
)

print(
    "History records before:",
    len(accepted_transactions_df)
)

print(
    "History records after:",
    len(valid_test_history)
)

P001 after: 14.0
P003 after: 1.0
History records before: 1
History records after: 2

In [1033]:
print(
    "Original P001 remains:",
    get_owner_area(
        ledger_after_test,
        "PAR001",
        "P001"
    )
)

print(
    "Original history records:",
    len(accepted_transactions_df)
)

Original P001 remains: 15.0
Original history records: 1

In [1034]:
assert automated_results_df["passed"].all()

assert ledger_unchanged_after_tests is True
assert history_unchanged_after_tests is True

assert valid_processing_result["valid"] is True

assert get_owner_area(
    valid_test_ledger,
    "PAR001",
    "P001"
) == 14.0

assert get_owner_area(
    valid_test_ledger,
    "PAR001",
    "P003"
) == 1.0

assert len(valid_test_history) == 2

assert check_ledger_integrity(
    valid_test_ledger,
    parcels_df
) is True

print("All automated assertions: PASS")

All automated assertions: PASS

In [1035]:
print("STEP 15 SUMMARY")
print("----------------")

print(
    "Automated scenarios:",
    len(automated_results_df)
)

print(
    "Passed:",
    automated_results_df["passed"].sum()
)

print(
    "Failed:",
    (~automated_results_df["passed"]).sum()
)

print(
    "Risk evaluation preserves ledger:",
    ledger_unchanged_after_tests
)

print(
    "Risk evaluation preserves history:",
    history_unchanged_after_tests
)

print(
    "Valid transaction processing:",
    valid_processing_result["reason"]
)

print(
    "Final ledger integrity:",
    check_ledger_integrity(
        valid_test_ledger,
        parcels_df
    )
)

print("\nAutomated Core Test Suite: PASS")

STEP 15 SUMMARY
----------------
Automated scenarios: 7
Passed: 7
Failed: 0
Risk evaluation preserves ledger: True
Risk evaluation preserves history: True
Valid transaction processing: VALID_TRANSFER
Final ledger integrity: True

Automated Core Test Suite: PASS

# STEP 16A — Larger Synthetic Base Registry

Create a larger privacy-safe synthetic base registry before generating
fraud and transaction scenarios.

Initial target:

- 30 synthetic people
- 20 synthetic parcels
- 20 valid initial ownership records

The generation is deterministic and reproducible.
No real citizen or land record is used.

In [1036]:
import random

RANDOM_SEED = 42

random.seed(RANDOM_SEED)

print("Random seed:", RANDOM_SEED)

Random seed: 42

In [1037]:
large_people_data = []

for i in range(1, 31):

    large_people_data.append({
        "person_id": f"P{i:03d}",
        "name_bn": f"ব্যক্তি-{i:03d}"
    })

large_people_df = pd.DataFrame(
    large_people_data
)

large_people_df.head()

  person_id      name_bn
0      P001  ব্যক্তি-001
1      P002  ব্যক্তি-002
2      P003  ব্যক্তি-003
3      P004  ব্যক্তি-004
4      P005  ব্যক্তি-005

In [1038]:
print(
    "People records:",
    len(large_people_df)
)

print(
    "Unique person IDs:",
    large_people_df["person_id"].nunique()
)

print(
    "Duplicate IDs:",
    large_people_df["person_id"]
    .duplicated()
    .sum()
)

print(
    "Missing IDs:",
    large_people_df["person_id"]
    .isna()
    .sum()
)

People records: 30
Unique person IDs: 30
Duplicate IDs: 0
Missing IDs: 0

In [1039]:
survey_types = [
    "CS",
    "SA",
    "RS",
    "BS"
]

large_parcel_data = []

for i in range(1, 21):

    district_number = (
        ((i - 1) // 10) + 1
    )

    upazila_number = (
        ((i - 1) // 5) + 1
    )

    mouza_number = (
        ((i - 1) // 2) + 1
    )

    survey_type = survey_types[
        (i - 1) % len(survey_types)
    ]

    area = float(
        random.choice(
            [10, 12, 15, 18, 20, 25, 30]
        )
    )

    large_parcel_data.append({
        "parcel_id": f"PAR{i:03d}",

        "district":
            f"Demo-District-{district_number}",

        "upazila":
            f"Demo-Upazila-{upazila_number}",

        "mouza":
            f"Demo-Mouza-{mouza_number:02d}",

        "survey_type":
            survey_type,

        "khatian_no":
            str(200 + i),

        "dag_no":
            str(700 + i),

        "total_area_decimal":
            area
    })

large_parcels_df = pd.DataFrame(
    large_parcel_data
)

large_parcels_df.head()

,parcel_id,district,upazila,mouza,survey_type,khatian_no,dag_no,total_area_decimal
0,PAR001,Demo-District-1,Demo-Upazila-1,Demo-Mouza-01,CS,201,701,25.0
1,PAR002,Demo-District-1,Demo-Upazila-1,Demo-Mouza-01,SA,202,702,10.0
2,PAR003,Demo-District-1,Demo-Upazila-1,Demo-Mouza-02,RS,203,703,10.0
3,PAR004,Demo-District-1,Demo-Upazila-1,Demo-Mouza-02,BS,204,704,25.0
4,PAR005,Demo-District-1,Demo-Upazila-1,Demo-Mouza-03,CS,205,705,15.0

In [1040]:
large_parcels_df[
    "parcel_key"
] = large_parcels_df.apply(
    lambda row: create_parcel_key(
        row["district"],
        row["upazila"],
        row["mouza"],
        row["survey_type"],
        row["khatian_no"],
        row["dag_no"]
    ),
    axis=1
)

In [1041]:
large_parcels_df[
    [
        "parcel_id",
        "parcel_key"
    ]
].head()

  parcel_id                                         parcel_key
0    PAR001  DEMO-DISTRICT-1|DEMO-UPAZILA-1|DEMO-MOUZA-01|C...
1    PAR002  DEMO-DISTRICT-1|DEMO-UPAZILA-1|DEMO-MOUZA-01|S...
2    PAR003  DEMO-DISTRICT-1|DEMO-UPAZILA-1|DEMO-MOUZA-02|R...
3    PAR004  DEMO-DISTRICT-1|DEMO-UPAZILA-1|DEMO-MOUZA-02|B...
4    PAR005  DEMO-DISTRICT-1|DEMO-UPAZILA-1|DEMO-MOUZA-03|C...

In [1042]:
print(
    "Parcel records:",
    len(large_parcels_df)
)

print(
    "Unique parcel IDs:",
    large_parcels_df[
        "parcel_id"
    ].nunique()
)

print(
    "Unique ParcelKeys:",
    large_parcels_df[
        "parcel_key"
    ].nunique()
)

print(
    "Duplicate ParcelKeys:",
    large_parcels_df[
        "parcel_key"
    ].duplicated().sum()
)

print(
    "Missing ParcelKeys:",
    large_parcels_df[
        "parcel_key"
    ].isna().sum()
)

Parcel records: 20
Unique parcel IDs: 20
Unique ParcelKeys: 20
Duplicate ParcelKeys: 0
Missing ParcelKeys: 0

In [1043]:
print(
    "Minimum parcel area:",
    large_parcels_df[
        "total_area_decimal"
    ].min()
)

print(
    "Maximum parcel area:",
    large_parcels_df[
        "total_area_decimal"
    ].max()
)

print(
    "Total synthetic land area:",
    large_parcels_df[
        "total_area_decimal"
    ].sum()
)

Minimum parcel area: 10.0
Maximum parcel area: 25.0
Total synthetic land area: 316.0

In [1044]:
large_ownership_data = []

for i, parcel in large_parcels_df.iterrows():

    owner_id = large_people_df.iloc[
        i
    ]["person_id"]

    large_ownership_data.append({
        "ownership_id":
            f"OWN{i + 1:03d}",

        "parcel_id":
            parcel["parcel_id"],

        "owner_id":
            owner_id,

        "owned_area_decimal":
            parcel[
                "total_area_decimal"
            ],

        "valid_from":
            "2025-01-01",

        "status":
            "ACTIVE"
    })

large_ownership_df = pd.DataFrame(
    large_ownership_data
)

large_ownership_df.head()

  ownership_id parcel_id owner_id  owned_area_decimal  valid_from  status
0       OWN001    PAR001     P001                25.0  2025-01-01  ACTIVE
1       OWN002    PAR002     P002                10.0  2025-01-01  ACTIVE
2       OWN003    PAR003     P003                10.0  2025-01-01  ACTIVE
3       OWN004    PAR004     P004                25.0  2025-01-01  ACTIVE
4       OWN005    PAR005     P005                15.0  2025-01-01  ACTIVE

In [1045]:
invalid_large_owners = (
    ~large_ownership_df[
        "owner_id"
    ].isin(
        large_people_df[
            "person_id"
        ]
    )
).sum()

invalid_large_parcels = (
    ~large_ownership_df[
        "parcel_id"
    ].isin(
        large_parcels_df[
            "parcel_id"
        ]
    )
).sum()

print(
    "Invalid owner references:",
    invalid_large_owners
)

print(
    "Invalid parcel references:",
    invalid_large_parcels
)

Invalid owner references: 0
Invalid parcel references: 0

In [1046]:
large_ledger_integrity = (
    check_ledger_integrity(
        large_ownership_df,
        large_parcels_df
    )
)

print(
    "Large registry ledger integrity:",
    large_ledger_integrity
)

Large registry ledger integrity: True

In [1047]:
large_owner_view = (
    large_ownership_df
    .merge(
        large_people_df,
        left_on="owner_id",
        right_on="person_id",
        how="left"
    )
)

large_owner_view[
    [
        "parcel_id",
        "owner_id",
        "name_bn",
        "owned_area_decimal"
    ]
].head(10)

  parcel_id owner_id      name_bn  owned_area_decimal
0    PAR001     P001  ব্যক্তি-001                25.0
1    PAR002     P002  ব্যক্তি-002                10.0
2    PAR003     P003  ব্যক্তি-003                10.0
3    PAR004     P004  ব্যক্তি-004                25.0
4    PAR005     P005  ব্যক্তি-005                15.0
5    PAR006     P006  ব্যক্তি-006                12.0
6    PAR007     P007  ব্যক্তি-007                12.0
7    PAR008     P008  ব্যক্তি-008                12.0
8    PAR009     P009  ব্যক্তি-009                25.0
9    PAR010     P010  ব্যক্তি-010                10.0

In [1048]:
total_parcel_area = (
    large_parcels_df[
        "total_area_decimal"
    ].sum()
)

total_owned_area = (
    large_ownership_df[
        "owned_area_decimal"
    ].sum()
)

print(
    "Total parcel area:",
    total_parcel_area
)

print(
    "Total owned area:",
    total_owned_area
)

print(
    "Area conservation:",
    total_parcel_area
    == total_owned_area
)

Total parcel area: 316.0
Total owned area: 316.0
Area conservation: True

In [1049]:
print("STEP 16A SUMMARY")
print("----------------")

print(
    "Synthetic people:",
    len(large_people_df)
)

print(
    "Synthetic parcels:",
    len(large_parcels_df)
)

print(
    "Initial ownership records:",
    len(large_ownership_df)
)

print(
    "Unique ParcelKeys:",
    large_parcels_df[
        "parcel_key"
    ].nunique()
)

print(
    "Duplicate ParcelKeys:",
    large_parcels_df[
        "parcel_key"
    ].duplicated().sum()
)

print(
    "Invalid owner references:",
    invalid_large_owners
)

print(
    "Invalid parcel references:",
    invalid_large_parcels
)

print(
    "Area conservation:",
    total_parcel_area
    == total_owned_area
)

print(
    "Ledger integrity:",
    large_ledger_integrity
)

print(
    "\nLarge Synthetic Base Registry: READY"
)

STEP 16A SUMMARY
----------------
Synthetic people: 30
Synthetic parcels: 20
Initial ownership records: 20
Unique ParcelKeys: 20
Duplicate ParcelKeys: 0
Invalid owner references: 0
Invalid parcel references: 0
Area conservation: True
Ledger integrity: True

Large Synthetic Base Registry: READY

# STEP 16B — Controlled Ground-Truth Scenario Foundation

Create a frozen synthetic reference state for future dataset generation.

The goal is to construct logically controlled scenarios for:

- VALID
- SELLER_NOT_OWNER
- OVER_TRANSFER
- DOUBLE_SALE
- DUPLICATE_DEED
- MUTATION_MISMATCH

Each scenario has a known expected decision before large-scale generation.

In [1050]:
large_history_columns = [
    "deed_id",
    "deed_type",
    "execution_date",
    "seller_id",
    "buyer_id",
    "parcel_id",
    "portion_id",
    "transferred_area_decimal",
    "transaction_status"
]

large_history_df = pd.DataFrame(
    columns=large_history_columns
)

print(
    "Initial history records:",
    len(large_history_df)
)

Initial history records: 0

In [1051]:
baseline_transactions = [
    {
        "deed_id": "DEED1001",
        "deed_type": "SAF_KABALA",
        "execution_date": "2026-01-05",
        "seller_id": "P001",
        "buyer_id": "P021",
        "parcel_id": "PAR001",
        "portion_id": "PAR001-PART-A",
        "transferred_area_decimal": 2.0,
        "transaction_status": "PENDING"
    },

    {
        "deed_id": "DEED1002",
        "deed_type": "SAF_KABALA",
        "execution_date": "2026-01-06",
        "seller_id": "P002",
        "buyer_id": "P022",
        "parcel_id": "PAR002",
        "portion_id": "PAR002-PART-A",
        "transferred_area_decimal": 2.0,
        "transaction_status": "PENDING"
    },

    {
        "deed_id": "DEED1003",
        "deed_type": "SAF_KABALA",
        "execution_date": "2026-01-07",
        "seller_id": "P003",
        "buyer_id": "P023",
        "parcel_id": "PAR003",
        "portion_id": "PAR003-PART-A",
        "transferred_area_decimal": 2.0,
        "transaction_status": "PENDING"
    },

    {
        "deed_id": "DEED1004",
        "deed_type": "SAF_KABALA",
        "execution_date": "2026-01-08",
        "seller_id": "P004",
        "buyer_id": "P024",
        "parcel_id": "PAR004",
        "portion_id": "PAR004-PART-A",
        "transferred_area_decimal": 2.0,
        "transaction_status": "PENDING"
    }
]

print(
    "Baseline transactions:",
    len(baseline_transactions)
)

Baseline transactions: 4

In [1052]:
large_reference_ledger_df = (
    large_ownership_df.copy()
)

large_reference_history_df = (
    large_history_df.copy()
)

baseline_results = []

for transaction in baseline_transactions:

    (
        large_reference_ledger_df,
        large_reference_history_df,
        result
    ) = process_transfer_with_checks(
        large_reference_ledger_df,
        large_reference_history_df,
        transaction,
        large_people_df,
        large_parcels_df
    )

    baseline_results.append({
        "deed_id": transaction["deed_id"],
        "valid": result["valid"],
        "reason": result["reason"]
    })

baseline_results_df = pd.DataFrame(
    baseline_results
)

baseline_results_df

    deed_id  valid          reason
0  DEED1001   True  VALID_TRANSFER
1  DEED1002   True  VALID_TRANSFER
2  DEED1003   True  VALID_TRANSFER
3  DEED1004   True  VALID_TRANSFER

In [1053]:
print(
    "Baseline accepted:",
    baseline_results_df[
        "valid"
    ].sum()
)

print(
    "Baseline rejected:",
    (~baseline_results_df[
        "valid"
    ]).sum()
)

print(
    "History records:",
    len(
        large_reference_history_df
    )
)

print(
    "Reference ledger integrity:",
    check_ledger_integrity(
        large_reference_ledger_df,
        large_parcels_df
    )
)

Baseline accepted: 4
Baseline rejected: 0
History records: 4
Reference ledger integrity: True

In [1054]:
print(
    "P001 remaining PAR001:",
    get_owner_area(
        large_reference_ledger_df,
        "PAR001",
        "P001"
    )
)

print(
    "P021 ownership PAR001:",
    get_owner_area(
        large_reference_ledger_df,
        "PAR001",
        "P021"
    )
)

P001 remaining PAR001: 23.0
P021 ownership PAR001: 2.0

In [1055]:
large_mutation_data = []

for i, parcel in large_parcels_df.iterrows():

    owner_id = f"P{i + 1:03d}"

    large_mutation_data.append({
        "mutation_id":
            f"MUT{i + 1:03d}",

        "parcel_id":
            parcel["parcel_id"],

        "portion_id":
            f"{parcel['parcel_id']}-PART-B",

        "mutation_owner_id":
            owner_id,

        "mutation_area_decimal":
            5.0,

        "effective_date":
            "2026-01-15",

        "status":
            "ACTIVE"
    })

large_mutation_df = pd.DataFrame(
    large_mutation_data
)

large_mutation_df.head()

,mutation_id,parcel_id,portion_id,mutation_owner_id,mutation_area_decimal,effective_date,status
0,MUT001,PAR001,PAR001-PART-B,P001,5.0,2026-01-15,ACTIVE
1,MUT002,PAR002,PAR002-PART-B,P002,5.0,2026-01-15,ACTIVE
2,MUT003,PAR003,PAR003-PART-B,P003,5.0,2026-01-15,ACTIVE
3,MUT004,PAR004,PAR004-PART-B,P004,5.0,2026-01-15,ACTIVE
4,MUT005,PAR005,PAR005-PART-B,P005,5.0,2026-01-15,ACTIVE

In [1056]:
print(
    "Mutation records:",
    len(large_mutation_df)
)

print(
    "Unique mutation IDs:",
    large_mutation_df[
        "mutation_id"
    ].nunique()
)

print(
    "Invalid mutation owners:",
    (
        ~large_mutation_df[
            "mutation_owner_id"
        ].isin(
            large_people_df[
                "person_id"
            ]
        )
    ).sum()
)

print(
    "Invalid mutation parcels:",
    (
        ~large_mutation_df[
            "parcel_id"
        ].isin(
            large_parcels_df[
                "parcel_id"
            ]
        )
    ).sum()
)

Mutation records: 20
Unique mutation IDs: 20
Invalid mutation owners: 0
Invalid mutation parcels: 0

In [1057]:
scenario_mutation_df = (
    large_mutation_df.copy()
)

mismatch_mask = (
    (scenario_mutation_df["parcel_id"] == "PAR009") &
    (
        scenario_mutation_df["portion_id"]
        == "PAR009-PART-B"
    )
)

scenario_mutation_df.loc[
    mismatch_mask,
    "mutation_owner_id"
] = "P030"

scenario_mutation_df[
    scenario_mutation_df[
        "parcel_id"
    ] == "PAR009"
]

,mutation_id,parcel_id,portion_id,mutation_owner_id,mutation_area_decimal,effective_date,status
8,MUT009,PAR009,PAR009-PART-B,P030,5.0,2026-01-15,ACTIVE

In [1058]:
par007_available = get_owner_area(
    large_reference_ledger_df,
    "PAR007",
    "P007"
)

par007_over_transfer = (
    par007_available + 1.0
)

print(
    "PAR007 seller available:",
    par007_available
)

print(
    "Over-transfer request:",
    par007_over_transfer
)

PAR007 seller available: 12.0
Over-transfer request: 13.0

In [1059]:
canonical_scenarios = [
    {
        "scenario_id": "SCN001",
        "scenario_label": "VALID",
        "expected_decision": "VALID_TRANSFER",

        "transaction": {
            "deed_id": "DEED2001",
            "deed_type": "SAF_KABALA",
            "execution_date": "2026-02-01",

            "seller_id": "P005",
            "buyer_id": "P025",

            "parcel_id": "PAR005",
            "portion_id": "PAR005-PART-B",

            "transferred_area_decimal": 1.0,
            "transaction_status": "PENDING"
        }
    },

    {
        "scenario_id": "SCN002",
        "scenario_label": "SELLER_NOT_OWNER",
        "expected_decision": "SELLER_NOT_OWNER",

        "transaction": {
            "deed_id": "DEED2002",
            "deed_type": "SAF_KABALA",
            "execution_date": "2026-02-02",

            "seller_id": "P030",
            "buyer_id": "P026",

            "parcel_id": "PAR006",
            "portion_id": "PAR006-PART-X",

            "transferred_area_decimal": 1.0,
            "transaction_status": "PENDING"
        }
    },

    {
        "scenario_id": "SCN003",
        "scenario_label": "OVER_TRANSFER",
        "expected_decision": "INSUFFICIENT_OWNERSHIP",

        "transaction": {
            "deed_id": "DEED2003",
            "deed_type": "SAF_KABALA",
            "execution_date": "2026-02-03",

            "seller_id": "P007",
            "buyer_id": "P027",

            "parcel_id": "PAR007",
            "portion_id": "PAR007-PART-B",

            "transferred_area_decimal":
                par007_over_transfer,

            "transaction_status": "PENDING"
        }
    },

    {
        "scenario_id": "SCN004",
        "scenario_label": "DOUBLE_SALE",
        "expected_decision": "DOUBLE_SALE",

        "transaction": {
            "deed_id": "DEED2004",
            "deed_type": "SAF_KABALA",
            "execution_date": "2026-02-04",

            "seller_id": "P001",
            "buyer_id": "P028",

            "parcel_id": "PAR001",
            "portion_id": "PAR001-PART-A",

            "transferred_area_decimal": 1.0,
            "transaction_status": "PENDING"
        }
    },

    {
        "scenario_id": "SCN005",
        "scenario_label": "DUPLICATE_DEED",
        "expected_decision": "DUPLICATE_DEED",

        "transaction": {
            "deed_id": "DEED1002",
            "deed_type": "SAF_KABALA",
            "execution_date": "2026-02-05",

            "seller_id": "P008",
            "buyer_id": "P029",

            "parcel_id": "PAR008",
            "portion_id": "PAR008-PART-B",

            "transferred_area_decimal": 1.0,
            "transaction_status": "PENDING"
        }
    },

    {
        "scenario_id": "SCN006",
        "scenario_label": "MUTATION_MISMATCH",
        "expected_decision":
            "DEED_MUTATION_MISMATCH",

        "transaction": {
            "deed_id": "DEED2006",
            "deed_type": "SAF_KABALA",
            "execution_date": "2026-02-06",

            "seller_id": "P009",
            "buyer_id": "P025",

            "parcel_id": "PAR009",
            "portion_id": "PAR009-PART-B",

            "transferred_area_decimal": 1.0,
            "transaction_status": "PENDING"
        }
    }
]

print(
    "Canonical scenarios:",
    len(canonical_scenarios)
)

Canonical scenarios: 6

In [1060]:
scenario_results = []

for scenario in canonical_scenarios:

    transaction = scenario[
        "transaction"
    ]

    (
        _test_ledger,
        _test_history,
        result
    ) = process_transfer_full_checks(
        large_reference_ledger_df,
        large_reference_history_df,
        scenario_mutation_df,
        transaction,
        large_people_df,
        large_parcels_df
    )

    actual_decision = result[
        "reason"
    ]

    passed = (
        actual_decision
        == scenario[
            "expected_decision"
        ]
    )

    scenario_results.append({
        "scenario_id":
            scenario["scenario_id"],

        "scenario_label":
            scenario["scenario_label"],

        "expected_decision":
            scenario[
                "expected_decision"
            ],

        "actual_decision":
            actual_decision,

        "passed":
            passed
    })

scenario_results_df = pd.DataFrame(
    scenario_results
)

scenario_results_df

,scenario_id,scenario_label,expected_decision,actual_decision,passed
0,SCN001,VALID,VALID_TRANSFER,VALID_TRANSFER,True
1,SCN002,SELLER_NOT_OWNER,SELLER_NOT_OWNER,SELLER_NOT_OWNER,True
2,SCN003,OVER_TRANSFER,INSUFFICIENT_OWNERSHIP,INSUFFICIENT_OWNERSHIP,True
3,SCN004,DOUBLE_SALE,DOUBLE_SALE,DOUBLE_SALE,True
4,SCN005,DUPLICATE_DEED,DUPLICATE_DEED,DUPLICATE_DEED,True
5,SCN006,MUTATION_MISMATCH,DEED_MUTATION_MISMATCH,DEED_MUTATION_MISMATCH,True

In [1061]:
for _, row in scenario_results_df.iterrows():

    status = (
        "PASS"
        if row["passed"]
        else "FAIL"
    )

    print(
        f"{status:4} | "
        f"{row['scenario_label']:20} | "
        f"Expected: "
        f"{row['expected_decision']:25} | "
        f"Actual: "
        f"{row['actual_decision']}"
    )

PASS | VALID                | Expected: VALID_TRANSFER            | Actual: VALID_TRANSFER
PASS | SELLER_NOT_OWNER     | Expected: SELLER_NOT_OWNER          | Actual: SELLER_NOT_OWNER
PASS | OVER_TRANSFER        | Expected: INSUFFICIENT_OWNERSHIP    | Actual: INSUFFICIENT_OWNERSHIP
PASS | DOUBLE_SALE          | Expected: DOUBLE_SALE               | Actual: DOUBLE_SALE
PASS | DUPLICATE_DEED       | Expected: DUPLICATE_DEED            | Actual: DUPLICATE_DEED
PASS | MUTATION_MISMATCH    | Expected: DEED_MUTATION_MISMATCH    | Actual: DEED_MUTATION_MISMATCH

In [1062]:
reference_ledger_snapshot = (
    large_reference_ledger_df.copy()
)

reference_history_snapshot = (
    large_reference_history_df.copy()
)

In [1063]:
for scenario in canonical_scenarios:

    _ = process_transfer_full_checks(
        large_reference_ledger_df,
        large_reference_history_df,
        scenario_mutation_df,
        scenario["transaction"],
        large_people_df,
        large_parcels_df
    )

In [1064]:
reference_ledger_unchanged = (
    reference_ledger_snapshot.equals(
        large_reference_ledger_df
    )
)

reference_history_unchanged = (
    reference_history_snapshot.equals(
        large_reference_history_df
    )
)

print(
    "Reference ledger unchanged:",
    reference_ledger_unchanged
)

print(
    "Reference history unchanged:",
    reference_history_unchanged
)

Reference ledger unchanged: True
Reference history unchanged: True

In [1065]:
assert len(
    large_reference_history_df
) == 4

assert baseline_results_df[
    "valid"
].all()

assert scenario_results_df[
    "passed"
].all()

assert reference_ledger_unchanged is True

assert reference_history_unchanged is True

assert check_ledger_integrity(
    large_reference_ledger_df,
    large_parcels_df
) is True

assert len(
    scenario_results_df[
        "scenario_label"
    ].unique()
) == 6

print(
    "Controlled ground-truth assertions: PASS"
)

Controlled ground-truth assertions: PASS

In [1066]:
print("STEP 16B SUMMARY")
print("----------------")

print(
    "Synthetic people:",
    len(large_people_df)
)

print(
    "Synthetic parcels:",
    len(large_parcels_df)
)

print(
    "Baseline accepted transactions:",
    len(large_reference_history_df)
)

print(
    "Clean mutation records:",
    len(large_mutation_df)
)

print(
    "Canonical scenarios:",
    len(canonical_scenarios)
)

print(
    "Unique scenario labels:",
    scenario_results_df[
        "scenario_label"
    ].nunique()
)

print(
    "Scenario tests passed:",
    scenario_results_df[
        "passed"
    ].sum()
)

print(
    "Scenario tests failed:",
    (~scenario_results_df[
        "passed"
    ]).sum()
)

print(
    "Reference ledger unchanged:",
    reference_ledger_unchanged
)

print(
    "Reference history unchanged:",
    reference_history_unchanged
)

print(
    "Reference ledger integrity:",
    check_ledger_integrity(
        large_reference_ledger_df,
        large_parcels_df
    )
)

print(
    "\nControlled Ground-Truth Foundation: READY"
)

STEP 16B SUMMARY
----------------
Synthetic people: 30
Synthetic parcels: 20
Baseline accepted transactions: 4
Clean mutation records: 20
Canonical scenarios: 6
Unique scenario labels: 6
Scenario tests passed: 6
Scenario tests failed: 0
Reference ledger unchanged: True
Reference history unchanged: True
Reference ledger integrity: True

Controlled Ground-Truth Foundation: READY

# STEP 16C — Balanced Synthetic Transaction Dataset

Generate a small controlled benchmark of 60 independent candidate
transactions.

Class distribution:

- 10 VALID
- 10 SELLER_NOT_OWNER
- 10 OVER_TRANSFER
- 10 DOUBLE_SALE
- 10 DUPLICATE_DEED
- 10 MUTATION_MISMATCH

Each candidate is evaluated independently against the same frozen
reference ledger, history, and synthetic mutation registry.

The dataset is not executed sequentially.

In [1067]:
synthetic_candidates = []

candidate_counter = 1

def add_candidate(
    label,
    expected_decision,
    transaction
):
    global candidate_counter

    synthetic_candidates.append({
        "candidate_id":
            f"CAND{candidate_counter:03d}",

        "scenario_label":
            label,

        "expected_decision":
            expected_decision,

        **transaction
    })

    candidate_counter += 1

In [1068]:
valid_parcels = [
    5, 6, 7, 8,
    10, 11, 12, 13, 14, 15
]

for j, parcel_number in enumerate(
    valid_parcels,
    start=1
):

    seller_id = (
        f"P{parcel_number:03d}"
    )

    buyer_id = (
        f"P{20 + j:03d}"
    )

    parcel_id = (
        f"PAR{parcel_number:03d}"
    )

    add_candidate(
        label="VALID",
        expected_decision="VALID_TRANSFER",

        transaction={
            "deed_id":
                f"DEED3{j:03d}",

            "deed_type":
                "SAF_KABALA",

            "execution_date":
                f"2026-03-{j:02d}",

            "seller_id":
                seller_id,

            "buyer_id":
                buyer_id,

            "parcel_id":
                parcel_id,

            "portion_id":
                f"{parcel_id}-PART-B",

            "transferred_area_decimal":
                1.0,

            "transaction_status":
                "PENDING"
        }
    )

In [1069]:
for j in range(1, 11):

    parcel_id = f"PAR{j:03d}"

    # Buyer will always be different from P030
    buyer_number = 21 + ((j - 1) % 9)

    buyer_id = f"P{buyer_number:03d}"

    add_candidate(
        label="SELLER_NOT_OWNER",
        expected_decision="SELLER_NOT_OWNER",

        transaction={
            "deed_id":
                f"DEED4{j:03d}",

            "deed_type":
                "SAF_KABALA",

            "execution_date":
                f"2026-04-{j:02d}",

            "seller_id":
                "P030",

            "buyer_id":
                buyer_id,

            "parcel_id":
                parcel_id,

            "portion_id":
                f"{parcel_id}-PART-X",

            "transferred_area_decimal":
                1.0,

            "transaction_status":
                "PENDING"
        }
    )

In [1070]:
over_transfer_parcels = [
    5, 6, 7, 8,
    10, 11, 12, 13, 14, 15
]

for j, parcel_number in enumerate(
    over_transfer_parcels,
    start=1
):

    parcel_id = (
        f"PAR{parcel_number:03d}"
    )

    seller_id = (
        f"P{parcel_number:03d}"
    )

    buyer_id = (
        f"P{20 + j:03d}"
    )

    available_area = get_owner_area(
        large_reference_ledger_df,
        parcel_id,
        seller_id
    )

    add_candidate(
        label="OVER_TRANSFER",
        expected_decision=
            "INSUFFICIENT_OWNERSHIP",

        transaction={
            "deed_id":
                f"DEED5{j:03d}",

            "deed_type":
                "SAF_KABALA",

            "execution_date":
                f"2026-05-{j:02d}",

            "seller_id":
                seller_id,

            "buyer_id":
                buyer_id,

            "parcel_id":
                parcel_id,

            "portion_id":
                f"{parcel_id}-PART-B",

            "transferred_area_decimal":
                available_area + 1.0,

            "transaction_status":
                "PENDING"
        }
    )

In [1071]:
historically_sold = [
    1, 2, 3, 4
]

for j in range(1, 11):

    parcel_number = historically_sold[
        (j - 1) % len(
            historically_sold
        )
    ]

    parcel_id = (
        f"PAR{parcel_number:03d}"
    )

    seller_id = (
        f"P{parcel_number:03d}"
    )

    buyer_id = (
        f"P{20 + ((j - 1) % 10) + 1:03d}"
    )

    add_candidate(
        label="DOUBLE_SALE",
        expected_decision="DOUBLE_SALE",

        transaction={
            "deed_id":
                f"DEED6{j:03d}",

            "deed_type":
                "SAF_KABALA",

            "execution_date":
                f"2026-06-{j:02d}",

            "seller_id":
                seller_id,

            "buyer_id":
                buyer_id,

            "parcel_id":
                parcel_id,

            "portion_id":
                f"{parcel_id}-PART-A",

            "transferred_area_decimal":
                1.0,

            "transaction_status":
                "PENDING"
        }
    )

In [1072]:
existing_deed_ids = [
    "DEED1001",
    "DEED1002",
    "DEED1003",
    "DEED1004"
]

for j in range(1, 11):

    parcel_number = 10 + j

    parcel_id = (
        f"PAR{parcel_number:03d}"
    )

    seller_id = (
        f"P{parcel_number:03d}"
    )

    buyer_id = (
        f"P{20 + j:03d}"
    )

    duplicate_deed_id = (
        existing_deed_ids[
            (j - 1)
            % len(existing_deed_ids)
        ]
    )

    add_candidate(
        label="DUPLICATE_DEED",
        expected_decision=
            "DUPLICATE_DEED",

        transaction={
            "deed_id":
                duplicate_deed_id,

            "deed_type":
                "SAF_KABALA",

            "execution_date":
                f"2026-07-{j:02d}",

            "seller_id":
                seller_id,

            "buyer_id":
                buyer_id,

            "parcel_id":
                parcel_id,

            "portion_id":
                f"{parcel_id}-PART-B",

            "transferred_area_decimal":
                1.0,

            "transaction_status":
                "PENDING"
        }
    )

In [1073]:
for j in range(1, 11):

    parcel_id = f"PAR{j:03d}"

    # Buyer will always be different from P030
    buyer_number = 21 + ((j - 1) % 9)

    buyer_id = f"P{buyer_number:03d}"

    add_candidate(
        label="SELLER_NOT_OWNER",
        expected_decision="SELLER_NOT_OWNER",

        transaction={
            "deed_id":
                f"DEED4{j:03d}",

            "deed_type":
                "SAF_KABALA",

            "execution_date":
                f"2026-04-{j:02d}",

            "seller_id":
                "P030",

            "buyer_id":
                buyer_id,

            "parcel_id":
                parcel_id,

            "portion_id":
                f"{parcel_id}-PART-X",

            "transferred_area_decimal":
                1.0,

            "transaction_status":
                "PENDING"
        }
    )

In [1074]:
synthetic_candidates_df = pd.DataFrame(
    synthetic_candidates
)

print(
    "Candidate records:",
    len(synthetic_candidates_df)
)

synthetic_candidates_df.head()

Candidate records: 60

,candidate_id,scenario_label,expected_decision,deed_id,deed_type,execution_date,seller_id,buyer_id,parcel_id,portion_id,transferred_area_decimal,transaction_status
0,CAND001,VALID,VALID_TRANSFER,DEED3001,SAF_KABALA,2026-03-01,P005,P021,PAR005,PAR005-PART-B,1.0,PENDING
1,CAND002,VALID,VALID_TRANSFER,DEED3002,SAF_KABALA,2026-03-02,P006,P022,PAR006,PAR006-PART-B,1.0,PENDING
2,CAND003,VALID,VALID_TRANSFER,DEED3003,SAF_KABALA,2026-03-03,P007,P023,PAR007,PAR007-PART-B,1.0,PENDING
3,CAND004,VALID,VALID_TRANSFER,DEED3004,SAF_KABALA,2026-03-04,P008,P024,PAR008,PAR008-PART-B,1.0,PENDING
4,CAND005,VALID,VALID_TRANSFER,DEED3005,SAF_KABALA,2026-03-05,P010,P025,PAR010,PAR010-PART-B,1.0,PENDING

In [1075]:
class_distribution = (
    synthetic_candidates_df[
        "scenario_label"
    ]
    .value_counts()
    .sort_index()
)

class_distribution

scenario_label
DOUBLE_SALE         10
DUPLICATE_DEED      10
OVER_TRANSFER       10
SELLER_NOT_OWNER    20
VALID               10
Name: count, dtype: int64

In [1076]:
print(
    "Unique scenario labels:",
    synthetic_candidates_df[
        "scenario_label"
    ].nunique()
)

print(
    "Minimum class size:",
    class_distribution.min()
)

print(
    "Maximum class size:",
    class_distribution.max()
)

Unique scenario labels: 5
Minimum class size: 10
Maximum class size: 20

In [1077]:
print(
    "Unique candidate IDs:",
    synthetic_candidates_df[
        "candidate_id"
    ].nunique()
)

print(
    "Duplicate candidate IDs:",
    synthetic_candidates_df[
        "candidate_id"
    ].duplicated().sum()
)

Unique candidate IDs: 60
Duplicate candidate IDs: 0

In [1078]:
evaluation_results = []

for _, row in synthetic_candidates_df.iterrows():

    transaction = {
        "deed_id":
            row["deed_id"],

        "deed_type":
            row["deed_type"],

        "execution_date":
            row["execution_date"],

        "seller_id":
            row["seller_id"],

        "buyer_id":
            row["buyer_id"],

        "parcel_id":
            row["parcel_id"],

        "portion_id":
            row["portion_id"],

        "transferred_area_decimal":
            float(
                row[
                    "transferred_area_decimal"
                ]
            ),

        "transaction_status":
            row["transaction_status"]
    }

    (
        _candidate_ledger,
        _candidate_history,
        result
    ) = process_transfer_full_checks(
        large_reference_ledger_df,
        large_reference_history_df,
        scenario_mutation_df,
        transaction,
        large_people_df,
        large_parcels_df
    )

    actual_decision = (
        result["reason"]
    )

    evaluation_results.append({
        "candidate_id":
            row["candidate_id"],

        "scenario_label":
            row["scenario_label"],

        "expected_decision":
            row["expected_decision"],

        "actual_decision":
            actual_decision,

        "passed":
            actual_decision
            == row["expected_decision"]
    })

In [1079]:
synthetic_evaluation_df = (
    pd.DataFrame(
        evaluation_results
    )
)

synthetic_evaluation_df.head(10)

  candidate_id scenario_label expected_decision actual_decision  passed
0      CAND001          VALID    VALID_TRANSFER  VALID_TRANSFER    True
1      CAND002          VALID    VALID_TRANSFER  VALID_TRANSFER    True
2      CAND003          VALID    VALID_TRANSFER  VALID_TRANSFER    True
3      CAND004          VALID    VALID_TRANSFER  VALID_TRANSFER    True
4      CAND005          VALID    VALID_TRANSFER  VALID_TRANSFER    True
5      CAND006          VALID    VALID_TRANSFER  VALID_TRANSFER    True
6      CAND007          VALID    VALID_TRANSFER  VALID_TRANSFER    True
7      CAND008          VALID    VALID_TRANSFER  VALID_TRANSFER    True
8      CAND009          VALID    VALID_TRANSFER  VALID_TRANSFER    True
9      CAND010          VALID    VALID_TRANSFER  VALID_TRANSFER    True

In [1080]:
passed_count = (
    synthetic_evaluation_df[
        "passed"
    ].sum()
)

failed_count = (
    (~synthetic_evaluation_df[
        "passed"
    ]).sum()
)

print(
    "Passed:",
    passed_count
)

print(
    "Failed:",
    failed_count
)

Passed: 60
Failed: 0

In [1081]:
failed_cases = synthetic_evaluation_df[
    synthetic_evaluation_df["passed"] == False
]

failed_cases

Empty DataFrame
Columns: [candidate_id, scenario_label, expected_decision, actual_decision, passed]
Index: []

In [1082]:
failed_ids = failed_cases["candidate_id"].tolist()

synthetic_candidates_df[
    synthetic_candidates_df["candidate_id"].isin(
        failed_ids
    )
][
    [
        "candidate_id",
        "scenario_label",
        "seller_id",
        "buyer_id",
        "parcel_id",
        "expected_decision"
    ]
]

Empty DataFrame
Columns: [candidate_id, scenario_label, seller_id, buyer_id, parcel_id, expected_decision]
Index: []

In [1083]:
class_validation = (
    synthetic_evaluation_df
    .groupby(
        "scenario_label"
    )["passed"]
    .agg(
        ["count", "sum"]
    )
)

class_validation[
    "failed"
] = (
    class_validation["count"]
    - class_validation["sum"]
)

class_validation

                  count  sum  failed
scenario_label
DOUBLE_SALE          10   10       0
DUPLICATE_DEED       10   10       0
OVER_TRANSFER        10   10       0
SELLER_NOT_OWNER     20   20       0
VALID                10   10       0

In [1084]:
invalid_candidate_sellers = (
    ~synthetic_candidates_df[
        "seller_id"
    ].isin(
        large_people_df[
            "person_id"
        ]
    )
).sum()

invalid_candidate_buyers = (
    ~synthetic_candidates_df[
        "buyer_id"
    ].isin(
        large_people_df[
            "person_id"
        ]
    )
).sum()

invalid_candidate_parcels = (
    ~synthetic_candidates_df[
        "parcel_id"
    ].isin(
        large_parcels_df[
            "parcel_id"
        ]
    )
).sum()

print(
    "Invalid seller references:",
    invalid_candidate_sellers
)

print(
    "Invalid buyer references:",
    invalid_candidate_buyers
)

print(
    "Invalid parcel references:",
    invalid_candidate_parcels
)

Invalid seller references: 0
Invalid buyer references: 0
Invalid parcel references: 0

In [1085]:
print(
    "Reference history records:",
    len(
        large_reference_history_df
    )
)

print(
    "Reference ledger integrity:",
    check_ledger_integrity(
        large_reference_ledger_df,
        large_parcels_df
    )
)

Reference history records: 4
Reference ledger integrity: True

In [1086]:
failed_cases = synthetic_evaluation_df[
    synthetic_evaluation_df["passed"] == False
]

print("Failed cases:", len(failed_cases))

if len(failed_cases) > 0:
    display(failed_cases)
else:
    print("All ground-truth decisions matched.")

Failed cases: 0
All ground-truth decisions matched.

In [1087]:
assert len(
    synthetic_candidates_df
) == 60

assert synthetic_candidates_df[
    "scenario_label"
].nunique() == 6

assert class_distribution.min() == 10
assert class_distribution.max() == 10

assert synthetic_candidates_df[
    "candidate_id"
].nunique() == 60

assert failed_count == 0
assert passed_count == 60

assert invalid_candidate_sellers == 0
assert invalid_candidate_buyers == 0
assert invalid_candidate_parcels == 0

assert len(
    large_reference_history_df
) == 4

assert check_ledger_integrity(
    large_reference_ledger_df,
    large_parcels_df
) is True

print(
    "Balanced synthetic dataset assertions: PASS"
)

AssertionError:

In [ ]:
print("Current records:", len(synthetic_candidates_df))

print("\nScenario distribution:")
print(
    synthetic_candidates_df[
        "scenario_label"
    ].value_counts(dropna=False)
)

print(
    "\nUnique scenario labels:",
    synthetic_candidates_df[
        "scenario_label"
    ].nunique()
)

Current records: 60

Scenario distribution:
scenario_label
SELLER_NOT_OWNER    20
VALID               10
OVER_TRANSFER       10
DOUBLE_SALE         10
DUPLICATE_DEED      10
Name: count, dtype: int64

Unique scenario labels: 5

In [ ]:
# =========================================
# STEP 16C — CLEAN 60-RECORD REBUILD
# =========================================

synthetic_candidates = []
candidate_counter = 1


def add_candidate(
    label,
    expected_decision,
    transaction
):
    global candidate_counter

    synthetic_candidates.append({
        "candidate_id":
            f"CAND{candidate_counter:03d}",

        "scenario_label":
            label,

        "expected_decision":
            expected_decision,

        **transaction
    })

    candidate_counter += 1


# -----------------------------------------
# 1. VALID — 10
# -----------------------------------------

valid_parcels = [
    5, 6, 7, 8,
    10, 11, 12, 13, 14, 15
]

for j, parcel_number in enumerate(
    valid_parcels,
    start=1
):
    parcel_id = f"PAR{parcel_number:03d}"
    seller_id = f"P{parcel_number:03d}"
    buyer_id = f"P{20 + j:03d}"

    add_candidate(
        "VALID",
        "VALID_TRANSFER",
        {
            "deed_id": f"DEED3{j:03d}",
            "deed_type": "SAF_KABALA",
            "execution_date": f"2026-03-{j:02d}",
            "seller_id": seller_id,
            "buyer_id": buyer_id,
            "parcel_id": parcel_id,
            "portion_id": f"{parcel_id}-PART-B",
            "transferred_area_decimal": 1.0,
            "transaction_status": "PENDING"
        }
    )


# -----------------------------------------
# 2. SELLER_NOT_OWNER — 10
# -----------------------------------------

for j in range(1, 11):

    parcel_id = f"PAR{j:03d}"

    # P030 is seller.
    # Buyer is always P021-P029, never P030.
    buyer_number = 21 + ((j - 1) % 9)
    buyer_id = f"P{buyer_number:03d}"

    add_candidate(
        "SELLER_NOT_OWNER",
        "SELLER_NOT_OWNER",
        {
            "deed_id": f"DEED4{j:03d}",
            "deed_type": "SAF_KABALA",
            "execution_date": f"2026-04-{j:02d}",
            "seller_id": "P030",
            "buyer_id": buyer_id,
            "parcel_id": parcel_id,
            "portion_id": f"{parcel_id}-PART-X",
            "transferred_area_decimal": 1.0,
            "transaction_status": "PENDING"
        }
    )


# -----------------------------------------
# 3. OVER_TRANSFER — 10
# -----------------------------------------

over_transfer_parcels = [
    5, 6, 7, 8,
    10, 11, 12, 13, 14, 15
]

for j, parcel_number in enumerate(
    over_transfer_parcels,
    start=1
):

    parcel_id = f"PAR{parcel_number:03d}"
    seller_id = f"P{parcel_number:03d}"
    buyer_id = f"P{20 + j:03d}"

    available_area = get_owner_area(
        large_reference_ledger_df,
        parcel_id,
        seller_id
    )

    add_candidate(
        "OVER_TRANSFER",
        "INSUFFICIENT_OWNERSHIP",
        {
            "deed_id": f"DEED5{j:03d}",
            "deed_type": "SAF_KABALA",
            "execution_date": f"2026-05-{j:02d}",
            "seller_id": seller_id,
            "buyer_id": buyer_id,
            "parcel_id": parcel_id,
            "portion_id": f"{parcel_id}-PART-B",
            "transferred_area_decimal":
                available_area + 1.0,
            "transaction_status": "PENDING"
        }
    )


# -----------------------------------------
# 4. DOUBLE_SALE — 10
# -----------------------------------------

historically_sold = [1, 2, 3, 4]

for j in range(1, 11):

    parcel_number = historically_sold[
        (j - 1) % 4
    ]

    parcel_id = f"PAR{parcel_number:03d}"
    seller_id = f"P{parcel_number:03d}"
    buyer_id = f"P{20 + j:03d}"

    add_candidate(
        "DOUBLE_SALE",
        "DOUBLE_SALE",
        {
            "deed_id": f"DEED6{j:03d}",
            "deed_type": "SAF_KABALA",
            "execution_date": f"2026-06-{j:02d}",
            "seller_id": seller_id,
            "buyer_id": buyer_id,
            "parcel_id": parcel_id,
            "portion_id": f"{parcel_id}-PART-A",
            "transferred_area_decimal": 1.0,
            "transaction_status": "PENDING"
        }
    )


# -----------------------------------------
# 5. DUPLICATE_DEED — 10
# -----------------------------------------

existing_deed_ids = [
    "DEED1001",
    "DEED1002",
    "DEED1003",
    "DEED1004"
]

for j in range(1, 11):

    parcel_number = 10 + j

    parcel_id = f"PAR{parcel_number:03d}"
    seller_id = f"P{parcel_number:03d}"
    buyer_id = f"P{20 + j:03d}"

    duplicate_deed_id = existing_deed_ids[
        (j - 1) % 4
    ]

    add_candidate(
        "DUPLICATE_DEED",
        "DUPLICATE_DEED",
        {
            "deed_id": duplicate_deed_id,
            "deed_type": "SAF_KABALA",
            "execution_date": f"2026-07-{j:02d}",
            "seller_id": seller_id,
            "buyer_id": buyer_id,
            "parcel_id": parcel_id,
            "portion_id": f"{parcel_id}-PART-B",
            "transferred_area_decimal": 1.0,
            "transaction_status": "PENDING"
        }
    )


# -----------------------------------------
# 6. MUTATION_MISMATCH — 10
# -----------------------------------------

for j in range(1, 11):

    buyer_id = f"P{20 + j:03d}"

    add_candidate(
        "MUTATION_MISMATCH",
        "DEED_MUTATION_MISMATCH",
        {
            "deed_id": f"DEED8{j:03d}",
            "deed_type": "SAF_KABALA",
            "execution_date": f"2026-08-{j:02d}",
            "seller_id": "P009",
            "buyer_id": buyer_id,
            "parcel_id": "PAR009",
            "portion_id": "PAR009-PART-B",
            "transferred_area_decimal": 1.0,
            "transaction_status": "PENDING"
        }
    )


# -----------------------------------------
# Build fresh DataFrame
# -----------------------------------------

synthetic_candidates_df = pd.DataFrame(
    synthetic_candidates
)

print(
    "Fresh candidate records:",
    len(synthetic_candidates_df)
)

print("\nScenario distribution:")

print(
    synthetic_candidates_df[
        "scenario_label"
    ]
    .value_counts()
    .sort_index()
)

Fresh candidate records: 60

Scenario distribution:
scenario_label
DOUBLE_SALE          10
DUPLICATE_DEED       10
MUTATION_MISMATCH    10
OVER_TRANSFER        10
SELLER_NOT_OWNER     10
VALID                10
Name: count, dtype: int64

In [ ]:
class_distribution = (
    synthetic_candidates_df[
        "scenario_label"
    ]
    .value_counts()
    .sort_index()
)

same_party_count = (
    synthetic_candidates_df["seller_id"]
    ==
    synthetic_candidates_df["buyer_id"]
).sum()

print(
    "Records:",
    len(synthetic_candidates_df)
)

print(
    "Unique labels:",
    synthetic_candidates_df[
        "scenario_label"
    ].nunique()
)

print(
    "Minimum class size:",
    class_distribution.min()
)

print(
    "Maximum class size:",
    class_distribution.max()
)

print(
    "Unique candidate IDs:",
    synthetic_candidates_df[
        "candidate_id"
    ].nunique()
)

print(
    "Seller = Buyer cases:",
    same_party_count
)

Records: 60
Unique labels: 6
Minimum class size: 10
Maximum class size: 10
Unique candidate IDs: 60
Seller = Buyer cases: 0

In [ ]:
assert len(synthetic_candidates_df) == 60

assert synthetic_candidates_df[
    "scenario_label"
].nunique() == 6

assert class_distribution.min() == 10
assert class_distribution.max() == 10

assert synthetic_candidates_df[
    "candidate_id"
].nunique() == 60

assert same_party_count == 0

print(
    "Synthetic structure checks: PASS"
)

Synthetic structure checks: PASS

In [ ]:
evaluation_results = []

for _, row in synthetic_candidates_df.iterrows():

    transaction = {
        "deed_id":
            row["deed_id"],

        "deed_type":
            row["deed_type"],

        "execution_date":
            row["execution_date"],

        "seller_id":
            row["seller_id"],

        "buyer_id":
            row["buyer_id"],

        "parcel_id":
            row["parcel_id"],

        "portion_id":
            row["portion_id"],

        "transferred_area_decimal":
            float(
                row[
                    "transferred_area_decimal"
                ]
            ),

        "transaction_status":
            row["transaction_status"]
    }

    (
        _candidate_ledger,
        _candidate_history,
        result
    ) = process_transfer_full_checks(
        large_reference_ledger_df,
        large_reference_history_df,
        scenario_mutation_df,
        transaction,
        large_people_df,
        large_parcels_df
    )

    actual_decision = result["reason"]

    evaluation_results.append({
        "candidate_id":
            row["candidate_id"],

        "scenario_label":
            row["scenario_label"],

        "expected_decision":
            row["expected_decision"],

        "actual_decision":
            actual_decision,

        "passed":
            actual_decision
            == row["expected_decision"]
    })


synthetic_evaluation_df = pd.DataFrame(
    evaluation_results
)

In [ ]:
passed_count = int(
    synthetic_evaluation_df[
        "passed"
    ].sum()
)

failed_count = int(
    (~synthetic_evaluation_df[
        "passed"
    ]).sum()
)

print(
    "Ground-truth passed:",
    passed_count
)

print(
    "Ground-truth failed:",
    failed_count
)

if failed_count > 0:

    display(
        synthetic_evaluation_df[
            synthetic_evaluation_df[
                "passed"
            ] == False
        ]
    )

Ground-truth passed: 60
Ground-truth failed: 0

# STEP 16D — Primary Rule Purity Audit

Verify that each synthetic candidate contains the intended conflict
without accidental additional critical conflicts.

For VALID records:
- No critical conflict should exist.

For each non-valid class:
- Exactly one intended critical conflict should exist.

Warnings such as missing mutation information are tracked separately
and are not treated as fraud/conflict labels.

In [1088]:
def audit_candidate_conflicts(
    transaction,
    ledger_df,
    history_df,
    mutation_df,
    people_df,
    parcels_df
):
    conflicts = []
    warnings = []

    seller_id = transaction["seller_id"]
    buyer_id = transaction["buyer_id"]
    parcel_id = transaction["parcel_id"]

    transfer_area = float(
        transaction["transferred_area_decimal"]
    )

    person_ids = set(
        people_df["person_id"]
    )

    parcel_ids = set(
        parcels_df["parcel_id"]
    )

    # ---------------------------------
    # Reference checks
    # ---------------------------------

    if seller_id not in person_ids:
        conflicts.append(
            "SELLER_NOT_FOUND"
        )

    if buyer_id not in person_ids:
        conflicts.append(
            "BUYER_NOT_FOUND"
        )

    if parcel_id not in parcel_ids:
        conflicts.append(
            "PARCEL_NOT_FOUND"
        )

        return {
            "conflicts": conflicts,
            "warnings": warnings
        }

    # ---------------------------------
    # Seller / buyer identity
    # ---------------------------------

    if seller_id == buyer_id:
        conflicts.append(
            "SELLER_BUYER_SAME"
        )

    # ---------------------------------
    # Duplicate deed
    # ---------------------------------

    duplicate_result = check_duplicate_deed(
        history_df,
        transaction["deed_id"]
    )

    if duplicate_result["duplicate"]:
        conflicts.append(
            "DUPLICATE_DEED"
        )

    # ---------------------------------
    # Double-sale
    # ---------------------------------

    double_sale_result = check_double_sale(
        history_df,
        transaction
    )

    if double_sale_result["double_sale"]:
        conflicts.append(
            "DOUBLE_SALE"
        )

    elif (
        double_sale_result["reason"]
        == "NO_PORTION_ID"
    ):
        warnings.append(
            "PORTION_ID_UNAVAILABLE"
        )

    # ---------------------------------
    # Seller ownership / area
    # ---------------------------------

    seller_area = get_owner_area(
        ledger_df,
        parcel_id,
        seller_id
    )

    if seller_area <= 0:

        conflicts.append(
            "SELLER_NOT_OWNER"
        )

    elif transfer_area <= 0:

        conflicts.append(
            "INVALID_TRANSFER_AREA"
        )

    elif transfer_area > seller_area:

        conflicts.append(
            "INSUFFICIENT_OWNERSHIP"
        )

    # ---------------------------------
    # Mutation consistency
    # ---------------------------------

    mutation_result = check_deed_mutation_match(
        mutation_df,
        transaction
    )

    if mutation_result["match"] is False:

        conflicts.append(
            "DEED_MUTATION_MISMATCH"
        )

    elif mutation_result["match"] is None:

        warnings.append(
            "NO_MUTATION_RECORD"
        )

    return {
        "conflicts": conflicts,
        "warnings": warnings
    }

In [1089]:
expected_conflict_map = {
    "VALID":
        None,

    "SELLER_NOT_OWNER":
        "SELLER_NOT_OWNER",

    "OVER_TRANSFER":
        "INSUFFICIENT_OWNERSHIP",

    "DOUBLE_SALE":
        "DOUBLE_SALE",

    "DUPLICATE_DEED":
        "DUPLICATE_DEED",

    "MUTATION_MISMATCH":
        "DEED_MUTATION_MISMATCH"
}

In [1090]:
expected_conflict_map

{'VALID': None,
 'SELLER_NOT_OWNER': 'SELLER_NOT_OWNER',
 'OVER_TRANSFER': 'INSUFFICIENT_OWNERSHIP',
 'DOUBLE_SALE': 'DOUBLE_SALE',
 'DUPLICATE_DEED': 'DUPLICATE_DEED',
 'MUTATION_MISMATCH': 'DEED_MUTATION_MISMATCH'}

In [1091]:
purity_results = []

for _, row in synthetic_candidates_df.iterrows():

    transaction = {
        "deed_id":
            row["deed_id"],

        "deed_type":
            row["deed_type"],

        "execution_date":
            row["execution_date"],

        "seller_id":
            row["seller_id"],

        "buyer_id":
            row["buyer_id"],

        "parcel_id":
            row["parcel_id"],

        "portion_id":
            row["portion_id"],

        "transferred_area_decimal":
            float(
                row[
                    "transferred_area_decimal"
                ]
            ),

        "transaction_status":
            row["transaction_status"]
    }

    audit = audit_candidate_conflicts(
        transaction,
        large_reference_ledger_df,
        large_reference_history_df,
        scenario_mutation_df,
        large_people_df,
        large_parcels_df
    )

    conflicts = audit["conflicts"]
    warnings = audit["warnings"]

    expected_conflict = (
        expected_conflict_map[
            row["scenario_label"]
        ]
    )

    if expected_conflict is None:

        pure = (
            len(conflicts) == 0
        )

    else:

        pure = (
            len(conflicts) == 1
            and conflicts[0]
            == expected_conflict
        )

    purity_results.append({
        "candidate_id":
            row["candidate_id"],

        "scenario_label":
            row["scenario_label"],

        "expected_conflict":
            expected_conflict,

        "conflict_count":
            len(conflicts),

        "conflicts":
            conflicts,

        "warning_count":
            len(warnings),

        "warnings":
            warnings,

        "rule_pure":
            pure
    })

In [1092]:
purity_df = pd.DataFrame(
    purity_results
)

purity_df.head(10)

,candidate_id,scenario_label,expected_conflict,conflict_count,conflicts,warning_count,warnings,rule_pure
0,CAND001,VALID,NaN,0,[],0,[],True
1,CAND002,VALID,NaN,0,[],0,[],True
2,CAND003,VALID,NaN,0,[],0,[],True
3,CAND004,VALID,NaN,0,[],0,[],True
4,CAND005,VALID,NaN,0,[],0,[],True
5,CAND006,VALID,NaN,0,[],0,[],True
6,CAND007,VALID,NaN,0,[],0,[],True
7,CAND008,VALID,NaN,0,[],0,[],True
8,CAND009,VALID,NaN,0,[],0,[],True
9,CAND010,VALID,NaN,0,[],0,[],True

In [1093]:
pure_count = int(
    purity_df[
        "rule_pure"
    ].sum()
)

impure_count = int(
    (~purity_df[
        "rule_pure"
    ]).sum()
)

print(
    "Primary-rule pure:",
    pure_count
)

print(
    "Impure:",
    impure_count
)

Primary-rule pure: 60
Impure: 0

In [1094]:
impure_records = purity_df[
    purity_df["rule_pure"] == False
]

print(
    "Impure records:",
    len(impure_records)
)

if len(impure_records) > 0:
    display(
        impure_records
    )
else:
    print(
        "No accidental multi-conflict records found."
    )

Impure records: 0
No accidental multi-conflict records found.

In [1095]:
print(
    purity_df[
        "conflict_count"
    ].value_counts().sort_index()
)

conflict_count
0    10
1    50
Name: count, dtype: int64

In [1096]:
valid_purity_df = purity_df[
    purity_df[
        "scenario_label"
    ] == "VALID"
]

valid_with_conflict = (
    valid_purity_df[
        "conflict_count"
    ] > 0
).sum()

print(
    "VALID records:",
    len(valid_purity_df)
)

print(
    "VALID records with conflicts:",
    valid_with_conflict
)

VALID records: 10
VALID records with conflicts: 0

In [1097]:
invalid_purity_df = purity_df[
    purity_df[
        "scenario_label"
    ] != "VALID"
]

exactly_one_conflict = (
    invalid_purity_df[
        "conflict_count"
    ] == 1
).sum()

print(
    "Non-valid records:",
    len(invalid_purity_df)
)

print(
    "Exactly one intended conflict:",
    exactly_one_conflict
)

Non-valid records: 50
Exactly one intended conflict: 50

In [1098]:
purity_by_class = (
    purity_df
    .groupby(
        "scenario_label"
    )
    .agg(
        records=(
            "candidate_id",
            "count"
        ),

        pure_records=(
            "rule_pure",
            "sum"
        ),

        average_conflicts=(
            "conflict_count",
            "mean"
        )
    )
)

purity_by_class

                  records  pure_records  average_conflicts
scenario_label
DOUBLE_SALE            10            10                1.0
DUPLICATE_DEED         10            10                1.0
OVER_TRANSFER          10            10                1.0
SELLER_NOT_OWNER       20            20                1.0
VALID                  10            10                0.0

In [1099]:
print(
    "Records with warnings:",
    (
        purity_df[
            "warning_count"
        ] > 0
    ).sum()
)

warning_rows = purity_df[
    purity_df[
        "warning_count"
    ] > 0
][
    [
        "candidate_id",
        "scenario_label",
        "warnings"
    ]
]

warning_rows.head(20)

Records with warnings: 30

   candidate_id    scenario_label              warnings
10      CAND011  SELLER_NOT_OWNER  [NO_MUTATION_RECORD]
11      CAND012  SELLER_NOT_OWNER  [NO_MUTATION_RECORD]
12      CAND013  SELLER_NOT_OWNER  [NO_MUTATION_RECORD]
13      CAND014  SELLER_NOT_OWNER  [NO_MUTATION_RECORD]
14      CAND015  SELLER_NOT_OWNER  [NO_MUTATION_RECORD]
15      CAND016  SELLER_NOT_OWNER  [NO_MUTATION_RECORD]
16      CAND017  SELLER_NOT_OWNER  [NO_MUTATION_RECORD]
17      CAND018  SELLER_NOT_OWNER  [NO_MUTATION_RECORD]
18      CAND019  SELLER_NOT_OWNER  [NO_MUTATION_RECORD]
19      CAND020  SELLER_NOT_OWNER  [NO_MUTATION_RECORD]
30      CAND031       DOUBLE_SALE  [NO_MUTATION_RECORD]
31      CAND032       DOUBLE_SALE  [NO_MUTATION_RECORD]
32      CAND033       DOUBLE_SALE  [NO_MUTATION_RECORD]
33      CAND034       DOUBLE_SALE  [NO_MUTATION_RECORD]
34      CAND035       DOUBLE_SALE  [NO_MUTATION_RECORD]
35      CAND036       DOUBLE_SALE  [NO_MUTATION_RECORD]
36      CAND037       DOUBLE_SALE  [NO_MUTATION_RECORD]
37      CAND038       DOUBLE_SALE  [NO_MUTATION_RECORD]
38      CAND039       DOUBLE_SALE  [NO_MUTATION_RECORD]
39      CAND040       DOUBLE_SALE  [NO_MUTATION_RECORD]

In [1100]:
decision_match_count = int(
    synthetic_evaluation_df[
        "passed"
    ].sum()
)

print(
    "Engine decision matches:",
    decision_match_count,
    "/",
    len(
        synthetic_evaluation_df
    )
)

Engine decision matches: 60 / 60

In [1101]:
assert len(
    purity_df
) == 60

assert pure_count == 60
assert impure_count == 0

assert valid_with_conflict == 0

assert len(
    invalid_purity_df
) == 50

assert exactly_one_conflict == 50

assert decision_match_count == 60

assert check_ledger_integrity(
    large_reference_ledger_df,
    large_parcels_df
) is True

print(
    "Primary-rule purity assertions: PASS"
)

Primary-rule purity assertions: PASS

In [1102]:
print("STEP 16D SUMMARY")
print("----------------")

print(
    "Records audited:",
    len(purity_df)
)

print(
    "Primary-rule pure:",
    pure_count
)

print(
    "Impure records:",
    impure_count
)

print(
    "VALID records with conflicts:",
    valid_with_conflict
)

print(
    "Non-valid records:",
    len(
        invalid_purity_df
    )
)

print(
    "Non-valid records with exactly "
    "one intended conflict:",
    exactly_one_conflict
)

print(
    "Engine decisions matched:",
    decision_match_count
)

print(
    "Reference ledger integrity:",
    check_ledger_integrity(
        large_reference_ledger_df,
        large_parcels_df
    )
)

print(
    "\nPrimary Rule Purity Audit: PASS"
)

STEP 16D SUMMARY
----------------
Records audited: 60
Primary-rule pure: 60
Impure records: 0
VALID records with conflicts: 0
Non-valid records: 50
Non-valid records with exactly one intended conflict: 50
Engine decisions matched: 60
Reference ledger integrity: True

Primary Rule Purity Audit: PASS

# STEP 16E — Scale Controlled Benchmark to 600 Candidates

Scale the verified synthetic benchmark to 600 independent candidate
transactions:

- 100 VALID
- 100 SELLER_NOT_OWNER
- 100 OVER_TRANSFER
- 100 DOUBLE_SALE
- 100 DUPLICATE_DEED
- 100 MUTATION_MISMATCH

Each candidate is evaluated independently against the same frozen
reference registry.

Validation requirements:

- balanced class distribution
- unique candidate IDs
- no seller=buyer errors
- all references valid
- 600/600 expected engine decisions
- primary-rule purity
- frozen reference state preserved

In [1103]:
scale_mutation_df = large_mutation_df.copy()

mismatch_parcel_numbers = [
    9, 16, 17, 18, 19, 20
]

for parcel_number in mismatch_parcel_numbers:

    parcel_id = f"PAR{parcel_number:03d}"
    portion_id = f"{parcel_id}-PART-B"

    mask = (
        (scale_mutation_df["parcel_id"] == parcel_id) &
        (scale_mutation_df["portion_id"] == portion_id)
    )

    scale_mutation_df.loc[
        mask,
        "mutation_owner_id"
    ] = "P030"


print(
    "Controlled mismatch parcels:",
    len(mismatch_parcel_numbers)
)

scale_mutation_df[
    scale_mutation_df["parcel_id"].isin(
        [
            f"PAR{x:03d}"
            for x in mismatch_parcel_numbers
        ]
    )
][
    [
        "parcel_id",
        "portion_id",
        "mutation_owner_id"
    ]
]

Controlled mismatch parcels: 6

   parcel_id     portion_id mutation_owner_id
8     PAR009  PAR009-PART-B              P030
15    PAR016  PAR016-PART-B              P030
16    PAR017  PAR017-PART-B              P030
17    PAR018  PAR018-PART-B              P030
18    PAR019  PAR019-PART-B              P030
19    PAR020  PAR020-PART-B              P030

In [1104]:
all_parcel_numbers = list(
    range(1, 21)
)

clean_parcel_numbers = [
    p
    for p in all_parcel_numbers
    if p not in mismatch_parcel_numbers
]

print(
    "Clean parcels:",
    len(clean_parcel_numbers)
)

print(
    clean_parcel_numbers
)

Clean parcels: 14
[1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 13, 14, 15]

In [1105]:
import random

SCALE_RANDOM_SEED = 2026

scale_rng = random.Random(
    SCALE_RANDOM_SEED
)

N_PER_CLASS = 100

scale_candidates = []
scale_candidate_counter = 1

In [1106]:
def add_scale_candidate(
    label,
    expected_decision,
    transaction
):
    global scale_candidate_counter

    scale_candidates.append({
        "candidate_id":
            f"SCAND{scale_candidate_counter:04d}",

        "scenario_label":
            label,

        "expected_decision":
            expected_decision,

        **transaction
    })

    scale_candidate_counter += 1


def synthetic_date(
    start_date,
    offset
):
    return (
        pd.Timestamp(start_date)
        + pd.Timedelta(days=offset)
    ).strftime("%Y-%m-%d")

In [1107]:
for i in range(N_PER_CLASS):

    parcel_number = scale_rng.choice(
        clean_parcel_numbers
    )

    parcel_id = f"PAR{parcel_number:03d}"
    seller_id = f"P{parcel_number:03d}"

    buyer_number = scale_rng.randint(
        21, 30
    )

    buyer_id = f"P{buyer_number:03d}"

    transfer_area = scale_rng.choice(
        [0.5, 1.0, 1.5, 2.0]
    )

    seller_available = get_owner_area(
        large_reference_ledger_df,
        parcel_id,
        seller_id
    )

    transfer_area = min(
        transfer_area,
        seller_available
    )

    add_scale_candidate(
        "VALID",
        "VALID_TRANSFER",
        {
            "deed_id":
                f"SCALE-V-{i + 1:04d}",

            "deed_type":
                "SAF_KABALA",

            "execution_date":
                synthetic_date(
                    "2026-03-01",
                    i
                ),

            "seller_id":
                seller_id,

            "buyer_id":
                buyer_id,

            "parcel_id":
                parcel_id,

            "portion_id":
                f"{parcel_id}-PART-B",

            "transferred_area_decimal":
                float(transfer_area),

            "transaction_status":
                "PENDING"
        }
    )

In [1108]:
non_owner_buyers = [
    f"P{x:03d}"
    for x in range(21, 30)
]

for i in range(N_PER_CLASS):

    parcel_number = scale_rng.choice(
        all_parcel_numbers
    )

    parcel_id = f"PAR{parcel_number:03d}"

    buyer_id = scale_rng.choice(
        non_owner_buyers
    )

    add_scale_candidate(
        "SELLER_NOT_OWNER",
        "SELLER_NOT_OWNER",
        {
            "deed_id":
                f"SCALE-SNO-{i + 1:04d}",

            "deed_type":
                "SAF_KABALA",

            "execution_date":
                synthetic_date(
                    "2026-06-15",
                    i
                ),

            "seller_id":
                "P030",

            "buyer_id":
                buyer_id,

            "parcel_id":
                parcel_id,

            "portion_id":
                f"{parcel_id}-PART-X",

            "transferred_area_decimal":
                1.0,

            "transaction_status":
                "PENDING"
        }
    )

In [1109]:
for i in range(N_PER_CLASS):

    parcel_number = scale_rng.choice(
        clean_parcel_numbers
    )

    parcel_id = f"PAR{parcel_number:03d}"
    seller_id = f"P{parcel_number:03d}"

    buyer_id = f"P{
        scale_rng.randint(21, 30)
    :03d}"

    available_area = get_owner_area(
        large_reference_ledger_df,
        parcel_id,
        seller_id
    )

    extra_area = scale_rng.choice(
        [0.5, 1.0, 2.0, 3.0]
    )

    add_scale_candidate(
        "OVER_TRANSFER",
        "INSUFFICIENT_OWNERSHIP",
        {
            "deed_id":
                f"SCALE-OT-{i + 1:04d}",

            "deed_type":
                "SAF_KABALA",

            "execution_date":
                synthetic_date(
                    "2026-09-25",
                    i
                ),

            "seller_id":
                seller_id,

            "buyer_id":
                buyer_id,

            "parcel_id":
                parcel_id,

            "portion_id":
                f"{parcel_id}-PART-B",

            "transferred_area_decimal":
                float(
                    available_area
                    + extra_area
                ),

            "transaction_status":
                "PENDING"
        }
    )

In [1110]:
sold_parcel_numbers = [
    1, 2, 3, 4
]

for i in range(N_PER_CLASS):

    parcel_number = scale_rng.choice(
        sold_parcel_numbers
    )

    parcel_id = f"PAR{parcel_number:03d}"
    seller_id = f"P{parcel_number:03d}"

    buyer_id = f"P{
        scale_rng.randint(21, 30)
    :03d}"

    add_scale_candidate(
        "DOUBLE_SALE",
        "DOUBLE_SALE",
        {
            "deed_id":
                f"SCALE-DS-{i + 1:04d}",

            "deed_type":
                "SAF_KABALA",

            "execution_date":
                synthetic_date(
                    "2027-01-03",
                    i
                ),

            "seller_id":
                seller_id,

            "buyer_id":
                buyer_id,

            "parcel_id":
                parcel_id,

            "portion_id":
                f"{parcel_id}-PART-A",

            "transferred_area_decimal":
                scale_rng.choice(
                    [0.5, 1.0, 1.5]
                ),

            "transaction_status":
                "PENDING"
        }
    )

In [1111]:
baseline_deed_ids = (
    large_reference_history_df[
        "deed_id"
    ].tolist()
)

print(
    "Baseline deed IDs:",
    baseline_deed_ids
)

Baseline deed IDs: ['DEED1001', 'DEED1002', 'DEED1003', 'DEED1004']

In [1112]:
for i in range(N_PER_CLASS):

    parcel_number = scale_rng.choice(
        clean_parcel_numbers
    )

    parcel_id = f"PAR{parcel_number:03d}"
    seller_id = f"P{parcel_number:03d}"

    buyer_id = f"P{
        scale_rng.randint(21, 30)
    :03d}"

    duplicate_deed_id = scale_rng.choice(
        baseline_deed_ids
    )

    add_scale_candidate(
        "DUPLICATE_DEED",
        "DUPLICATE_DEED",
        {
            "deed_id":
                duplicate_deed_id,

            "deed_type":
                "SAF_KABALA",

            "execution_date":
                synthetic_date(
                    "2027-04-15",
                    i
                ),

            "seller_id":
                seller_id,

            "buyer_id":
                buyer_id,

            "parcel_id":
                parcel_id,

            "portion_id":
                f"{parcel_id}-PART-B",

            "transferred_area_decimal":
                1.0,

            "transaction_status":
                "PENDING"
        }
    )

In [1113]:
for i in range(N_PER_CLASS):

    parcel_number = scale_rng.choice(
        mismatch_parcel_numbers
    )

    parcel_id = f"PAR{parcel_number:03d}"
    seller_id = f"P{parcel_number:03d}"

    buyer_id = scale_rng.choice(
        non_owner_buyers
    )

    add_scale_candidate(
        "MUTATION_MISMATCH",
        "DEED_MUTATION_MISMATCH",
        {
            "deed_id":
                f"SCALE-MM-{i + 1:04d}",

            "deed_type":
                "SAF_KABALA",

            "execution_date":
                synthetic_date(
                    "2027-07-24",
                    i
                ),

            "seller_id":
                seller_id,

            "buyer_id":
                buyer_id,

            "parcel_id":
                parcel_id,

            "portion_id":
                f"{parcel_id}-PART-B",

            "transferred_area_decimal":
                1.0,

            "transaction_status":
                "PENDING"
        }
    )

In [1114]:
scale_candidates_df = pd.DataFrame(
    scale_candidates
)

print(
    "Scaled candidates:",
    len(scale_candidates_df)
)

Scaled candidates: 600

In [1115]:
scale_class_distribution = (
    scale_candidates_df[
        "scenario_label"
    ]
    .value_counts()
    .sort_index()
)

scale_class_distribution

scenario_label
DOUBLE_SALE          100
DUPLICATE_DEED       100
MUTATION_MISMATCH    100
OVER_TRANSFER        100
SELLER_NOT_OWNER     100
VALID                100
Name: count, dtype: int64

In [1116]:
print(
    "Scenario classes:",
    scale_candidates_df[
        "scenario_label"
    ].nunique()
)

print(
    "Minimum class size:",
    scale_class_distribution.min()
)

print(
    "Maximum class size:",
    scale_class_distribution.max()
)

Scenario classes: 6
Minimum class size: 100
Maximum class size: 100

In [1117]:
scale_same_party_count = (
    scale_candidates_df[
        "seller_id"
    ]
    ==
    scale_candidates_df[
        "buyer_id"
    ]
).sum()

scale_duplicate_candidate_ids = (
    scale_candidates_df[
        "candidate_id"
    ]
    .duplicated()
    .sum()
)

scale_invalid_sellers = (
    ~scale_candidates_df[
        "seller_id"
    ].isin(
        large_people_df[
            "person_id"
        ]
    )
).sum()

scale_invalid_buyers = (
    ~scale_candidates_df[
        "buyer_id"
    ].isin(
        large_people_df[
            "person_id"
        ]
    )
).sum()

scale_invalid_parcels = (
    ~scale_candidates_df[
        "parcel_id"
    ].isin(
        large_parcels_df[
            "parcel_id"
        ]
    )
).sum()

print(
    "Seller = Buyer:",
    scale_same_party_count
)

print(
    "Duplicate candidate IDs:",
    scale_duplicate_candidate_ids
)

print(
    "Invalid sellers:",
    scale_invalid_sellers
)

print(
    "Invalid buyers:",
    scale_invalid_buyers
)

print(
    "Invalid parcels:",
    scale_invalid_parcels
)

Seller = Buyer: 0
Duplicate candidate IDs: 0
Invalid sellers: 0
Invalid buyers: 0
Invalid parcels: 0

In [1118]:
scale_evaluation_results = []

for _, row in scale_candidates_df.iterrows():

    transaction = {
        "deed_id":
            row["deed_id"],

        "deed_type":
            row["deed_type"],

        "execution_date":
            row["execution_date"],

        "seller_id":
            row["seller_id"],

        "buyer_id":
            row["buyer_id"],

        "parcel_id":
            row["parcel_id"],

        "portion_id":
            row["portion_id"],

        "transferred_area_decimal":
            float(
                row[
                    "transferred_area_decimal"
                ]
            ),

        "transaction_status":
            row["transaction_status"]
    }

    (
        _ledger,
        _history,
        result
    ) = process_transfer_full_checks(
        large_reference_ledger_df,
        large_reference_history_df,
        scale_mutation_df,
        transaction,
        large_people_df,
        large_parcels_df
    )

    actual_decision = (
        result["reason"]
    )

    scale_evaluation_results.append({
        "candidate_id":
            row["candidate_id"],

        "scenario_label":
            row["scenario_label"],

        "expected_decision":
            row["expected_decision"],

        "actual_decision":
            actual_decision,

        "passed":
            actual_decision
            == row["expected_decision"]
    })


scale_evaluation_df = pd.DataFrame(
    scale_evaluation_results
)

In [1119]:
scale_passed_count = int(
    scale_evaluation_df[
        "passed"
    ].sum()
)

scale_failed_count = int(
    (~scale_evaluation_df[
        "passed"
    ]).sum()
)

print(
    "Ground-truth passed:",
    scale_passed_count
)

print(
    "Ground-truth failed:",
    scale_failed_count
)

Ground-truth passed: 600
Ground-truth failed: 0

In [1120]:
scale_purity_results = []

for _, row in scale_candidates_df.iterrows():

    transaction = {
        "deed_id":
            row["deed_id"],

        "deed_type":
            row["deed_type"],

        "execution_date":
            row["execution_date"],

        "seller_id":
            row["seller_id"],

        "buyer_id":
            row["buyer_id"],

        "parcel_id":
            row["parcel_id"],

        "portion_id":
            row["portion_id"],

        "transferred_area_decimal":
            float(
                row[
                    "transferred_area_decimal"
                ]
            ),

        "transaction_status":
            row["transaction_status"]
    }

    audit = audit_candidate_conflicts(
        transaction,
        large_reference_ledger_df,
        large_reference_history_df,
        scale_mutation_df,
        large_people_df,
        large_parcels_df
    )

    conflicts = audit["conflicts"]
    warnings = audit["warnings"]

    expected_conflict = (
        expected_conflict_map[
            row["scenario_label"]
        ]
    )

    if expected_conflict is None:

        pure = (
            len(conflicts) == 0
        )

    else:

        pure = (
            len(conflicts) == 1
            and conflicts[0]
            == expected_conflict
        )

    scale_purity_results.append({
        "candidate_id":
            row["candidate_id"],

        "scenario_label":
            row["scenario_label"],

        "expected_conflict":
            expected_conflict,

        "conflict_count":
            len(conflicts),

        "conflicts":
            conflicts,

        "warning_count":
            len(warnings),

        "warnings":
            warnings,

        "rule_pure":
            pure
    })


scale_purity_df = pd.DataFrame(
    scale_purity_results
)

In [1121]:
scale_pure_count = int(
    scale_purity_df[
        "rule_pure"
    ].sum()
)

scale_impure_count = int(
    (~scale_purity_df[
        "rule_pure"
    ]).sum()
)

print(
    "Rule-pure records:",
    scale_pure_count
)

print(
    "Impure records:",
    scale_impure_count
)

Rule-pure records: 600
Impure records: 0

In [1122]:
print(
    scale_purity_df[
        "conflict_count"
    ]
    .value_counts()
    .sort_index()
)

conflict_count
0    100
1    500
Name: count, dtype: int64

In [1123]:
scale_purity_by_class = (
    scale_purity_df
    .groupby(
        "scenario_label"
    )
    .agg(
        records=(
            "candidate_id",
            "count"
        ),

        pure_records=(
            "rule_pure",
            "sum"
        ),

        average_conflicts=(
            "conflict_count",
            "mean"
        )
    )
)

scale_purity_by_class

                   records  pure_records  average_conflicts
scenario_label
DOUBLE_SALE            100           100                1.0
DUPLICATE_DEED         100           100                1.0
MUTATION_MISMATCH      100           100                1.0
OVER_TRANSFER          100           100                1.0
SELLER_NOT_OWNER       100           100                1.0
VALID                  100           100                0.0

In [1124]:
print(
    "Reference history records:",
    len(
        large_reference_history_df
    )
)

print(
    "Reference ledger integrity:",
    check_ledger_integrity(
        large_reference_ledger_df,
        large_parcels_df
    )
)

Reference history records: 4
Reference ledger integrity: True

In [1125]:
assert len(
    scale_candidates_df
) == 600

assert scale_candidates_df[
    "scenario_label"
].nunique() == 6

assert scale_class_distribution.min() == 100
assert scale_class_distribution.max() == 100

assert scale_duplicate_candidate_ids == 0
assert scale_same_party_count == 0

assert scale_invalid_sellers == 0
assert scale_invalid_buyers == 0
assert scale_invalid_parcels == 0

assert scale_passed_count == 600
assert scale_failed_count == 0

assert scale_pure_count == 600
assert scale_impure_count == 0

assert len(
    large_reference_history_df
) == 4

assert check_ledger_integrity(
    large_reference_ledger_df,
    large_parcels_df
) is True

print(
    "600-record benchmark assertions: PASS"
)

600-record benchmark assertions: PASS

In [1126]:
print("STEP 16E SUMMARY")
print("----------------")

print(
    "Synthetic candidate records:",
    len(scale_candidates_df)
)

print(
    "Scenario classes:",
    scale_candidates_df[
        "scenario_label"
    ].nunique()
)

print(
    "Records per class:",
    scale_class_distribution.min()
)

print(
    "Ground-truth checks passed:",
    scale_passed_count
)

print(
    "Ground-truth checks failed:",
    scale_failed_count
)

print(
    "Primary-rule pure:",
    scale_pure_count
)

print(
    "Impure records:",
    scale_impure_count
)

print(
    "Seller = Buyer cases:",
    scale_same_party_count
)

print(
    "Duplicate candidate IDs:",
    scale_duplicate_candidate_ids
)

print(
    "Invalid seller references:",
    scale_invalid_sellers
)

print(
    "Invalid buyer references:",
    scale_invalid_buyers
)

print(
    "Invalid parcel references:",
    scale_invalid_parcels
)

print(
    "Reference history preserved:",
    len(
        large_reference_history_df
    ) == 4
)

print(
    "Reference ledger integrity:",
    check_ledger_integrity(
        large_reference_ledger_df,
        large_parcels_df
    )
)

print(
    "\n600-Record Controlled Benchmark: READY"
)

STEP 16E SUMMARY
----------------
Synthetic candidate records: 600
Scenario classes: 6
Records per class: 100
Ground-truth checks passed: 600
Ground-truth checks failed: 0
Primary-rule pure: 600
Impure records: 0
Seller = Buyer cases: 0
Duplicate candidate IDs: 0
Invalid seller references: 0
Invalid buyer references: 0
Invalid parcel references: 0
Reference history preserved: True
Reference ledger integrity: True

600-Record Controlled Benchmark: READY

# STEP 17A — Create Reusable BhumiGuard Source Package

Move the already-tested parcel and land-field normalization functions
from the notebook into reusable Python source code.

Project package:

src/
└── bhumiguard/
    ├── __init__.py
    └── normalization.py

In [1127]:
from pathlib import Path

PROJECT_ROOT = Path(r"D:\BhumiGuard-BD")

print("Project root:", PROJECT_ROOT)
print("Exists:", PROJECT_ROOT.exists())

Project root: D:\BhumiGuard-BD
Exists: True

In [1128]:
BHUMIGUARD_SRC = (
    PROJECT_ROOT
    / "src"
    / "bhumiguard"
)

BHUMIGUARD_SRC.mkdir(
    parents=True,
    exist_ok=True
)

print("Package folder:")
print(BHUMIGUARD_SRC)

print(
    "Exists:",
    BHUMIGUARD_SRC.exists()
)

Package folder:
D:\BhumiGuard-BD\src\bhumiguard
Exists: True

In [1129]:
init_file = (
    BHUMIGUARD_SRC
    / "__init__.py"
)

init_file.write_text(
    '"""BhumiGuard BD core package."""\n',
    encoding="utf-8"
)

print(
    "__init__.py created:",
    init_file.exists()
)

__init__.py created: True

In [1130]:
normalization_code = r'''
import re
import unicodedata


BANGLA_DIGITS = str.maketrans(
    "০১২৩৪৫৬৭৮৯",
    "0123456789"
)


SURVEY_ALIASES = {
    "CS": "CS",
    "C S": "CS",
    "C.S": "CS",
    "C.S.": "CS",
    "সি এস": "CS",

    "SA": "SA",
    "S A": "SA",
    "S.A": "SA",
    "S.A.": "SA",
    "এস এ": "SA",

    "RS": "RS",
    "R S": "RS",
    "R.S": "RS",
    "R.S.": "RS",
    "আর এস": "RS",

    "BS": "BS",
    "B S": "BS",
    "B.S": "BS",
    "B.S.": "BS",
    "বি এস": "BS",
}


def bangla_to_english_digits(value):
    if value is None:
        return None

    return str(value).translate(
        BANGLA_DIGITS
    )


def normalize_land_number(value):
    if value is None:
        return None

    value = bangla_to_english_digits(
        value
    )

    value = unicodedata.normalize(
        "NFKC",
        value
    )

    value = value.strip()

    labels = [
        "দাগ নং",
        "দাগ নম্বর",
        "দাগ",
        "খতিয়ান নং",
        "খতিয়ান নং",
        "খতিয়ান নম্বর",
        "খতিয়ান নম্বর",
        "খতিয়ান",
        "খতিয়ান",
        "নং",
        "নম্বর",
        "NO.",
        "NO",
    ]

    for label in labels:
        value = value.replace(
            label,
            ""
        )

    value = value.strip()

    digits = re.sub(
        r"[^0-9]",
        "",
        value
    )

    if digits == "":
        return None

    return str(
        int(digits)
    )


def normalize_survey_type(value):
    if value is None:
        return None

    value = unicodedata.normalize(
        "NFKC",
        str(value)
    )

    value = " ".join(
        value.strip()
        .upper()
        .split()
    )

    return SURVEY_ALIASES.get(
        value,
        value
    )


def normalize_location(value):
    if value is None:
        return None

    value = unicodedata.normalize(
        "NFKC",
        str(value)
    )

    value = " ".join(
        value.strip()
        .split()
    )

    return value.upper()


def create_parcel_key(
    district,
    upazila,
    mouza,
    survey_type,
    khatian_no,
    dag_no
):
    district_n = normalize_location(
        district
    )

    upazila_n = normalize_location(
        upazila
    )

    mouza_n = normalize_location(
        mouza
    )

    survey_n = normalize_survey_type(
        survey_type
    )

    khatian_n = normalize_land_number(
        khatian_no
    )

    dag_n = normalize_land_number(
        dag_no
    )

    components = [
        district_n,
        upazila_n,
        mouza_n,
        survey_n,
        khatian_n,
        dag_n,
    ]

    if any(
        value is None
        for value in components
    ):
        return None

    return "|".join(
        components
    )
'''

normalization_file = (
    BHUMIGUARD_SRC
    / "normalization.py"
)

normalization_file.write_text(
    normalization_code.strip()
    + "\n",
    encoding="utf-8"
)

print(
    "normalization.py created:",
    normalization_file.exists()
)

normalization.py created: True

In [1131]:
for path in sorted(
    BHUMIGUARD_SRC.iterdir()
):
    print(path.name)

__init__.py
normalization.py

In [1132]:
import sys

SRC_PATH = str(
    PROJECT_ROOT / "src"
)

if SRC_PATH not in sys.path:
    sys.path.insert(
        0,
        SRC_PATH
    )

print(
    "Source path ready:",
    SRC_PATH in sys.path
)

Source path ready: True

In [1133]:
from bhumiguard.normalization import (
    bangla_to_english_digits,
    normalize_land_number,
    normalize_survey_type,
    normalize_location,
    create_parcel_key,
)

print(
    "Normalization module import: PASS"
)

Normalization module import: PASS

In [1134]:
print(
    normalize_land_number(
        "দাগ নং ০০৭৩১"
    )
)

731

In [1135]:
print(
    normalize_survey_type(
        "আর এস"
    )
)

RS

In [1136]:
module_key_a = create_parcel_key(
    district="Demo-District-A",
    upazila="Demo-Upazila-A",
    mouza="Demo-Mouza-01",
    survey_type="RS",
    khatian_no="205",
    dag_no="731"
)

module_key_b = create_parcel_key(
    district=" demo-district-a ",
    upazila="Demo-Upazila-A",
    mouza="Demo-Mouza-01",
    survey_type="আর এস",
    khatian_no="খতিয়ান নং ২০৫",
    dag_no="দাগ নং ০০৭৩১"
)

print(
    "Key A:",
    module_key_a
)

print(
    "Key B:",
    module_key_b
)

print(
    "Same parcel:",
    module_key_a == module_key_b
)

Key A: DEMO-DISTRICT-A|DEMO-UPAZILA-A|DEMO-MOUZA-01|RS|205|731
Key B: DEMO-DISTRICT-A|DEMO-UPAZILA-A|DEMO-MOUZA-01|RS|205|731
Same parcel: True

In [1137]:
assert (
    bangla_to_english_digits(
        "১২৩৪৫"
    )
    == "12345"
)

assert (
    normalize_land_number(
        "দাগ নং ০০৭৩১"
    )
    == "731"
)

assert (
    normalize_land_number(
        "খতিয়ান নং ০০২০৫"
    )
    == "205"
)

assert (
    normalize_survey_type(
        "আর এস"
    )
    == "RS"
)

assert (
    normalize_survey_type(
        "C.S."
    )
    == "CS"
)

assert module_key_a == module_key_b

print(
    "Normalization module tests: PASS"
)

Normalization module tests: PASS

In [1138]:
print("STEP 17A SUMMARY")
print("----------------")

print(
    "Package folder exists:",
    BHUMIGUARD_SRC.exists()
)

print(
    "__init__.py exists:",
    init_file.exists()
)

print(
    "normalization.py exists:",
    normalization_file.exists()
)

print(
    "Bangla digit test:",
    bangla_to_english_digits(
        "৭৩১"
    )
)

print(
    "Land-number test:",
    normalize_land_number(
        "দাগ নং ০০৭৩১"
    )
)

print(
    "Survey test:",
    normalize_survey_type(
        "আর এস"
    )
)

print(
    "ParcelKey variant match:",
    module_key_a == module_key_b
)

print(
    "\nNormalization Module: READY"
)

STEP 17A SUMMARY
----------------
Package folder exists: True
__init__.py exists: True
normalization.py exists: True
Bangla digit test: 731
Land-number test: 731
Survey test: RS
ParcelKey variant match: True

Normalization Module: READY

# STEP 17B — Reusable Ownership Ledger Module

Move ownership and transaction-processing logic into:

src/bhumiguard/ledger.py

Responsibilities:

- current owner-area lookup
- ownership ID generation
- ledger-integrity validation
- safe transfer processing
- preservation of the original ledger when a transaction is rejected

In [1139]:
ledger_code = r'''
import pandas as pd


def get_owner_area(
    ledger_df,
    parcel_id,
    owner_id
):
    rows = ledger_df[
        (ledger_df["parcel_id"] == parcel_id) &
        (ledger_df["owner_id"] == owner_id) &
        (ledger_df["status"] == "ACTIVE")
    ]

    if rows.empty:
        return 0.0

    return float(
        rows["owned_area_decimal"].sum()
    )


def next_ownership_id(ledger_df):
    numbers = []

    for value in ledger_df["ownership_id"]:
        value = str(value)

        if value.startswith("OWN"):

            number = value[3:]

            if number.isdigit():
                numbers.append(
                    int(number)
                )

    next_number = (
        max(numbers, default=0) + 1
    )

    return f"OWN{next_number:03d}"


def check_ledger_integrity(
    ledger_df,
    parcels_df,
    tolerance=1e-9
):
    required_ledger_columns = {
        "ownership_id",
        "parcel_id",
        "owner_id",
        "owned_area_decimal",
        "status",
    }

    required_parcel_columns = {
        "parcel_id",
        "total_area_decimal",
    }

    if not required_ledger_columns.issubset(
        ledger_df.columns
    ):
        return False

    if not required_parcel_columns.issubset(
        parcels_df.columns
    ):
        return False

    # No negative ownership
    if (
        ledger_df[
            "owned_area_decimal"
        ] < 0
    ).any():
        return False

    # Every ownership row must reference a real parcel
    if (
        ~ledger_df[
            "parcel_id"
        ].isin(
            parcels_df[
                "parcel_id"
            ]
        )
    ).any():
        return False

    active = ledger_df[
        ledger_df["status"] == "ACTIVE"
    ].copy()

    active_totals = (
        active
        .groupby(
            "parcel_id",
            as_index=False
        )[
            "owned_area_decimal"
        ]
        .sum()
    )

    parcel_totals = parcels_df[
        [
            "parcel_id",
            "total_area_decimal"
        ]
    ].copy()

    comparison = parcel_totals.merge(
        active_totals,
        on="parcel_id",
        how="left"
    )

    comparison[
        "owned_area_decimal"
    ] = comparison[
        "owned_area_decimal"
    ].fillna(0.0)

    difference = (
        comparison[
            "owned_area_decimal"
        ]
        -
        comparison[
            "total_area_decimal"
        ]
    ).abs()

    return bool(
        (difference <= tolerance).all()
    )


def process_transfer(
    ledger_df,
    transaction,
    people_df,
    parcels_df
):
    original_ledger = (
        ledger_df.copy(deep=True)
    )

    updated_ledger = (
        ledger_df.copy(deep=True)
    )

    seller_id = transaction["seller_id"]
    buyer_id = transaction["buyer_id"]
    parcel_id = transaction["parcel_id"]

    transfer_area = float(
        transaction[
            "transferred_area_decimal"
        ]
    )

    person_ids = set(
        people_df["person_id"]
    )

    parcel_ids = set(
        parcels_df["parcel_id"]
    )

    # ---------------------------------
    # Basic validation
    # ---------------------------------

    if seller_id not in person_ids:

        return original_ledger, {
            "valid": False,
            "reason": "SELLER_NOT_FOUND"
        }

    if buyer_id not in person_ids:

        return original_ledger, {
            "valid": False,
            "reason": "BUYER_NOT_FOUND"
        }

    if parcel_id not in parcel_ids:

        return original_ledger, {
            "valid": False,
            "reason": "PARCEL_NOT_FOUND"
        }

    if seller_id == buyer_id:

        return original_ledger, {
            "valid": False,
            "reason": "SELLER_BUYER_SAME"
        }

    if transfer_area <= 0:

        return original_ledger, {
            "valid": False,
            "reason": "INVALID_TRANSFER_AREA"
        }

    # ---------------------------------
    # Seller ownership
    # ---------------------------------

    seller_available = get_owner_area(
        updated_ledger,
        parcel_id,
        seller_id
    )

    if seller_available <= 0:

        return original_ledger, {
            "valid": False,
            "reason": "SELLER_NOT_OWNER",
            "seller_available": 0.0
        }

    if transfer_area > seller_available:

        return original_ledger, {
            "valid": False,
            "reason":
                "INSUFFICIENT_OWNERSHIP",

            "seller_available":
                seller_available,

            "requested_area":
                transfer_area
        }

    # ---------------------------------
    # Deduct seller ownership
    # ---------------------------------

    seller_indices = updated_ledger[
        (updated_ledger["parcel_id"] == parcel_id) &
        (updated_ledger["owner_id"] == seller_id) &
        (updated_ledger["status"] == "ACTIVE")
    ].index.tolist()

    remaining_to_deduct = transfer_area

    for index in seller_indices:

        row_area = float(
            updated_ledger.loc[
                index,
                "owned_area_decimal"
            ]
        )

        deduction = min(
            row_area,
            remaining_to_deduct
        )

        new_area = (
            row_area - deduction
        )

        updated_ledger.loc[
            index,
            "owned_area_decimal"
        ] = new_area

        if abs(new_area) <= 1e-9:

            updated_ledger.loc[
                index,
                "owned_area_decimal"
            ] = 0.0

            updated_ledger.loc[
                index,
                "status"
            ] = "INACTIVE"

        remaining_to_deduct -= (
            deduction
        )

        if remaining_to_deduct <= 1e-9:
            break

    # ---------------------------------
    # Add buyer ownership
    # ---------------------------------

    buyer_indices = updated_ledger[
        (updated_ledger["parcel_id"] == parcel_id) &
        (updated_ledger["owner_id"] == buyer_id) &
        (updated_ledger["status"] == "ACTIVE")
    ].index.tolist()

    if buyer_indices:

        buyer_index = buyer_indices[0]

        updated_ledger.loc[
            buyer_index,
            "owned_area_decimal"
        ] = (
            float(
                updated_ledger.loc[
                    buyer_index,
                    "owned_area_decimal"
                ]
            )
            + transfer_area
        )

    else:

        new_row = {
            "ownership_id":
                next_ownership_id(
                    updated_ledger
                ),

            "parcel_id":
                parcel_id,

            "owner_id":
                buyer_id,

            "owned_area_decimal":
                transfer_area,

            "valid_from":
                transaction[
                    "execution_date"
                ],

            "status":
                "ACTIVE"
        }

        updated_ledger = pd.concat(
            [
                updated_ledger,
                pd.DataFrame(
                    [new_row]
                )
            ],
            ignore_index=True
        )

    # ---------------------------------
    # Final integrity protection
    # ---------------------------------

    if not check_ledger_integrity(
        updated_ledger,
        parcels_df
    ):

        return original_ledger, {
            "valid": False,
            "reason":
                "LEDGER_INTEGRITY_FAILURE"
        }

    return updated_ledger, {
        "valid": True,
        "reason": "VALID_TRANSFER",

        "seller_available_before":
            seller_available,

        "transferred_area":
            transfer_area
    }
'''

ledger_file = (
    BHUMIGUARD_SRC
    / "ledger.py"
)

ledger_file.write_text(
    ledger_code.strip() + "\n",
    encoding="utf-8"
)

print(
    "ledger.py created:",
    ledger_file.exists()
)

ledger.py created: True

In [1140]:
for path in sorted(
    BHUMIGUARD_SRC.iterdir()
):
    print(path.name)

__init__.py
__pycache__
ledger.py
normalization.py

In [1141]:
from bhumiguard.ledger import (
    get_owner_area as module_get_owner_area,
    next_ownership_id as module_next_ownership_id,
    check_ledger_integrity as module_check_ledger_integrity,
    process_transfer as module_process_transfer,
)

print(
    "Ledger module import: PASS"
)

Ledger module import: PASS

In [1142]:
print(
    "P001 / PAR001:",
    module_get_owner_area(
        ownership_df,
        "PAR001",
        "P001"
    )
)

print(
    "P003 / PAR001:",
    module_get_owner_area(
        ownership_df,
        "PAR001",
        "P003"
    )
)

P001 / PAR001: 20.0
P003 / PAR001: 0.0

In [1143]:
print(
    "Next ownership ID:",
    module_next_ownership_id(
        ownership_df
    )
)

Next ownership ID: OWN006

In [1144]:
print(
    "Initial small ledger integrity:",
    module_check_ledger_integrity(
        ownership_df,
        parcels_df
    )
)

print(
    "Large reference ledger integrity:",
    module_check_ledger_integrity(
        large_reference_ledger_df,
        large_parcels_df
    )
)

Initial small ledger integrity: True
Large reference ledger integrity: True

In [1145]:
module_valid_transaction = {
    "deed_id": "MODULE-TEST-001",
    "deed_type": "SAF_KABALA",
    "execution_date": "2026-09-01",

    "seller_id": "P001",
    "buyer_id": "P002",

    "parcel_id": "PAR001",

    "transferred_area_decimal": 5.0
}

In [1146]:
(
    module_valid_ledger,
    module_valid_result
) = module_process_transfer(
    ownership_df,
    module_valid_transaction,
    people_df,
    parcels_df
)

print(module_valid_result)

{'valid': True, 'reason': 'VALID_TRANSFER', 'seller_available_before': 20.0, 'transferred_area': 5.0}

In [1147]:
print(
    "Seller after:",
    module_get_owner_area(
        module_valid_ledger,
        "PAR001",
        "P001"
    )
)

print(
    "Buyer after:",
    module_get_owner_area(
        module_valid_ledger,
        "PAR001",
        "P002"
    )
)

print(
    "Updated ledger integrity:",
    module_check_ledger_integrity(
        module_valid_ledger,
        parcels_df
    )
)

Seller after: 15.0
Buyer after: 5.0
Updated ledger integrity: True

In [1148]:
print(
    "Original seller ownership:",
    module_get_owner_area(
        ownership_df,
        "PAR001",
        "P001"
    )
)

Original seller ownership: 20.0

In [1149]:
module_invalid_transaction = {
    "deed_id": "MODULE-TEST-002",
    "deed_type": "SAF_KABALA",
    "execution_date": "2026-09-02",

    "seller_id": "P003",
    "buyer_id": "P004",

    "parcel_id": "PAR001",

    "transferred_area_decimal": 1.0
}

In [1150]:
(
    module_invalid_ledger,
    module_invalid_result
) = module_process_transfer(
    ownership_df,
    module_invalid_transaction,
    people_df,
    parcels_df
)

print(module_invalid_result)

{'valid': False, 'reason': 'SELLER_NOT_OWNER', 'seller_available': 0.0}

In [1151]:
module_rejected_unchanged = (
    ownership_df.equals(
        module_invalid_ledger
    )
)

print(
    "Rejected transaction preserves ledger:",
    module_rejected_unchanged
)

Rejected transaction preserves ledger: True

In [1152]:
module_over_transaction = {
    "deed_id": "MODULE-TEST-003",
    "deed_type": "SAF_KABALA",
    "execution_date": "2026-09-03",

    "seller_id": "P001",
    "buyer_id": "P003",

    "parcel_id": "PAR001",

    "transferred_area_decimal": 25.0
}

In [1153]:
(
    module_over_ledger,
    module_over_result
) = module_process_transfer(
    ownership_df,
    module_over_transaction,
    people_df,
    parcels_df
)

print(module_over_result)

{'valid': False, 'reason': 'INSUFFICIENT_OWNERSHIP', 'seller_available': 20.0, 'requested_area': 25.0}

In [1154]:
corrupted_ledger = ownership_df.copy()

corrupted_ledger.loc[
    corrupted_ledger[
        "parcel_id"
    ] == "PAR001",
    "owned_area_decimal"
] = 19.0

print(
    "Corrupted ledger integrity:",
    module_check_ledger_integrity(
        corrupted_ledger,
        parcels_df
    )
)

Corrupted ledger integrity: False

In [1155]:
assert module_get_owner_area(
    ownership_df,
    "PAR001",
    "P001"
) == 20.0

assert module_next_ownership_id(
    ownership_df
) == "OWN006"

assert module_check_ledger_integrity(
    ownership_df,
    parcels_df
) is True

assert module_valid_result[
    "reason"
] == "VALID_TRANSFER"

assert module_get_owner_area(
    module_valid_ledger,
    "PAR001",
    "P001"
) == 15.0

assert module_get_owner_area(
    module_valid_ledger,
    "PAR001",
    "P002"
) == 5.0

assert module_invalid_result[
    "reason"
] == "SELLER_NOT_OWNER"

assert module_rejected_unchanged is True

assert module_over_result[
    "reason"
] == "INSUFFICIENT_OWNERSHIP"

assert module_check_ledger_integrity(
    corrupted_ledger,
    parcels_df
) is False

print(
    "Ledger module tests: PASS"
)

Ledger module tests: PASS

In [1156]:
large_module_integrity = (
    module_check_ledger_integrity(
        large_reference_ledger_df,
        large_parcels_df
    )
)

print(
    "600-benchmark reference ledger:",
    large_module_integrity
)

600-benchmark reference ledger: True

In [1157]:
print("STEP 17B SUMMARY")
print("----------------")

print(
    "ledger.py exists:",
    ledger_file.exists()
)

print(
    "Owner lookup test:",
    module_get_owner_area(
        ownership_df,
        "PAR001",
        "P001"
    )
)

print(
    "Valid transfer:",
    module_valid_result[
        "reason"
    ]
)

print(
    "Seller after valid transfer:",
    module_get_owner_area(
        module_valid_ledger,
        "PAR001",
        "P001"
    )
)

print(
    "Buyer after valid transfer:",
    module_get_owner_area(
        module_valid_ledger,
        "PAR001",
        "P002"
    )
)

print(
    "Seller-not-owner test:",
    module_invalid_result[
        "reason"
    ]
)

print(
    "Over-transfer test:",
    module_over_result[
        "reason"
    ]
)

print(
    "Rejected ledger unchanged:",
    module_rejected_unchanged
)

print(
    "Corrupted ledger rejected:",
    not module_check_ledger_integrity(
        corrupted_ledger,
        parcels_df
    )
)

print(
    "Large reference integrity:",
    large_module_integrity
)

print(
    "\nOwnership Ledger Module: READY"
)

STEP 17B SUMMARY
----------------
ledger.py exists: True
Owner lookup test: 20.0
Valid transfer: VALID_TRANSFER
Seller after valid transfer: 15.0
Buyer after valid transfer: 5.0
Seller-not-owner test: SELLER_NOT_OWNER
Over-transfer test: INSUFFICIENT_OWNERSHIP
Rejected ledger unchanged: True
Corrupted ledger rejected: True
Large reference integrity: True

Ownership Ledger Module: READY

# STEP 17C — Reusable Validation Module

Move transaction-history and cross-record validation logic into:

src/bhumiguard/validation.py

Responsibilities:

- duplicate deed detection
- repeated portion / double-sale detection
- deed-mutation consistency checking
- combined transaction validation
- preserving ledger/history when a transaction is rejected

In [1158]:
validation_code = r'''
import pandas as pd

from .ledger import process_transfer


def check_duplicate_deed(
    history_df,
    deed_id
):
    matches = history_df[
        history_df["deed_id"] == deed_id
    ]

    if matches.empty:
        return {
            "duplicate": False,
            "reason": "DEED_ID_AVAILABLE"
        }

    return {
        "duplicate": True,
        "reason": "DUPLICATE_DEED",
        "existing_records": len(matches)
    }


def check_double_sale(
    history_df,
    transaction
):
    portion_id = transaction.get(
        "portion_id"
    )

    if portion_id is None:
        return {
            "double_sale": False,
            "reason": "NO_PORTION_ID"
        }

    required_columns = {
        "parcel_id",
        "portion_id",
        "transaction_status",
        "deed_id",
        "buyer_id",
    }

    if not required_columns.issubset(
        history_df.columns
    ):
        return {
            "double_sale": False,
            "reason": "HISTORY_SCHEMA_INCOMPLETE"
        }

    previous_sales = history_df[
        (
            history_df["parcel_id"]
            == transaction["parcel_id"]
        )
        &
        (
            history_df["portion_id"]
            == portion_id
        )
        &
        (
            history_df[
                "transaction_status"
            ]
            == "VALID"
        )
    ]

    if previous_sales.empty:
        return {
            "double_sale": False,
            "reason": "NO_PREVIOUS_SALE"
        }

    return {
        "double_sale": True,
        "reason": "DOUBLE_SALE",

        "previous_deeds":
            previous_sales[
                "deed_id"
            ].tolist(),

        "previous_buyers":
            previous_sales[
                "buyer_id"
            ].tolist(),
    }


def check_deed_mutation_match(
    mutation_df,
    transaction
):
    required_columns = {
        "parcel_id",
        "portion_id",
        "mutation_owner_id",
        "status",
    }

    if not required_columns.issubset(
        mutation_df.columns
    ):
        return {
            "match": None,
            "reason":
                "MUTATION_SCHEMA_INCOMPLETE"
        }

    records = mutation_df[
        (
            mutation_df["parcel_id"]
            == transaction["parcel_id"]
        )
        &
        (
            mutation_df["portion_id"]
            == transaction.get(
                "portion_id"
            )
        )
        &
        (
            mutation_df["status"]
            == "ACTIVE"
        )
    ]

    if records.empty:
        return {
            "match": None,
            "reason": "NO_MUTATION_RECORD"
        }

    mutation_owners = set(
        records[
            "mutation_owner_id"
        ]
    )

    deed_seller = transaction[
        "seller_id"
    ]

    if deed_seller in mutation_owners:
        return {
            "match": True,
            "reason": "MUTATION_MATCH",
            "mutation_owners":
                sorted(
                    mutation_owners
                ),
        }

    return {
        "match": False,
        "reason":
            "DEED_MUTATION_MISMATCH",

        "deed_seller":
            deed_seller,

        "mutation_owners":
            sorted(
                mutation_owners
            ),
    }


def process_transfer_full_checks(
    ledger_df,
    history_df,
    mutation_df,
    transaction,
    people_df,
    parcels_df
):
    original_ledger = (
        ledger_df.copy(deep=True)
    )

    original_history = (
        history_df.copy(deep=True)
    )

    # ---------------------------------
    # 1. Duplicate deed
    # ---------------------------------

    duplicate_result = (
        check_duplicate_deed(
            history_df,
            transaction["deed_id"]
        )
    )

    if duplicate_result["duplicate"]:

        return (
            original_ledger,
            original_history,
            {
                "valid": False,
                "reason": "DUPLICATE_DEED",
                "existing_records":
                    duplicate_result[
                        "existing_records"
                    ],
            }
        )

    # ---------------------------------
    # 2. Double-sale
    # ---------------------------------

    double_sale_result = (
        check_double_sale(
            history_df,
            transaction
        )
    )

    if double_sale_result[
        "double_sale"
    ]:

        return (
            original_ledger,
            original_history,
            {
                "valid": False,
                "reason": "DOUBLE_SALE",

                "previous_deeds":
                    double_sale_result[
                        "previous_deeds"
                    ],

                "previous_buyers":
                    double_sale_result[
                        "previous_buyers"
                    ],
            }
        )

    # ---------------------------------
    # 3. Mutation consistency
    # ---------------------------------

    mutation_result = (
        check_deed_mutation_match(
            mutation_df,
            transaction
        )
    )

    if mutation_result["match"] is False:

        return (
            original_ledger,
            original_history,
            {
                "valid": False,
                "reason":
                    "DEED_MUTATION_MISMATCH",

                "deed_seller":
                    mutation_result[
                        "deed_seller"
                    ],

                "mutation_owners":
                    mutation_result[
                        "mutation_owners"
                    ],
            }
        )

    # ---------------------------------
    # 4. Ownership / transfer validation
    # ---------------------------------

    (
        updated_ledger,
        transfer_result
    ) = process_transfer(
        ledger_df,
        transaction,
        people_df,
        parcels_df
    )

    if not transfer_result["valid"]:

        return (
            original_ledger,
            original_history,
            transfer_result
        )

    # ---------------------------------
    # 5. Store accepted transaction
    # ---------------------------------

    accepted_transaction = (
        transaction.copy()
    )

    accepted_transaction[
        "transaction_status"
    ] = "VALID"

    updated_history = pd.concat(
        [
            original_history,
            pd.DataFrame(
                [accepted_transaction]
            )
        ],
        ignore_index=True
    )

    return (
        updated_ledger,
        updated_history,
        {
            "valid": True,
            "reason": "VALID_TRANSFER",

            "mutation_status":
                mutation_result[
                    "reason"
                ],
        }
    )
'''

validation_file = (
    BHUMIGUARD_SRC
    / "validation.py"
)

validation_file.write_text(
    validation_code.strip() + "\n",
    encoding="utf-8"
)

print(
    "validation.py created:",
    validation_file.exists()
)

validation.py created: True

In [1159]:
for path in sorted(
    BHUMIGUARD_SRC.iterdir()
):
    print(path.name)

__init__.py
__pycache__
ledger.py
normalization.py
validation.py

In [1160]:
import importlib
import bhumiguard.validation

importlib.reload(
    bhumiguard.validation
)

from bhumiguard.validation import (
    check_duplicate_deed as module_check_duplicate_deed,
    check_double_sale as module_check_double_sale,
    check_deed_mutation_match as module_check_deed_mutation_match,
    process_transfer_full_checks as module_process_transfer_full_checks,
)

print(
    "Validation module import: PASS"
)

Validation module import: PASS

In [1161]:
module_duplicate_result = (
    module_check_duplicate_deed(
        large_reference_history_df,
        "DEED1001"
    )
)

print(
    module_duplicate_result
)

{'duplicate': True, 'reason': 'DUPLICATE_DEED', 'existing_records': 1}

In [1162]:
print(
    module_check_duplicate_deed(
        large_reference_history_df,
        "NEW-DEED-999"
    )
)

{'duplicate': False, 'reason': 'DEED_ID_AVAILABLE'}

In [1163]:
module_double_sale_tx = {
    "deed_id": "MODULE-DS-001",
    "deed_type": "SAF_KABALA",
    "execution_date": "2026-09-10",

    "seller_id": "P001",
    "buyer_id": "P025",

    "parcel_id": "PAR001",
    "portion_id": "PAR001-PART-A",

    "transferred_area_decimal": 1.0,
    "transaction_status": "PENDING"
}

module_double_sale_result = (
    module_check_double_sale(
        large_reference_history_df,
        module_double_sale_tx
    )
)

print(
    module_double_sale_result
)

{'double_sale': True, 'reason': 'DOUBLE_SALE', 'previous_deeds': ['DEED1001'], 'previous_buyers': ['P021']}

In [1164]:
module_mutation_match_tx = {
    "deed_id": "MODULE-MMATCH-001",
    "seller_id": "P005",
    "buyer_id": "P025",

    "parcel_id": "PAR005",
    "portion_id": "PAR005-PART-B",

    "transferred_area_decimal": 1.0
}

module_mutation_match_result = (
    module_check_deed_mutation_match(
        large_mutation_df,
        module_mutation_match_tx
    )
)

print(
    module_mutation_match_result
)

{'match': True, 'reason': 'MUTATION_MATCH', 'mutation_owners': ['P005']}

In [1165]:
module_mutation_mismatch_tx = {
    "deed_id": "MODULE-MM-001",
    "seller_id": "P009",
    "buyer_id": "P025",

    "parcel_id": "PAR009",
    "portion_id": "PAR009-PART-B",

    "transferred_area_decimal": 1.0
}

module_mutation_mismatch_result = (
    module_check_deed_mutation_match(
        scenario_mutation_df,
        module_mutation_mismatch_tx
    )
)

print(
    module_mutation_mismatch_result
)

{'match': False, 'reason': 'DEED_MUTATION_MISMATCH', 'deed_seller': 'P009', 'mutation_owners': ['P030']}

In [1166]:
module_full_valid_tx = {
    "deed_id": "MODULE-VALID-001",
    "deed_type": "SAF_KABALA",
    "execution_date": "2026-09-15",

    "seller_id": "P005",
    "buyer_id": "P025",

    "parcel_id": "PAR005",
    "portion_id": "PAR005-PART-B",

    "transferred_area_decimal": 1.0,
    "transaction_status": "PENDING"
}

In [1167]:
(
    module_full_valid_ledger,
    module_full_valid_history,
    module_full_valid_result
) = module_process_transfer_full_checks(
    large_reference_ledger_df,
    large_reference_history_df,
    large_mutation_df,
    module_full_valid_tx,
    large_people_df,
    large_parcels_df
)

print(
    module_full_valid_result
)

{'valid': True, 'reason': 'VALID_TRANSFER', 'mutation_status': 'MUTATION_MATCH'}

In [1168]:
p005_before = module_get_owner_area(
    large_reference_ledger_df,
    "PAR005",
    "P005"
)

p005_after = module_get_owner_area(
    module_full_valid_ledger,
    "PAR005",
    "P005"
)

p025_after = module_get_owner_area(
    module_full_valid_ledger,
    "PAR005",
    "P025"
)

print(
    "P005 before:",
    p005_before
)

print(
    "P005 after:",
    p005_after
)

print(
    "P025 after:",
    p025_after
)

print(
    "History before:",
    len(
        large_reference_history_df
    )
)

print(
    "History after:",
    len(
        module_full_valid_history
    )
)

P005 before: 15.0
P005 after: 14.0
P025 after: 1.0
History before: 4
History after: 5

In [1169]:
module_full_duplicate_tx = {
    "deed_id": "DEED1001",
    "deed_type": "SAF_KABALA",
    "execution_date": "2026-09-16",

    "seller_id": "P005",
    "buyer_id": "P025",

    "parcel_id": "PAR005",
    "portion_id": "PAR005-PART-B",

    "transferred_area_decimal": 1.0,
    "transaction_status": "PENDING"
}

In [1170]:
(
    module_dup_ledger,
    module_dup_history,
    module_dup_result
) = module_process_transfer_full_checks(
    large_reference_ledger_df,
    large_reference_history_df,
    large_mutation_df,
    module_full_duplicate_tx,
    large_people_df,
    large_parcels_df
)

print(module_dup_result)

{'valid': False, 'reason': 'DUPLICATE_DEED', 'existing_records': 1}

In [1171]:
module_duplicate_ledger_unchanged = (
    large_reference_ledger_df.equals(
        module_dup_ledger
    )
)

module_duplicate_history_unchanged = (
    large_reference_history_df.equals(
        module_dup_history
    )
)

print(
    "Ledger unchanged:",
    module_duplicate_ledger_unchanged
)

print(
    "History unchanged:",
    module_duplicate_history_unchanged
)

Ledger unchanged: True
History unchanged: True

In [1172]:
(
    module_ds_ledger,
    module_ds_history,
    module_ds_result
) = module_process_transfer_full_checks(
    large_reference_ledger_df,
    large_reference_history_df,
    large_mutation_df,
    module_double_sale_tx,
    large_people_df,
    large_parcels_df
)

print(
    module_ds_result
)

{'valid': False, 'reason': 'DOUBLE_SALE', 'previous_deeds': ['DEED1001'], 'previous_buyers': ['P021']}

In [1173]:
module_full_mismatch_tx = {
    "deed_id": "MODULE-MM-002",
    "deed_type": "SAF_KABALA",
    "execution_date": "2026-09-18",

    "seller_id": "P009",
    "buyer_id": "P025",

    "parcel_id": "PAR009",
    "portion_id": "PAR009-PART-B",

    "transferred_area_decimal": 1.0,
    "transaction_status": "PENDING"
}

In [1174]:
(
    module_mm_ledger,
    module_mm_history,
    module_mm_result
) = module_process_transfer_full_checks(
    large_reference_ledger_df,
    large_reference_history_df,
    scenario_mutation_df,
    module_full_mismatch_tx,
    large_people_df,
    large_parcels_df
)

print(
    module_mm_result
)

{'valid': False, 'reason': 'DEED_MUTATION_MISMATCH', 'deed_seller': 'P009', 'mutation_owners': ['P030']}

In [1175]:
module_missing_mutation_tx = {
    "deed_id": "MODULE-NOMUT-001",
    "deed_type": "SAF_KABALA",
    "execution_date": "2026-09-19",

    "seller_id": "P005",
    "buyer_id": "P026",

    "parcel_id": "PAR005",
    "portion_id": "PAR005-PART-Z",

    "transferred_area_decimal": 1.0,
    "transaction_status": "PENDING"
}

In [1176]:
module_missing_mutation_check = (
    module_check_deed_mutation_match(
        large_mutation_df,
        module_missing_mutation_tx
    )
)

print(
    module_missing_mutation_check
)

{'match': None, 'reason': 'NO_MUTATION_RECORD'}

In [1177]:
assert module_duplicate_result[
    "reason"
] == "DUPLICATE_DEED"

assert module_double_sale_result[
    "reason"
] == "DOUBLE_SALE"

assert module_mutation_match_result[
    "reason"
] == "MUTATION_MATCH"

assert module_mutation_mismatch_result[
    "reason"
] == "DEED_MUTATION_MISMATCH"

assert module_full_valid_result[
    "reason"
] == "VALID_TRANSFER"

assert len(
    module_full_valid_history
) == (
    len(
        large_reference_history_df
    ) + 1
)

assert module_dup_result[
    "reason"
] == "DUPLICATE_DEED"

assert module_duplicate_ledger_unchanged is True
assert module_duplicate_history_unchanged is True

assert module_ds_result[
    "reason"
] == "DOUBLE_SALE"

assert module_mm_result[
    "reason"
] == "DEED_MUTATION_MISMATCH"

assert module_missing_mutation_check[
    "reason"
] == "NO_MUTATION_RECORD"

assert module_check_ledger_integrity(
    module_full_valid_ledger,
    large_parcels_df
) is True

print(
    "Validation module tests: PASS"
)

Validation module tests: PASS

In [1178]:
module_benchmark_passed = 0
module_benchmark_failed = 0

for _, row in scale_candidates_df.iterrows():

    transaction = {
        "deed_id":
            row["deed_id"],

        "deed_type":
            row["deed_type"],

        "execution_date":
            row["execution_date"],

        "seller_id":
            row["seller_id"],

        "buyer_id":
            row["buyer_id"],

        "parcel_id":
            row["parcel_id"],

        "portion_id":
            row["portion_id"],

        "transferred_area_decimal":
            float(
                row[
                    "transferred_area_decimal"
                ]
            ),

        "transaction_status":
            row["transaction_status"]
    }

    (
        _ledger,
        _history,
        result
    ) = module_process_transfer_full_checks(
        large_reference_ledger_df,
        large_reference_history_df,
        scale_mutation_df,
        transaction,
        large_people_df,
        large_parcels_df
    )

    if (
        result["reason"]
        == row["expected_decision"]
    ):
        module_benchmark_passed += 1
    else:
        module_benchmark_failed += 1

In [1179]:
print(
    "Module benchmark passed:",
    module_benchmark_passed
)

print(
    "Module benchmark failed:",
    module_benchmark_failed
)

Module benchmark passed: 600
Module benchmark failed: 0

In [1180]:
assert module_benchmark_passed == 600
assert module_benchmark_failed == 0

print(
    "600-record validation compatibility: PASS"
)

600-record validation compatibility: PASS

In [1181]:
print("STEP 17C SUMMARY")
print("----------------")

print(
    "validation.py exists:",
    validation_file.exists()
)

print(
    "Duplicate-deed test:",
    module_duplicate_result[
        "reason"
    ]
)

print(
    "Double-sale test:",
    module_double_sale_result[
        "reason"
    ]
)

print(
    "Mutation-match test:",
    module_mutation_match_result[
        "reason"
    ]
)

print(
    "Mutation-mismatch test:",
    module_mutation_mismatch_result[
        "reason"
    ]
)

print(
    "Missing mutation test:",
    module_missing_mutation_check[
        "reason"
    ]
)

print(
    "Valid full processing:",
    module_full_valid_result[
        "reason"
    ]
)

print(
    "Rejected ledger unchanged:",
    module_duplicate_ledger_unchanged
)

print(
    "Rejected history unchanged:",
    module_duplicate_history_unchanged
)

print(
    "600 benchmark passed:",
    module_benchmark_passed
)

print(
    "600 benchmark failed:",
    module_benchmark_failed
)

print(
    "\nValidation Module: READY"
)

STEP 17C SUMMARY
----------------
validation.py exists: True
Duplicate-deed test: DUPLICATE_DEED
Double-sale test: DOUBLE_SALE
Mutation-match test: MUTATION_MATCH
Mutation-mismatch test: DEED_MUTATION_MISMATCH
Missing mutation test: NO_MUTATION_RECORD
Valid full processing: VALID_TRANSFER
Rejected ledger unchanged: True
Rejected history unchanged: True
600 benchmark passed: 600
600 benchmark failed: 0

Validation Module: READY

# STEP 17D — Explainable Risk Engine Module

Move the explainable pre-registration screening logic into:

src/bhumiguard/risk.py

Responsibilities:

- independently evaluate verification rules
- produce PASS / WARNING / FAIL results
- calculate LOW / MEDIUM / HIGH screening risk
- generate explainable rule messages
- never modify ownership or transaction history

In [1182]:
risk_code = r'''
from .ledger import get_owner_area

from .validation import (
    check_duplicate_deed,
    check_double_sale,
    check_deed_mutation_match,
)


def evaluate_transaction_rules(
    ledger_df,
    history_df,
    mutation_df,
    transaction,
    people_df,
    parcels_df
):
    rules = {}

    seller_id = transaction["seller_id"]
    buyer_id = transaction["buyer_id"]
    parcel_id = transaction["parcel_id"]
    deed_id = transaction["deed_id"]

    transfer_area = float(
        transaction[
            "transferred_area_decimal"
        ]
    )

    person_ids = set(
        people_df["person_id"]
    )

    parcel_ids = set(
        parcels_df["parcel_id"]
    )

    # ---------------------------------
    # Rule 1: Deed ID
    # ---------------------------------

    duplicate_result = (
        check_duplicate_deed(
            history_df,
            deed_id
        )
    )

    if duplicate_result["duplicate"]:

        rules["deed_id_check"] = {
            "status": "FAIL",
            "code": "DUPLICATE_DEED",
            "message": (
                f"Deed ID {deed_id} "
                "already exists in the "
                "accepted transaction history."
            )
        }

    else:

        rules["deed_id_check"] = {
            "status": "PASS",
            "code": "DEED_ID_AVAILABLE",
            "message":
                "Deed ID is not duplicated."
        }

    # ---------------------------------
    # Rule 2: Party references
    # ---------------------------------

    if seller_id not in person_ids:

        rules["seller_reference_check"] = {
            "status": "FAIL",
            "code": "SELLER_NOT_FOUND",
            "message":
                "Seller was not found in the registry."
        }

    else:

        rules["seller_reference_check"] = {
            "status": "PASS",
            "code": "SELLER_FOUND",
            "message":
                "Seller exists in the registry."
        }

    if buyer_id not in person_ids:

        rules["buyer_reference_check"] = {
            "status": "FAIL",
            "code": "BUYER_NOT_FOUND",
            "message":
                "Buyer was not found in the registry."
        }

    elif seller_id == buyer_id:

        rules["buyer_reference_check"] = {
            "status": "FAIL",
            "code": "SELLER_BUYER_SAME",
            "message":
                "Seller and buyer cannot be the same party."
        }

    else:

        rules["buyer_reference_check"] = {
            "status": "PASS",
            "code": "BUYER_FOUND",
            "message":
                "Buyer exists and differs from the seller."
        }

    # ---------------------------------
    # Rule 3: Parcel reference
    # ---------------------------------

    parcel_exists = (
        parcel_id in parcel_ids
    )

    if parcel_exists:

        rules["parcel_check"] = {
            "status": "PASS",
            "code": "PARCEL_FOUND",
            "message":
                "Parcel exists in the registry."
        }

    else:

        rules["parcel_check"] = {
            "status": "FAIL",
            "code": "PARCEL_NOT_FOUND",
            "message":
                "Parcel was not found in the registry."
        }

    # ---------------------------------
    # Rule 4: Seller ownership
    # ---------------------------------

    seller_area = get_owner_area(
        ledger_df,
        parcel_id,
        seller_id
    )

    if seller_area > 0:

        rules["seller_ownership_check"] = {
            "status": "PASS",
            "code": "SELLER_IS_OWNER",
            "message": (
                f"Seller currently owns "
                f"{seller_area} decimal "
                "in the parcel."
            )
        }

    else:

        rules["seller_ownership_check"] = {
            "status": "FAIL",
            "code": "SELLER_NOT_OWNER",
            "message":
                "Seller has no active ownership "
                "in this parcel."
        }

    # ---------------------------------
    # Rule 5: Transfer area
    # ---------------------------------

    if transfer_area <= 0:

        rules["area_check"] = {
            "status": "FAIL",
            "code":
                "INVALID_TRANSFER_AREA",
            "message":
                "Transfer area must be positive."
        }

    elif (
        seller_area > 0
        and transfer_area > seller_area
    ):

        rules["area_check"] = {
            "status": "FAIL",
            "code":
                "INSUFFICIENT_OWNERSHIP",

            "message": (
                f"Requested transfer is "
                f"{transfer_area} decimal, "
                f"but the seller currently "
                f"owns {seller_area} decimal."
            )
        }

    elif seller_area <= 0:

        rules["area_check"] = {
            "status": "WARNING",
            "code":
                "AREA_CHECK_NOT_APPLICABLE",

            "message":
                "Transfer-area sufficiency cannot "
                "be confirmed because seller "
                "ownership is unavailable."
        }

    else:

        rules["area_check"] = {
            "status": "PASS",
            "code": "AREA_AVAILABLE",
            "message": (
                f"Requested transfer of "
                f"{transfer_area} decimal "
                "is within seller ownership."
            )
        }

    # ---------------------------------
    # Rule 6: Double-sale
    # ---------------------------------

    double_sale_result = (
        check_double_sale(
            history_df,
            transaction
        )
    )

    if double_sale_result[
        "double_sale"
    ]:

        rules["double_sale_check"] = {
            "status": "FAIL",
            "code": "DOUBLE_SALE",
            "message":
                "The same identified land portion "
                "appears in a previous valid sale."
        }

    elif (
        double_sale_result["reason"]
        == "NO_PORTION_ID"
    ):

        rules["double_sale_check"] = {
            "status": "WARNING",
            "code":
                "PORTION_ID_UNAVAILABLE",
            "message":
                "Double-sale verification is "
                "incomplete because no portion "
                "identifier is available."
        }

    elif (
        double_sale_result["reason"]
        == "HISTORY_SCHEMA_INCOMPLETE"
    ):

        rules["double_sale_check"] = {
            "status": "WARNING",
            "code":
                "HISTORY_SCHEMA_INCOMPLETE",
            "message":
                "Transaction history does not contain "
                "all fields required for double-sale "
                "verification."
        }

    else:

        rules["double_sale_check"] = {
            "status": "PASS",
            "code": "NO_PREVIOUS_SALE",
            "message":
                "No previous valid sale was found "
                "for this identified portion."
        }

    # ---------------------------------
    # Rule 7: Mutation consistency
    # ---------------------------------

    mutation_result = (
        check_deed_mutation_match(
            mutation_df,
            transaction
        )
    )

    if mutation_result["match"] is True:

        rules["mutation_check"] = {
            "status": "PASS",
            "code": "MUTATION_MATCH",
            "message":
                "Deed seller matches the active "
                "mutation-side owner."
        }

    elif mutation_result["match"] is False:

        mutation_owners = ", ".join(
            mutation_result[
                "mutation_owners"
            ]
        )

        rules["mutation_check"] = {
            "status": "FAIL",
            "code":
                "DEED_MUTATION_MISMATCH",

            "message": (
                f"Deed seller is {seller_id}, "
                f"while the mutation-side record "
                f"lists {mutation_owners}."
            )
        }

    elif (
        mutation_result["reason"]
        == "MUTATION_SCHEMA_INCOMPLETE"
    ):

        rules["mutation_check"] = {
            "status": "WARNING",
            "code":
                "MUTATION_SCHEMA_INCOMPLETE",

            "message":
                "Mutation data does not contain "
                "all fields required for verification."
        }

    else:

        rules["mutation_check"] = {
            "status": "WARNING",
            "code": "NO_MUTATION_RECORD",
            "message":
                "No matching mutation record is "
                "available for this parcel portion."
        }

    return rules


def calculate_risk_level(rules):
    pass_count = sum(
        result["status"] == "PASS"
        for result in rules.values()
    )

    warning_count = sum(
        result["status"] == "WARNING"
        for result in rules.values()
    )

    fail_count = sum(
        result["status"] == "FAIL"
        for result in rules.values()
    )

    if fail_count > 0:
        risk_level = "HIGH"

    elif warning_count > 0:
        risk_level = "MEDIUM"

    else:
        risk_level = "LOW"

    return {
        "risk_level":
            risk_level,

        "pass_count":
            pass_count,

        "warning_count":
            warning_count,

        "fail_count":
            fail_count,
    }


def verify_transaction(
    ledger_df,
    history_df,
    mutation_df,
    transaction,
    people_df,
    parcels_df
):
    rules = evaluate_transaction_rules(
        ledger_df,
        history_df,
        mutation_df,
        transaction,
        people_df,
        parcels_df
    )

    summary = calculate_risk_level(
        rules
    )

    return {
        "deed_id":
            transaction["deed_id"],

        "parcel_id":
            transaction["parcel_id"],

        "seller_id":
            transaction["seller_id"],

        "buyer_id":
            transaction["buyer_id"],

        "risk_level":
            summary["risk_level"],

        "pass_count":
            summary["pass_count"],

        "warning_count":
            summary["warning_count"],

        "fail_count":
            summary["fail_count"],

        "rules":
            rules,

        "disclaimer":
            (
                "Screening result only. "
                "It does not establish legal title "
                "or prove fraud."
            ),
    }


def format_risk_report(report):
    lines = []

    lines.append(
        "BHUMIGUARD BD — PRE-REGISTRATION CHECK"
    )

    lines.append(
        "=" * 50
    )

    lines.append(
        f"Deed: {report['deed_id']}"
    )

    lines.append(
        f"Parcel: {report['parcel_id']}"
    )

    lines.append(
        f"Seller: {report['seller_id']}"
    )

    lines.append(
        f"Buyer: {report['buyer_id']}"
    )

    lines.append("")
    lines.append("RULE CHECKS")
    lines.append("-" * 50)

    for result in report[
        "rules"
    ].values():

        lines.append(
            f"{result['status']:7} | "
            f"{result['code']}"
        )

        lines.append(
            f"          {result['message']}"
        )

    lines.append("")
    lines.append("SUMMARY")
    lines.append("-" * 50)

    lines.append(
        f"PASS: {report['pass_count']}"
    )

    lines.append(
        f"WARNING: {report['warning_count']}"
    )

    lines.append(
        f"FAIL: {report['fail_count']}"
    )

    lines.append(
        f"OVERALL RISK: "
        f"{report['risk_level']}"
    )

    lines.append("")
    lines.append(
        report["disclaimer"]
    )

    return "\n".join(lines)
'''

risk_file = (
    BHUMIGUARD_SRC
    / "risk.py"
)

risk_file.write_text(
    risk_code.strip() + "\n",
    encoding="utf-8"
)

print(
    "risk.py created:",
    risk_file.exists()
)

risk.py created: True

In [1183]:
for path in sorted(
    BHUMIGUARD_SRC.iterdir()
):
    print(path.name)

__init__.py
__pycache__
ledger.py
normalization.py
risk.py
validation.py

In [1184]:
import importlib
import bhumiguard.risk

importlib.reload(
    bhumiguard.risk
)

from bhumiguard.risk import (
    evaluate_transaction_rules as module_evaluate_rules,
    calculate_risk_level as module_calculate_risk,
    verify_transaction as module_verify_transaction,
    format_risk_report as module_format_risk_report,
)

print(
    "Risk module import: PASS"
)

Risk module import: PASS

In [1186]:
module_low_tx = {
    "deed_id": "RISK-LOW-001",
    "deed_type": "SAF_KABALA",
    "execution_date": "2026-10-01",

    "seller_id": "P005",
    "buyer_id": "P025",

    "parcel_id": "PAR005",
    "portion_id": "PAR005-PART-B",

    "transferred_area_decimal": 1.0,
    "transaction_status": "PENDING"
}

In [1187]:
module_low_report = (
    module_verify_transaction(
        large_reference_ledger_df,
        large_reference_history_df,
        large_mutation_df,
        module_low_tx,
        large_people_df,
        large_parcels_df
    )
)

print(
    "Risk:",
    module_low_report["risk_level"]
)

print(
    "PASS:",
    module_low_report["pass_count"]
)

print(
    "WARNING:",
    module_low_report["warning_count"]
)

print(
    "FAIL:",
    module_low_report["fail_count"]
)

Risk: LOW
PASS: 8
WARNING: 0
FAIL: 0

In [1188]:
module_medium_tx = {
    "deed_id": "RISK-MEDIUM-001",
    "deed_type": "SAF_KABALA",
    "execution_date": "2026-10-02",

    "seller_id": "P005",
    "buyer_id": "P026",

    "parcel_id": "PAR005",
    "portion_id": "PAR005-PART-Z",

    "transferred_area_decimal": 1.0,
    "transaction_status": "PENDING"
}

In [1189]:
module_medium_report = (
    module_verify_transaction(
        large_reference_ledger_df,
        large_reference_history_df,
        large_mutation_df,
        module_medium_tx,
        large_people_df,
        large_parcels_df
    )
)

print(
    "Risk:",
    module_medium_report["risk_level"]
)

print(
    "Warning:",
    module_medium_report["warning_count"]
)

print(
    "Mutation:",
    module_medium_report[
        "rules"
    ]["mutation_check"]["code"]
)

Risk: MEDIUM
Warning: 1
Mutation: NO_MUTATION_RECORD

In [1190]:
module_high_tx = {
    "deed_id": "RISK-HIGH-001",
    "deed_type": "SAF_KABALA",
    "execution_date": "2026-10-03",

    "seller_id": "P009",
    "buyer_id": "P025",

    "parcel_id": "PAR009",
    "portion_id": "PAR009-PART-B",

    "transferred_area_decimal": 1.0,
    "transaction_status": "PENDING"
}

In [1191]:
module_high_report = (
    module_verify_transaction(
        large_reference_ledger_df,
        large_reference_history_df,
        scenario_mutation_df,
        module_high_tx,
        large_people_df,
        large_parcels_df
    )
)

print(
    "Risk:",
    module_high_report["risk_level"]
)

print(
    "Fail:",
    module_high_report["fail_count"]
)

print(
    "Mutation:",
    module_high_report[
        "rules"
    ]["mutation_check"]["code"]
)

Risk: HIGH
Fail: 1
Mutation: DEED_MUTATION_MISMATCH

In [1192]:
print(
    module_format_risk_report(
        module_high_report
    )
)

BHUMIGUARD BD — PRE-REGISTRATION CHECK
==================================================
Deed: RISK-HIGH-001
Parcel: PAR009
Seller: P009
Buyer: P025

RULE CHECKS
--------------------------------------------------
PASS    | DEED_ID_AVAILABLE
          Deed ID is not duplicated.
PASS    | SELLER_FOUND
          Seller exists in the registry.
PASS    | BUYER_FOUND
          Buyer exists and differs from the seller.
PASS    | PARCEL_FOUND
          Parcel exists in the registry.
PASS    | SELLER_IS_OWNER
          Seller currently owns 25.0 decimal in the parcel.
PASS    | AREA_AVAILABLE
          Requested transfer of 1.0 decimal is within seller ownership.
PASS    | NO_PREVIOUS_SALE
          No previous valid sale was found for this identified portion.
FAIL    | DEED_MUTATION_MISMATCH
          Deed seller is P009, while the mutation-side record lists P030.

SUMMARY
--------------------------------------------------
PASS: 7
WARNING: 0
FAIL: 1
OVERALL RISK: HIGH

Screening result only. It does not establish legal title or prove fraud.

In [1193]:
risk_ledger_snapshot = (
    large_reference_ledger_df.copy(
        deep=True
    )
)

risk_history_snapshot = (
    large_reference_history_df.copy(
        deep=True
    )
)

_ = module_verify_transaction(
    large_reference_ledger_df,
    large_reference_history_df,
    scenario_mutation_df,
    module_high_tx,
    large_people_df,
    large_parcels_df
)

risk_ledger_unchanged = (
    risk_ledger_snapshot.equals(
        large_reference_ledger_df
    )
)

risk_history_unchanged = (
    risk_history_snapshot.equals(
        large_reference_history_df
    )
)

print(
    "Ledger unchanged:",
    risk_ledger_unchanged
)

print(
    "History unchanged:",
    risk_history_unchanged
)

Ledger unchanged: True
History unchanged: True

In [1194]:
expected_risk_map = {
    "VALID": "LOW",

    "SELLER_NOT_OWNER":
        "HIGH",

    "OVER_TRANSFER":
        "HIGH",

    "DOUBLE_SALE":
        "HIGH",

    "DUPLICATE_DEED":
        "HIGH",

    "MUTATION_MISMATCH":
        "HIGH",
}

In [1196]:
risk_benchmark_results = []

for _, row in scale_candidates_df.iterrows():

    transaction = {
        "deed_id":
            row["deed_id"],

        "deed_type":
            row["deed_type"],

        "execution_date":
            row["execution_date"],

        "seller_id":
            row["seller_id"],

        "buyer_id":
            row["buyer_id"],

        "parcel_id":
            row["parcel_id"],

        "portion_id":
            row["portion_id"],

        "transferred_area_decimal":
            float(
                row[
                    "transferred_area_decimal"
                ]
            ),

        "transaction_status":
            row["transaction_status"]
    }

    report = module_verify_transaction(
        large_reference_ledger_df,
        large_reference_history_df,
        scale_mutation_df,
        transaction,
        large_people_df,
        large_parcels_df
    )

    expected_risk = (
        expected_risk_map[
            row["scenario_label"]
        ]
    )

    risk_benchmark_results.append({
        "candidate_id":
            row["candidate_id"],

        "scenario_label":
            row["scenario_label"],

        "expected_risk":
            expected_risk,

        "actual_risk":
            report["risk_level"],

        "passed":
            report["risk_level"]
            == expected_risk
    })

In [1197]:
risk_benchmark_df = pd.DataFrame(
    risk_benchmark_results
)

risk_benchmark_passed = int(
    risk_benchmark_df[
        "passed"
    ].sum()
)

risk_benchmark_failed = int(
    (~risk_benchmark_df[
        "passed"
    ]).sum()
)

print(
    "Risk benchmark passed:",
    risk_benchmark_passed
)

print(
    "Risk benchmark failed:",
    risk_benchmark_failed
)

Risk benchmark passed: 600
Risk benchmark failed: 0

In [1198]:
print(
    risk_benchmark_df[
        "actual_risk"
    ].value_counts()
)

actual_risk
HIGH    500
LOW     100
Name: count, dtype: int64

In [1199]:
expected_code_map = {
    "VALID": None,

    "SELLER_NOT_OWNER":
        "SELLER_NOT_OWNER",

    "OVER_TRANSFER":
        "INSUFFICIENT_OWNERSHIP",

    "DOUBLE_SALE":
        "DOUBLE_SALE",

    "DUPLICATE_DEED":
        "DUPLICATE_DEED",

    "MUTATION_MISMATCH":
        "DEED_MUTATION_MISMATCH",
}

In [1200]:
risk_code_passed = 0
risk_code_failed = 0

for _, row in scale_candidates_df.iterrows():

    transaction = {
        "deed_id": row["deed_id"],
        "deed_type": row["deed_type"],
        "execution_date":
            row["execution_date"],
        "seller_id": row["seller_id"],
        "buyer_id": row["buyer_id"],
        "parcel_id": row["parcel_id"],
        "portion_id": row["portion_id"],
        "transferred_area_decimal":
            float(
                row[
                    "transferred_area_decimal"
                ]
            ),
        "transaction_status":
            row["transaction_status"]
    }

    report = module_verify_transaction(
        large_reference_ledger_df,
        large_reference_history_df,
        scale_mutation_df,
        transaction,
        large_people_df,
        large_parcels_df
    )

    expected_code = (
        expected_code_map[
            row["scenario_label"]
        ]
    )

    fail_codes = [
        result["code"]
        for result
        in report["rules"].values()
        if result["status"] == "FAIL"
    ]

    if expected_code is None:

        passed = (
            len(fail_codes) == 0
        )

    else:

        passed = (
            expected_code
            in fail_codes
        )

    if passed:
        risk_code_passed += 1
    else:
        risk_code_failed += 1

In [1201]:
print(
    "Expected rule codes passed:",
    risk_code_passed
)

print(
    "Expected rule codes failed:",
    risk_code_failed
)

Expected rule codes passed: 600
Expected rule codes failed: 0

In [1202]:
assert module_low_report[
    "risk_level"
] == "LOW"

assert module_low_report[
    "fail_count"
] == 0

assert module_low_report[
    "warning_count"
] == 0

assert module_medium_report[
    "risk_level"
] == "MEDIUM"

assert module_medium_report[
    "rules"
]["mutation_check"]["code"] \
    == "NO_MUTATION_RECORD"

assert module_high_report[
    "risk_level"
] == "HIGH"

assert module_high_report[
    "rules"
]["mutation_check"]["code"] \
    == "DEED_MUTATION_MISMATCH"

assert risk_ledger_unchanged is True
assert risk_history_unchanged is True

assert risk_benchmark_passed == 600
assert risk_benchmark_failed == 0

assert risk_code_passed == 600
assert risk_code_failed == 0

print(
    "Risk module tests: PASS"
)

Risk module tests: PASS

In [1203]:
print("STEP 17D SUMMARY")
print("----------------")

print(
    "risk.py exists:",
    risk_file.exists()
)

print(
    "LOW test:",
    module_low_report[
        "risk_level"
    ]
)

print(
    "MEDIUM test:",
    module_medium_report[
        "risk_level"
    ]
)

print(
    "HIGH test:",
    module_high_report[
        "risk_level"
    ]
)

print(
    "High-risk code:",
    module_high_report[
        "rules"
    ][
        "mutation_check"
    ][
        "code"
    ]
)

print(
    "Risk check preserves ledger:",
    risk_ledger_unchanged
)

print(
    "Risk check preserves history:",
    risk_history_unchanged
)

print(
    "600 risk benchmark passed:",
    risk_benchmark_passed
)

print(
    "600 risk benchmark failed:",
    risk_benchmark_failed
)

print(
    "Expected rule codes passed:",
    risk_code_passed
)

print(
    "Expected rule codes failed:",
    risk_code_failed
)

print(
    "\nExplainable Risk Module: READY"
)

STEP 17D SUMMARY
----------------
risk.py exists: True
LOW test: LOW
MEDIUM test: MEDIUM
HIGH test: HIGH
High-risk code: DEED_MUTATION_MISMATCH
Risk check preserves ledger: True
Risk check preserves history: True
600 risk benchmark passed: 600
600 risk benchmark failed: 0
Expected rule codes passed: 600
Expected rule codes failed: 0

Explainable Risk Module: READY